### ISSUE TITLE
Cursor not highlighting correct row in Gmail

### ISSUE THREAD

**Issue by vancleve** [wavebox/waveboxapp#903] opened 2019-01-13 15:58 UTC
* Wavebox Version: 4.5.10
* Operating System & Version: Mac OS 10.12.6 (also seen on 10.13)
* Account type (if applicable): gmail

I have been having a persistent though intermittent bug in Gmail where after command-tabbing back to Wavebox, the cursor is aligned correctly with its target; specifically, the email highlighted is a row below the position of the cursor. When I click to go to the email (or mailbox), Wavebox treats that as a click and hold.  When I move the cursor into the labels pane and up out of the window frame and then back, this seems to fix the problem (temporarily).

The installed extensions I have are Slack++, Dropbox, and Dark Reader. I had the same problem on 10.13 with another laptop and only had the Dropbox extension installed.

Video below demonstrates the problem.

![wavebox_cursor_problem](https://user-images.githubusercontent.com/1442334/51087473-ea133e00-1721-11e9-93ea-a7b39863de36.gif)

**Comment by Thomas101** [comment] 2019-01-15 08:38
Thanks for reporting and for the video. I've managed to reproduce this here - although it does take a little while for it to kick in. Out of curiosity, roughly how long would you say it takes for the behaviour to appear for you?

Would you be able to try a couple of things your end, hopefully it will help me get to the root cause of it...
1. When the issue comes, up does doing anything to the window, such as resizing it change the behaviour?
2. Right click on the account in the left, and then `Account Settings`. Under the tools section, double click `Clear all browsing data`. You'll need to sign back into the account, but does this fix it at all?
3. Try disabling dropbox, and run the app for a little while again. Does that fix it?

**Comment by vancleve** [comment] 2019-01-16 01:02
It seems like it takes 10 minutes or so away from Wavebox before the issue crops up.

Resizing the window seems to fix the problem during that interaction with the app.

I'm working on trying the other things you suggested 😄

**Comment by vancleve** [comment] 2019-01-16 01:10
Having cleared all browsing data, the problem still comes back

**Comment by vancleve** [comment] 2019-01-16 08:31
Disabling dropbox also doesn't fix it.

**Comment by Thomas101** [comment] 2019-01-16 10:36
Thanks for trying those! I did suspect that disabling dropbox would fix it, but it looks like I'm barking up the wrong tree with that 🤔. Maybe the setup I'm trying it with is different here...

* Does it seem to be the amount of time you spend away from the app, or is it the amount of time the app is open?
* Do you have Gmail offline enabled? You can check this out by opening your Gmail Settings within Gmail, then going to the offline tab
* Do you have any Gmail add-ons enabled? You can check this out by opening your Gmail Settings within Gmail, then going to the Add-ons tab and checking if anything is listed

A few other things to try changing, which might help...
* Try removing all extensions - I did suspect it was something to do with this, but just to make sure
* Go to Settings > Advanced, disable `Sandboxing` and enable `Isolate Account Processes` to see if that makes any difference

Thanks!

**Comment by vancleve** [comment] 2019-01-21 22:59
Ok, so disabling all the extensions seems to have helped and the problem went away.

I don't have gmail offline or other gmail add-ons

I haven't tried the sandboxing.

I'm now running Wavebox on my normal macbook pro with Mojave and all seems fine. I installed the dropbox plugin and the problem hasn't come up after a day but I'll mention it if it does.

**Comment by Thomas101** [comment] 2019-01-23 16:13
Seeing that you're not seeing this anymore, I'll close this off. If it comes up again though, just recomment and I'll take another look. Thanks for taking the time to report!

**Closed by Thomas101** 2019-01-23 16:13 UTC
Labels: bug, follow-up, os:macOS
