### ISSUE TITLE
skype - selecting emoji flashes and move icons around in popup

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#630] opened 2018-03-26 13:29 UTC
* Which version of Wavebox are you using?
3.13.0

* Which Operating System are you using?
windows 10

* Description:
Popup for selecting emoji flashes and moves emojis around. Hard to select emoji in popup box.

* Expected Result:
Stable select where icons are not moved around in window.

**Comment by nmat** [comment] 2018-03-28 09:08
I am going to try and create something to show you. I have tested to reload it and tested windowed and fullscreen with same flashy effect.

**Comment by nmat** [comment] 2018-03-28 20:00
I can't reproduce it here on my home machine: 1709 (OS Build 16299.334) very odd.

**Comment by nmat** [comment] 2018-03-29 07:07
This might be related to using wavebox on hidpi devices. Tested at home and do not have hidpi there. Using laptop that is using hidpi does however show the flashing of emoji.

**Comment by Thomas101** [comment] 2018-04-11 12:41
We've given this a try and aren't able to reproduce here. After changing your settings/plugging your monitor in, have you logged out and back into windows? There seem to be lots of broken artefacts in the standard windows UI until you do this (for example huge scrollbars, tiny menus etc)

**Comment by nmat** [comment] 2018-05-10 06:58
This could be a problem with hidpi and electron 2.0 might fix this also. When wavebox is done to use electron 2.0 I can give it a try again.

**Comment by Thomas101** [comment] 2018-07-20 13:00
@nmat are you still seeing this with the newer versions?

**Comment by Thomas101** [comment] 2018-09-10 10:26
@nmat have you seen this behaviour with Wavebox 3.14.* or 4.0?

**Comment by nmat** [comment] 2018-09-10 10:49
Yes I can even reproduce it and it seems that it happens on zoom. If I use standard zoom size the problem does not occur. It happens on even first zoom.

**Comment by Thomas101** [comment] 2018-09-10 10:51
Thanks, will see if I can get to the bottom of it :)

**Comment by nmat** [comment] 2018-09-10 10:53
Yes I am going to try it on different computers also and give more feedback.

**Comment by Thomas101** [comment] 2018-09-12 09:01
It looks like a bug with Skype. I've managed to reproduce on macOS in Wavebox and Chrome 69. It only happens when zoom is 110%, works fine in 100% and 120% and a varying selection of others beyond that.

This gif below is from Chrome 69. First run at 100%, second 110% and third 120%.
![sep-12-2018 09-52-33](https://user-images.githubusercontent.com/103586/45413779-da9bbf80-b671-11e8-85ef-c4998dd9363f.gif)

IMO it looks like a rounding issue in webkit or the styling that skype uses but can't say for sure. Going to close this off as it looks like affects browser too and is an issue with Skype

**Closed by Thomas101** 2018-09-12 09:01 UTC
Labels: investigate, os:windows
