### ISSUE TITLE
Keyboard change of services using Ctrl+Shift+number window flashes

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#450] opened 2017-11-02 09:43 UTC
* Which version of Wavebox are you using?
3.5.0

* Which Operating System are you using?
Windows 10

* Description:
There are 2 odd effects using Ctrl+Shift+Number and I will list them below

1. Window "reloads" or flashes on change with keyboard but not with mouse click
- I am using 2 different windows on one screen so they split the area: | wavebox | atom |
- When I click the service for Google calendar the wavebox app does not flash or reload but changes to the service smoothly
- When I use Ctrl+Shift+2 then a odd reload or something happens and the inner window flashes.
(Note! This does not happen if I have wavebox in fullscreen and do the same type of change using keyboard)

2. Using office365 the keyboard change of service inside does not highlight or underscore the service
- Inside office365 I try changing the service to calendar or onedrive using keyboard
- The service is not highlighted or underscored as active. The content however does change so I can see that the service is another when changing but its not highlighting

The one common problem I can see is when using "Allow services to indicate when sleeping"

When this option is enabled then office365 will not show the highlight change.

I tested to restart wavebox now. And the gmail account no longer flashes (maybe this happens if I have had the computer sleeping)?

**Comment by Thomas101** [comment] 2017-11-06 11:37
Sounds like something may have wrong there. If it happens again can you hit <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> to open the developer tools and click on the console tab do you have any errors there? If so can you send a screenshot?

**Comment by nmat** [comment] 2017-11-06 12:08
I think I know why....it could be that the Ctrl+Shift combo is being used when inside office365 for the internal keyboard shortcut to change the view.

In this case the tab change does not occur but inside for example office365 (outlook it would change the tab in the office site instead of the tab in wavebox) so the combination is being used for internal office365 site also.

**Comment by nmat** [comment] 2017-11-06 12:11
I think that if Ctrl+LeftAlt+Number is used. Instead of Ctrl+Shift then that problem would go away. Not 100% sure though. :/

**Comment by nmat** [comment] 2017-11-06 13:03
Sorry....I mean Shift+LeftAlt+Number should be better then Ctrl+Shift+Number

One more reason for this is that for hand posture that combination is more natural than Ctrl+Shift+Number

**Comment by Thomas101** [comment] 2017-11-07 10:59
Okay yeah, I see the same now. Let me take a look to see if I can disable the keyboard shortcuts

**Comment by Thomas101** [comment] 2017-11-21 09:29
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment] 2017-11-22 07:39
hmmm I just tested this. So here is the setup:

office365 - first main service - has calendar, onedrive and contacts
teams - (using weblink) - main service 2

If I go to office365 and want to change with Ctrl+Shift+2 it jumps to teams tab. That is the same as hitting Ctrl+2

If I hit Ctrl+Shift+3 then it jumps to the next major service right after that one and so on.

If I am in the gsuite then the Ctrl+Shift+Number works as intended though.

**Comment by Thomas101** [comment] 2017-11-22 10:39
What do you have setup under Settings > Advanced > Keyboard Accelerators > Service at Index?

**Comment by nmat** [comment] 2017-11-22 10:53
Do you mean in office365 or in wavebox? I can't find a setting for that in office365 maybe because I am not admin?

**Comment by Thomas101** [comment] 2017-11-22 11:31
Sorry, in Wavebox

**Comment by nmat** [comment] 2017-11-22 12:02
@Thomas101 thank you. Here is the bindings.

Service at Index - Ctrl+Shift+Number
Account at Index - CmdOrCtrl+Number

**Comment by Thomas101** [comment] 2017-11-22 14:23
Ah yeah, I only had one account added which is why I wasn't seeing the behaviour. It looks like there is some kind of conflict in electron with this meaning that ctrl+shift+N is overwritten by ctrl+N.

In terms of other options, the only other thing I can think of is Ctrl+F1, F2 etc... but I'm hesitant to start using the F-keys for compatability reasons.

We're keen to get this next release out as it's got some important fixes in it, so I'm going to set the default as un-mapped and we'll take a deeper dive into what we can do following this release and hopefully fix ctrl+shift+N.

**Comment by nmat** [comment] 2017-11-22 14:28
Yeah I agree. It is in fact also better for consistency to use the same kind of binding on all of the services with underlying indexed services. Unfortunately I do not have any good idea here either.

**Comment by nmat** [comment] 2017-12-20 21:11
I noticed now that this is even more importat after the index services added for microsoft services.

I can Ctrl+Shift+1 from Teams -> Inbox

But inside inbox if I go Ctrl+Shift+2 it changes to the second service in the main service list. I think that most people using office365 will have issues with this in the future.

Me myself I can handle it in the way it is.....but might be good to have it overwritten due to services added?

**Comment by Thomas101** [comment] 2017-12-21 09:07
Hmmmm, I thought I was capturing the Ctrl+Shift+Numer behaviour in https://github.com/wavebox/waveboxapp/commit/60d15e6d3f0ae904bc01323fbc8c51e02bae4370#diff-991a2cfe75fa30c2f3b2539e324a9fe5 but obviously not. Have you just seen this on Windows or have you come across it on macOS/linux too?

**Comment by nmat** [comment] 2017-12-21 09:18
Yeah it seems to not change (inside inbox where you have the calendar etc) but if using the indexed services then it switches the main services.

Tests are done on windows 10 1703 (OS Build 15063.786) 

The setup I have is like this:
Service #1 - Office365 - indexed services (in order) - Inbox, Teams, Calendar, onedrive, People
Service #2 - Zendesk (using manual weblink) 
Service #3 - Trello

etc

So I Ctrl+1 to Office365, then Ctrl+Shift+2 and it will change to zendesk instead of Teams.

Another test: Ctrl+1 to Office365, manually clicked on Teams located on service index #2 and then Ctrl+Shift+1. At this point it will go to inbox.

This all seems to be just related to where the mails are located. Does this help?

**Comment by Thomas101** [comment] 2018-03-15 12:56
I've been doing some more investigation into this. Found the root cause - not so close to a fix yet.

What's actually happening here is Microsoft binds to the same keyboard shortcut as Wavebox. When you press the keyboard shortcut the Microsoft webpage actually reloads itself to the designated url - which is what causes the flash. Not so great as we're providing a unified way to do this, you might have services ordered differently etc etc.

#### Underlying problem
The hosted page is actually calling code to the following effect, which intercepts the keystroke, prevents it and does something else...
```js
window.addEventListener('keydown', (evt) => {
  evt.preventDefault()
}, true)
```
This works as per the html spec, the guest page should get these before the browser commands do. So for example you could overwrite <kbd>Ctrl</kbd>+<kbd>C</kbd> to do something else for example. This is the behaviour that all the major browsers exhibit, so you could almost say that it's not a bug, more of an undesired behaviour for us.

#### Changing behaviour with electron APIs
As for looking for a fix, there is a `webContents.on('before-input-event', ...` event that I've looked at utilizing. This effectively gets the keydown event before the page and can be prevented from there. I've already put some specific patches in for certain accounts, but this doesn't work across the board.

If the guest page doesn't bind to `keydown` event, the `before-input-event` doesn't get called, but the app accelerators do. This is the desired behaviour.

Once the guest page does bind to the `keydown` event and prevent the event, the app accelerators don't get called but `before-input-event` does. Arguably you could just intercept this here and re-dispatch the accelerator to get the desired behaviour. Unfortunately, the info that comes back across the API is problematic. The key that normally comes back (e.g. <kbd>i</kbd>) can end up being (rightly) transformed into another key when <kbd>alt</kbd> is pressed. In this instance <kbd>i</kbd> becomes the <kbd>Dead</kbd> keystroke. The transformation from the <kbd>alt</kbd> key depends on the users keyboard layout and language setup - which causes a bit of a nightmare in trying to re-map back to the setup accelerators.

#### Looking for a fix
There's probably a few ways to do this, none ideal...
1. Pick out the users keyboard layout have a complete list of alt combos. Then once we have this dispatch to the app first. We're guaranteed to miss some alt-codes and get some wrong though.
2. Patch electron to have non-standard behaviour and dispatch to the app accelerators rather than the page.
3. Patch electron to prevent preventing the default dispatch from the guest page on an opt-in basis depending on the tab that's loaded. This might actually need us to patch chromium though.
4. Drop the accelerators from the app menu and instead bind as globalshortcuts - however experience in doing this in the past has left shortcuts bound after the app has been running and just a real mess.

If we're patching the app to have non-standard browser behaviour we're going to break something. For example, Google Docs overwrites Copy and Paste to do something different and would break given a behaviour change. This means we're down to patching on an opt-in basis, which could mean patching chromium.

None of the options look particularly nice at the moment. I suspect whatever we do though will require some kind of patch to Electron. I've had a quick look through the source but haven't spotted anything easily obvious to patch.

**Comment by Thomas101** [comment] 2018-03-15 12:57
Going to move this off the 3.11 milestone for now as it's just being moved from one to the next. Adding to the `upstream:electron` and `investigate` labels so we can look through it a bit more

**Comment by Thomas101** [comment] 2018-09-25 10:15
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment, I'm happy to-open and I’ll take another look. Thanks

**Closed by Thomas101** 2018-09-25 10:15 UTC
Labels: bug, investigate, more-info, upstream: electron
