### ISSUE TITLE
Mixmax enabled does not allow attachment download in Gmail

### ISSUE THREAD

**Issue by themiguelamador** [wavebox/waveboxapp#449] opened 2017-11-01 16:54 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.5.1beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS 10.13.1 Beta

When clicking to download on Gmail in attachments nothing happens. Using Mixmax but not seems to be related as it does not change anything there. Download works for instance in google drive. 

Here are my settings.

<img width="567" alt="screen shot 2017-11-01 at 17 51 30" src="https://user-images.githubusercontent.com/2944764/32286333-61463d7c-bf2d-11e7-809b-f5e6b8c80caf.png">

**Comment by nmat** [comment] 2017-11-01 17:01
Just tested it on macOS High Sierra 10.13 with wavebox 3.5.1 beta and the popup do come up for me in gmail. I do not have Mixmax installed only markdown

**Comment by themiguelamador** [comment] 2017-11-01 17:04
Yes, Mixmax somehow is the issue! After disabling it, started working fine.

**Comment by nmat** [comment] 2017-11-01 17:10
Yes I have verified it on macOS and Windows 10 now.

Somethine odd is going on with the extension causing the attachments to not be able to be downloaded.

If possible can you change topic on this issue to something like "Mixmax enabled does not allow attachment download in Gmail"?

its mostly to pin point the root cause of the issue in general

**Comment by Thomas101** [comment] 2017-11-02 08:30
Thanks! I'll take a look as to what Mixmax is doing/what we're not handling

**Comment by Thomas101** [comment] 2017-11-07 14:21
I've just pushed a fix for this to the extension config. You don't need to update Wavebox, but will need to remove Mixmax and re-add it again this time. After that you should be able to download attachments again :)

**Closed by Thomas101** 2017-11-07 14:21 UTC
Labels: bug, extensions
