### ISSUE TITLE
[FEATURE REQUEST] Add words to dictionaries

### ISSUE THREAD

**Issue by AnInsaneScientist** [wavebox/waveboxapp#267] opened 2017-06-20 21:13 UTC
Loving Wavebox so far and I use it every day. I use it for emails, Trello, and Workflowy. I do a lot of writing when I write emails and I often write massive notes in Workflowy when I am doing research or something. In Wavebox I will often get spelling errors when I have none and none when I should have one. 

This is frustrating because of how much writing I do in the application. I have no way of adding a correct word to the dictionary. I would love if Wavebox was altered so I can add words to dictionaries. Also, I would be super grateful if Grammarly could be somehow integrated into Wavebox, this would be a gamechanger for me.

**Comment by Thomas101** [comment] 2017-06-21 11:59
Add to dictionary: Duplicate of https://github.com/wavebox/waveboxapp/issues/143. Due to be released in 3.1.9

Grammarly: falls under extension support (https://github.com/wavebox/waveboxapp/issues/138). There's a voting form there, make sure you add your vote in for grammarly (although it's currently leading)

Thanks :)

**Closed by Thomas101** 2017-06-21 11:59 UTC
Labels: duplicate

**Comment by AnInsaneScientist** [comment] 2017-06-22 16:29
Thank you for the update! Awesome to hear you're working on integrating extensions. I'm definitely glad to have paid for Wavebox Pro and support the development :)
