### ISSUE TITLE
Mailto links are not working.

### ISSUE THREAD

**Issue by braffas** [wavebox/waveboxapp#382] opened 2017-09-11 12:58 UTC
* Which version of Wavebox are you using? [3.3.2]

* Which Operating System are you using? [Windows 10]

mailto links are not working. It stopped working recently, last update i think.

Wavebox is opening when i click the mailto link, account selector pops up, and a new message is created, but the 'to' address is not going into the 'to' field.

I hope a for a fast solution since i'm quite addicted to Wavebox now :)

**Comment by Thomas101** [comment] 2017-09-12 07:40
I'll get a patch out into the next beta. Looks like Google have changed the underlying layout of the compose window

**Comment by Thomas101** [comment] 2017-09-18 11:48
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.3.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by braffas** [comment] 2017-09-18 14:45
Fantastic! It works again.

Thank you :)

2017-09-18 13:48 GMT+02:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment] 2017-09-18 15:25
Awesome, great to hear :)

**Closed** 2017-10-04 10:22 UTC
Labels: account:google, bug

**Comment by jottr** [comment] 2020-09-03 16:02
There seems to be a regression for this bug.
Clicking mailto links opens **Wavebox** and goes straight to my Gmail Inbox.. 
The "new message" form is not activated.

```
Wavebox version:
Version 4.11.12 beta (dmg)

---

ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021

```
