### ISSUE TITLE
Window height is always set to max

### ISSUE THREAD

**Issue by amig** [wavebox/waveboxapp#277] opened 2017-06-26 06:19 UTC
Every time I reopen Wavebox, the app window is reset to my screen's max height.

* Which version of Wavebox are you using? 3.1.12 (problem started with 3.1.8)

* Which Operating System are you using? Ubuntu 16.04.2

**Comment by Thomas101** [comment] 2017-06-26 09:07
Thanks. It looks like the window positioning is not being maintained

**Comment by Thomas101** [comment] 2017-07-07 10:13
Hi we've just released this into the beta channel if you want to give a try. There's some instructions on how to [get the latest beta release here](https://wavebox.io/kb/beta-channel). Thanks!

**Comment by amig** [comment] 2017-07-09 07:08
After installing the beta I got the following error when trying to launch the app:

> error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

**Comment by Thomas101** [comment] 2017-07-10 11:04
If you run `ps aux | grep Wavebox` are there any processes running? Could you check the version of libXss that's installed by doing `dpkg -s libxss1`?

**Comment by amig** [comment] 2017-07-10 13:39
Lots of processes.

Package: libxss1
Status: install ok installed
Priority: optional
Architecture: amd64
Multi-Arch: same
Version: 1:1.2.2-1

**Comment by Thomas101** [comment] 2017-07-11 08:04
if you try running `killall -9 Wavebox` and try starting again does it launch or still the same issue?

**Comment by amig** [comment] 2017-07-11 08:41
I reinstalled. No Wavebox process is running. Same error.

I also noticed that after installing the beta version, Wavebox launcher was deleted.

**Comment by Thomas101** [comment] 2017-07-11 08:47
That's weird! Which install method did you use? (e.g. deb, snap, tar)?

**Comment by amig** [comment] 2017-07-11 09:08
deb

**Comment by Thomas101** [comment] 2017-07-11 15:18
The launcher not being there makes it sound like something's gone wrong during the install process. There's a couple of things to try...

* Run `dpkg --remove wavebox` and re-install using software center
* Try installing through `dpkg -i /path/to/wavebox.deb`. This might bring up some more info in the console if there are errors
* Failing the two above, if you download the tar version, extract, cd, and try running it with just `./Wavebox` does that work?

**Comment by amig** [comment] 2017-07-11 16:02
I need some spanking :-P
I was trying to install the wrong version (32 instead of 64). Now it's working and the reported issue is solved.
Thanks Thomas

**Comment by Thomas101** [comment] 2017-07-12 08:02
That probably explains why I couldn't reproduce it! :)

Just out of curiosity did the download page suggest the 32-bit version at the top or did it just give you the list of all possible downloads? Just in case I need to update the matching for auto-suggesting platform and arch

**Comment by amig** [comment] 2017-07-12 09:13
The download page suggests the 64 bit version but only for the stable release.
I had to download it from https://github.com/wavebox/waveboxapp/releases and there I choose in a haste the wrong file.

**Comment by Thomas101** [comment] 2017-08-02 11:44
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-08-02 11:44 UTC
Labels: bug, in-beta, os:linux, os:macOS, os:windows
