### ISSUE TITLE
[Bug Report] New System Tray Instance Upon Reload

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#361] opened 2017-08-21 19:37 UTC
3.2.6Beta (I also noticed it, I think as far back as 3.2.3)
KDE Neon (Ubuntu 16.04)

If you press Ctrl+R for reloading Wavebox it will work fine but it seems to also create another entry in the System Tray for Wavebox. If the action is repeated the new entry issue also repeats. I tested until I made 5 entries load in the System Tray at the same time.

![wavebox-bug](https://user-images.githubusercontent.com/1056731/29535108-45a5031a-867e-11e7-9fe7-7e79e6458c5f.png)

**Comment by Thomas101** [comment] 2017-08-23 09:18
I seem to remember there being an upstream issue for this somewhere, but it could be a timing thing during the teardown process. Could you give the following a try...

Open View > Developer Tools and then click the console tab. Paste the following in...

```js
var remote = require('electron').remote
var tray = new remote.Tray(remote.nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEDWlDQ1BJQ0MgUHJvZmlsZQAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9oU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvuuWfvBei5qliWkRQBFpquLRcy4nOHj4g9K5CEh6AXBqFXUR0rXalMAjZPC3e1W99Dwntf2dXd/p+tt0YdFSBxH2Kz5qgLiI8B8KdVy3YBevqRHz/qWh72Yui3MUDEL3q44WPXw3M+fo1pZuQs4tOIBVVTaoiXEI/MxfhGDPsxsNZfoE1q66ro5aJim3XdoLFw72H+n23BaIXzbcOnz5mfPoTvYVz7KzUl5+FRxEuqkp9G/Ajia219thzg25abkRE/BpDc3pqvphHvRFys2weqvp+krbWKIX7nhDbzLOItiM8358pTwdirqpPFnMF2xLc1WvLyOwTAibpbmvHHcvttU57y5+XqNZrLe3lE/Pq8eUj2fXKfOe3pfOjzhJYtB/yll5SDFcSDiH+hRkH25+L+sdxKEAMZahrlSX8ukqMOWy/jXW2m6M9LDBc31B9LFuv6gVKg/0Szi3KAr1kGq1GMjU/aLbnq6/lRxc4XfJ98hTargX++DbMJBSiYMIe9Ck1YAxFkKEAG3xbYaKmDDgYyFK0UGYpfoWYXG+fAPPI6tJnNwb7ClP7IyF+D+bjOtCpkhz6CFrIa/I6sFtNl8auFXGMTP34sNwI/JhkgEtmDz14ySfaRcTIBInmKPE32kxyyE2Tv+thKbEVePDfW/byMM1Kmm0XdObS7oGD/MypMXFPXrCwOtoYjyyn7BV29/MZfsVzpLDdRtuIZnbpXzvlf+ev8MvYr/Gqk4H/kV/G3csdazLuyTMPsbFhzd1UabQbjFvDRmcWJxR3zcfHkVw9GfpbJmeev9F08WW8uDkaslwX6avlWGU6NRKz0g/SHtCy9J30o/ca9zX3Kfc19zn3BXQKRO8ud477hLnAfc1/G9mrzGlrfexZ5GLdn6ZZrrEohI2wVHhZywjbhUWEy8icMCGNCUdiBlq3r+xafL549HQ5jH+an+1y+LlYBifuxAvRN/lVVVOlwlCkdVm9NOL5BE4wkQ2SMlDZU97hX86EilU/lUmkQUztTE6mx1EEPh7OmdqBtAvv8HdWpbrJS6tJj3n0CWdM6busNzRV3S9KTYhqvNiqWmuroiKgYhshMjmhTh9ptWhsF7970j/SbMrsPE1suR5z7DMC+P/Hs+y7ijrQAlhyAgccjbhjPygfeBTjzhNqy28EdkUh8C+DU9+z2v/oyeH791OncxHOs5y2AtTc7nb/f73TWPkD/qwBnjX8BoJ98VVBg/m8AAAFLSURBVFgJtZYLEoMgDESl97+zJWokkn9EplMobnZfxM7Y9m3rHzL2509y5f2yNebxYzuCiGkqG4ovBwBzRVzJPWoMPxlgJYQRvvXj/sGXOqxitYhcsOqv3PMOfAFhhRPGcQQrIbxwkjUAgIpcIJDn0jPFAk83ZTwBwGQSoO8xe+bedcGbA1QhCuEQJQNkIYrhNkAWAvTSEG47lbW9D7ohrr0OxaK+GbDWj4CaBoyo/FgHa2IA4Bg0zISDNg4A6ghERANe18gBYNXCOQcQeRgjGtJAHCBjnNDGABKGd3PBGh/AM7IeOq+209oAngGG43y3TxaOhw7gFLK/ZBFCBsiGY8MFCA5QDS9CPAHehhcgngBoIM3W7c3qSaMDgGwyv2w4Glh1V94J8EV4EKL1txH9hcTqAAOis9LkOILZaGU4eCt+MoAinhnTvwXfP0AhZDicSdEhAAAAAElFTkSuQmCC'))
```
... you should get a lovely red X in your tray. If you then run

```js
tray.destroy()
```
does it disappear or are you still left with it?

**Comment by MichaelTunnell** [comment] 2017-08-23 19:12
the tray icon did not become a red x, it appears that nothing happened but I did receive an error in the console which was:

`Uncaught ReferenceError: require is not defined
    at <anonymous>:1:14
(anonymous) @ VM764:1`

**Comment by Thomas101** [comment] 2017-08-24 13:20
Okay, I've tried tightening up the reload cycle so it jumps down into the render thread and waits, so it should ensure the tray icon is destroyed correctly.

I'm having trouble reproducing the issue on the current beta though. Can you check which version of `libappindicator1` you have installed on your system? Also which method were you using to reload? <kbd>Ctrl</kbd>+<kbd>R</kbd> or `View` > `Reload`?

This was the config I used for testing...
![screen shot 2017-08-24 at 14 15 27](https://user-images.githubusercontent.com/103586/29668115-ed6b3cae-88d6-11e7-97a1-acdbdcafffb0.png)

**Comment by MichaelTunnell** [comment] 2017-09-14 17:18
sorry for the delay in the response.

libappindicator1 = 12.10.1+16.04.20170215

I was using Ctrl+R but I just tried it with View -> Reload which resulted in the same issue.

![neon-info](https://user-images.githubusercontent.com/1056731/30443899-d1c4d41c-9946-11e7-9fa0-559dd27ab8b1.png)

**Comment by Thomas101** [comment] 2017-09-19 13:33
Thanks. I've got the same version of libappindicator1 here and tried updating the kde frameworks to the same as yours but still not seeing it. I'm guessing after you quit Wavebox the duplicated icons all vanish? To be honest I'm a little bit stumped with this one :-/

**Comment by MichaelTunnell** [comment] 2017-09-20 15:36
>  I'm guessing after you quit Wavebox the duplicated icons all vanish? 

Correct.

> To be honest I'm a little bit stumped with this one :-/

Yea, this one seems to be a very odd issue.

-----------

If I reload an account by right clicking an icon and then choosing Reload then it works fine with no duplicate. Only the Ctrl+R and the Menu->View->Reload makes it happen.

**Comment by Thomas101** [comment] 2017-09-21 09:47
The underlying behaviour of the two reloads is very different. The right click > reload just reloads the tab that's associated with it, where as the menu > view > reload reloads the entire window - which includes the logic to handle sync, tray etc etc.

I wonder if it's time we re-map ctrl+r and the menu > view > reload to just reload the tab. Have you been finding the Menu > View > Reload useful at anytime?

**Comment by MichaelTunnell** [comment] 2017-09-21 16:10
> I wonder if it's time we re-map ctrl+r and the menu > view > reload to just reload the tab. Have you been finding the Menu > View > Reload useful at anytime?

Honestly, I rarely want to reload the entire application. Most of the time I just want to reload the account or even the page of the account that I am on. If both options could be made where Ctrl+R is like a normal browser of reloading what you are using and maybe Ctrl+Shift+R could be a reload for the whole app.

What do you think?

**Comment by Thomas101** [comment] 2017-09-25 10:09
I think that makes sense. I'll schedule it in to change those around, something along the lines of what you suggested.

As for the duplicate icon when reloading the entire window - we're at a bit of a loss on that one. It might just fall onto the hard-to-reproduce pile

**Comment by Thomas101** [comment] 2017-10-02 10:19
@MichaelTunnell the latest beta, 3.3.4 has now updated the shortcuts to work on a per-account basis rather reloading the app. If you do want to reload, then Shift+Ctrl+R will do what the old behaviour did.

As regards the duplicate try items, I'm going to keep this open in case we are able to reproduce the issue and get it fixed in the future. Thanks!

**Comment by Thomas101** [comment] 2019-01-23 14:45
I originally left this open to track the duplicate tray icons and as you mentioned reloading the main window is something that happens rarely. Our thinking is that tray icon remains due to a dangling reference, but this is probably upstream in Chromium.

As it's something that rarely happens and has low impact, I'm going to close this off. Thanks!

**Closed by Thomas101** 2019-01-23 14:45 UTC
Labels: os:linux, sporadic/hard to reproduce

**Comment by MichaelTunnell** [comment] 2019-01-23 14:54
Sorry for the lack of my reply, but I can safely say I haven't seen this issue in a while. It used to have multiple times a day every day when I submitted but I don't remember seeing it happen for at least a couple months now so maybe the upgrade of electron fixed that

**Comment by Thomas101** [comment] 2019-01-23 16:27
Awesome, thanks for the update :)

**Comment by NoSync** [comment] 2019-09-23 10:35
Unfortunately this bug still occurs on my system all the time (Manjaro latest, Wavebox 4.11.3, Plasma 5.16.4). Quitting Wavebox fixes it, Ctrl + R creates a new icon.
