### ISSUE TITLE
Can't delete non-main accounts after trial period

### ISSUE THREAD

**Issue by guidezpl** [wavebox/waveboxapp#333] opened 2017-08-01 18:02 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mas OSX Sierra

I cannot delete accounts other than my main account after the trial period ends. In fact I still get notifications for these accounts. Going into settings, I see two buttons, one to upgrade to Pro, the other to "Delete this account". After clicking again to confirm, nothing happens. The account is not deleted

**Comment by Thomas101** [comment] 2017-08-02 11:29
Hi, apologies for this. If you try right clicking the account in the sidebar and picking delete does that work?

**Comment by guidezpl** [comment] 2017-08-02 14:14
Sorry, I erased everything and reinstalled so I don’t know

**Comment by Thomas101** [comment] 2017-08-02 14:17
Okay, I'll close this off for now then as I'm not able to reproduce the issue. Feel free to re-comment or open a new issue if it comes back up. Thanks

**Closed by Thomas101** 2017-08-02 14:17 UTC

**Comment by bigjay517** [comment] 2018-01-13 22:50
I just had this issue.  I was unable to delete my accounts from the settings accounts menu.  I was able to delete them by right clicking and selecting delete from the sidebar.

**Comment by Thomas101** [comment] 2018-01-15 10:46
@bigjay517 did you see any errors?

**Comment by bigjay517** [comment] 2018-01-15 15:37
No errors were displayed. When I confirmed the delete the remove account
button came back. I tried to perform the actions again with the same
result. When I tried to quit wavebox it crashed and Windows had to force it
closed.
