### ISSUE TITLE
Some key bindings in GMail are to physical keys, not respecting non-qwerty layouts

### ISSUE THREAD

**Issue by max-sixty** [wavebox/waveboxapp#964] opened 2019-03-06 03:08 UTC
* Wavebox Version: Version 4.7.3 (dmg)
* Operating System & Version: Mac 10.14.2 (18C54)
* Account type (if applicable): GMail

**Expected & actual behavior**

Use `Cmd+]` on a dvorak keyboard in a bulleted list. The physical key in qwerty is `+`.

Expected: Indent. (This is also the behavior in Chrome)
Actual: Zoom in, consistent with the mapping being to a physical key rather than the selected input source.

Thank you for the wonderful product!

**Comment by Thomas101** [comment] 2019-03-07 14:47
Thanks for reporting! I'm seeing the same here. I'll have a look to see what the root cause of the issue is, however as quick workaround you can disable the zoom in keyboard shortcut, which makes it work as indent on Gmail. To do this,
* Go to `Settings` > `Keyboard Shortcuts`
* Open the `View` section and find Zoom In
* Just delete the shortcut that's there and leave it blank

**Comment by max-sixty** [comment] 2019-03-07 15:03
Great! Thanks for the workaround

**Comment by Thomas101** [comment] 2019-03-07 15:45
I think I've found the root cause. I'll try and get a patch into the next release :)

**Comment by Thomas101** [comment] 2019-03-11 11:04
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2019-03-11 11:04 UTC
Labels: bug, os:macOS, waiting-release

**Comment by max-sixty** [comment] 2019-03-11 13:27
Thanks so much @Thomas101 ! The turnaround is awesome
