### ISSUE TITLE
Notification badge for Slack notifications sometimes doesn't clear

### ISSUE THREAD

**Issue by rfgamaral** [wavebox/waveboxapp#884] opened 2018-12-12 16:54 UTC
* Wavebox Version: 4.5.5
* Operating System & Version: Windows 10
* Account type (if applicable): Slack

**Expected & actual behavior**
Sometimes the notification badge (both in the sidebar and toolbar) remain stuck when all unread content has been read already. The notification badge should be removed as soon as all unread content has been marked as read.

**Steps to reproduce**
I have no idea...

**Is the bug persistent or intermittent?**
It only happens sometimes.

**Comment by Thomas101** [comment] 2018-12-13 09:47
Next time it happens can you try the following.
1. Go to Wavebox Settings > Debug > Task Monitor. At the bottom of the task monitor, your slack channel should be listed, is this all in green?
2. Right click on the account and pick `Resync`, does that clear it, or does it remain there?
3. If it remains there after trying (2) does pressing <kbd>Shift</kbd>+<kbd>Esc</kbd> in slack and then trying `Resync` clear the badge?

**Comment by rfgamaral** [comment] 2018-12-13 14:55
> At the bottom of the task monitor, your slack channel should be listed, is this all in green?

Yes.

> Right click on the account and pick Resync, does that clear it, or does it remain there?

Yes, it clears the badges right away.

**Comment by greggb** [comment] 2018-12-13 15:17
Re-syncing clears this issue up for me as well, but it still occurs fairly often. Haven't figured out a reproducible pattern yet.

**Comment by rfgamaral** [comment] 2018-12-13 15:59
I guess I'm not alone 😁

**Comment by greggb** [comment] 2018-12-13 16:00
@rfgamaral Nope :) I've just lived with it until I saw your issue

**Comment by Thomas101** [comment] 2018-12-14 16:08
Sounds like we're just not listening correctly on one of the events as they come through. If I add some logging tools into a beta release would you be happy to try them?

**Comment by rfgamaral** [comment] 2018-12-14 16:39
It's moderately busy and it usually happens every single day. Is there anyway you could implement an on/off?

**Comment by Thomas101** [comment] 2018-12-17 15:41
Awesome thanks. I've just pushed a beta out (v4.5.6) with some tools to pick this out and hopefully help us get to the bottom of it. To use it...

1. Open up the Wavebox Developer Tools by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>
2. Click the console tab
3. Enter `window.waveboxDebug.tests.debugSlackCount.startLogging()`.

This will start making a note of slack messages. When the app falls out of sync there are two ways to tell it that this has happened. The first one is by typing `window.waveboxDebug.tests.debugSlackCount.writeLog()` into the console. The debug will also try to detect the case where messages have fallen out of sync. If the app is able to detect this, you'll get a popup box similar to this one and you can just press `Write log`. The log will only be up to the last 5 minutes of activity from the account so you'll need to be quick-ish.
![dialog](https://user-images.githubusercontent.com/103586/50095877-5b88cb00-020e-11e9-8911-df03c68dc147.png)


To stop logging at any point, either type `window.waveboxDebug.tests.debugSlackCount.stopLogging()` into the console or restart the app.

When you've written the logs, they'll just be placed on your desktop. There will be two files. `wavebox_<timestamp>_stripped.log` and `wavebox_<timestamp>_full.log`. Because potentially there's sensitive data in here it's best not to share the whole log - hence the stripped version. This cuts strings off after the first two characters aside from a few select fields. Double check there's nothing sensitive in there and either upload it here or send it across to support _at_ wavebox.io.

Keep hold of the full version - there might be some extra info in this that helps, but if it's needed we can do this on a case-by-case basis.

**Comment by Thomas101** [comment] 2018-12-19 08:51
@rfgamaral are you still building a version of the app from source? I think 9f944fe might be a fix for this :)

If you're not building from source, let me know, I'll run a build off our build boxes here, if you want to try

**Comment by Thomas101** [comment] 2018-12-20 10:51
@rfgamaral No worries. I've just pushed it out as part of 4.5.9. Let me know if the count is any better

**Comment by rfgamaral** [comment] 2018-12-20 11:01
@Thomas101 Just updated. Let's see how it goes through the day :)

**Comment by greggb** [comment] 2018-12-20 16:37
@Thomas101 Started running 4.5.9 this morning since the issue was occurring with even greater frequency lately.

I tried use the logging commands above, but there was no `waveBoxDebug` defined on window. I'm watching the console logs and the out of sync marker seems to coincide with 

```modern.vendor.468581084cbf984a4932.min.js:1 Dec-20 11:32:02.905 (T024FNNHU) Notification (message) suppressed because:
The message was a join or leave message```

But I can't honestly be sure as I was not watching the whole time. If it's any help I have almost all notifications turned off accept for badges in the sidebar.

**Comment by Thomas101** [comment] 2018-12-21 09:17
Thanks @greggb. If you right click on the account and pick `Resync` does that correct the count or does it remain incorrect?

While poking around, we found that messages in threads were being incorrectly treated like messages in the channel. This would cause the unread indicator dot to turn on, or in the case of a mention the count to increase. When running a full resync (either manually from the context menu, periodically, or after certain events), this would correct itself and be okay for a while.

The change we did in 4.5.9 was to take note of the unread threads and mimic the behaviour of the official Slack client more closely. When there's a change to a thread the unread indicator turns on and when there's a mention in a thread this is added to your count.

---
> I tried use the logging commands above, but there was no waveBoxDebug defined on window. I'm watching the console logs and the out of sync marker seems to coincide with

From the log, it looks like you opened the console for the Slack tab (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> or `View` > `Developer` > `Developer Tools`), rather than the Wavebox Window (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> or `View` > `Developer` > `Wavebox Developer Tools`), which is why `waveboxDebug` is not available :)

**Comment by greggb** [comment] 2018-12-21 15:33
Thanks Thomas! I did a resync and I'll keep an eye on it today.

>rather than the Wavebox Window

🤦‍♂️

**Comment by greggb** [comment] 2018-12-21 17:15
@Thomas101 caught one!

```
0: {"type":"channel_marked","channel":"C0|9","ts":"1545412233.007100","unread_count":0,"unread_count_display":0,"num_mentions":0,"num_mentions_display":0,"mention_count":0,"mention_count_display":0,"event_ts":"1545412314.003100"}
1: {"type":"member_joined_channel","user":"U0|9","channel":"CB|9","channel_type":"C|1","team":"T0|9","event_ts":"1545412324.001900","ts":"1545412324.001900"}
2: {"user":"U0|9","user_profile":{"avatar_hash":"92|12","image_72":"ht|82","first_name":"Ka|7","real_name":"Ka|17","display_name":"ka|3","team":"T0|9","name":"ka|17","is_restricted":false,"is_ultra_restricted":false},"type":"message","subtype":"ch|12","team":"T0|9","text":"<@|35","channel":"CB|9","event_ts":"1545412324.002000","ts":"1545412324.002000"}
3: {"type":"message","user":"U0|9","text":"Je|62","client_msg_id":"32|36","team":"T0|9","channel":"CB|9","thread_ts":"1545410416.000800","event_ts":"1545412373.002100","ts":"1545412373.002100"}
4: {"type":"message","message":{"type":"me|7","user":"U0|9","text":"Fo|111","client_msg_id":"fc|36","thread_ts":"1545410416.000800","reply_count":3,"replies":[{"user":"U0|9","ts":"1545410455.000900"},{"user":"U0|9","ts":"1545410486.001200"},{"user":"U0|9","ts":"1545412373.002100"}],"unread_count":3,"ts":"1545410416.000800"},"subtype":"me|15","hidden":true,"channel":"CB|9","event_ts":"1545412373.002200","ts":"1545412373.002200"}
5: {"text":"","bot_id":"B0|9","attachments":[{"fallback":"mi|158","id":1,"color":"2e|6","fields":[{"title":"","value":"mi|158","short":false}],"mrkdwn_in":["pr|7","te|4","fi|6"]}],"type":"message","subtype":"bo|11","team":"T0|9","channel":"C6|9","event_ts":"1545412408.022300","ts":"1545412408.022300"}
6: {"type":"member_joined_channel","user":"U7|9","channel":"CB|9","channel_type":"C|1","team":"T0|9","event_ts":"1545412409.002300","ts":"1545412409.002300"}
7: {"user":"U7|9","user_profile":{"avatar_hash":"84|12","image_72":"ht|82","first_name":"Kr|4","real_name":"Kr|12","display_name":"sk|9","team":"T0|9","name":"kr|12","is_restricted":false,"is_ultra_restricted":false},"type":"message","subtype":"ch|12","team":"T0|9","text":"<@|35","channel":"CB|9","event_ts":"1545412409.002400","ts":"1545412409.002400"}
8: {"type":"file_change","file_id":"FE|9","user_id":"U7|9","file":{"id":"FE|9"},"event_ts":"1545412429.067000"}
```

**Comment by rfgamaral** [comment] 2018-12-22 00:36
I'm not sure if this is working better or worse on the latest build, I honestly can't tell. But I found another weird bug that might have been there already (and is related to this issue) or maybe it was introduced with the latest changes.

Open a DM with "Slackbot", type something and press `Return`. Then delete that message. The notification badge will appear. This happens with any message deleted and for each one deleted, the notification badge number increases. Manually resyncing clears the badge.

**Comment by Thomas101** [comment] 2019-01-07 16:32
@greggb thanks, that one triggered incorrectly when a member joined a channel

@rfgamaral thanks, that was because we were treating a deleted & change message the same as a new one

We're hoping to push a release out this week which will include fixes for those two :)

**Comment by greggb** [comment] 2019-01-16 22:17
This seems to be fixed now. Appreciate the help @Thomas101.

**Comment by Thomas101** [comment] 2019-01-18 09:41
Whoops, sorry, think I forgot to post that it went out in 4.5.10 :)

@rfgamaral does it seem better for you too?

**Comment by rfgamaral** [comment] 2019-01-18 14:51
Yes, I think it's much better now, thanks.

Keep up the good work :)

**Comment by Thomas101** [comment] 2019-01-18 15:05
Awesome, thanks for the help :)

**Closed by Thomas101** 2019-01-18 15:05 UTC
Labels: account:slack, follow-up, waiting-release

**Comment by joncchen** [comment] 2019-12-19 19:44
I'm unfortunately still having this issue. But only in my SSO / google sign in workspace, and not any of my other workspaces. Clearing notifications with Shift/Escape doesn't help, and resyncing doesn't undo the notification either. Any ideas?

**Comment by Thomas101** [comment] 2019-12-20 10:41
@joncchen which version of Wavebox are you using?

**Comment by joncchen** [comment] 2019-12-20 17:19
4.11.11 on Mac 10.14.4

Ended up fixing it by finding an inactive channel that still had
notifications/unread. Sorry for the trouble.
