### ISSUE TITLE
Wavebox has a problem and requires the page to reload 

### ISSUE THREAD

**Issue by tonybyng** [wavebox/waveboxapp#816] opened 2018-09-29 11:13 UTC
* Wavebox Version: [e.g. 3.0.0] 4.2.1beta but been happening for the last 6 - 8 weeks ish
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10] Mint 18.3
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...] apt repo
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...] gmail

**Expected & actual behavior**
A couple of times per day usually a screen  replaces the (usually gmail) screen contents, saying that something has gone wrong and I need to reload. There is a reload button on the screen. This is not a screen I get when gmail is running through the browser. It can happen when Im typing an email or sat at the main inbox. Its not linked to starting up or shutting down Wavebox, it often happens middle of the day. I believe I didnt have it during the 3 days that 4.2beta was installed but it happened again this morning after installing 4.2.1beta, within a few seconds of starting Wavebox

Im on a wired network so its not to do with dropping a wireless network connection and I dont use a VPN - its just the PC, wired to a hub, which is wired to a broadband router. I had no problems up until about 8 weeks ago, which sounded very similar to #750 

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug? No. it just happens periodically. Occasionally shortly after starting Wavebox but more often than not,  sometime during the day, randomly. thankfully because gmail saves the email draft as you type, I dont lose anything ive typed, other than maybe half a sentence

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**

**Comment by Thomas101** [comment] 2018-09-29 12:04
Thanks for re-raising :-). Is it just with one Gmail account or multiple? Do you have any extensions installed? I wonder if one of those is intefering with something :-/

**Comment by tonybyng** [comment] 2018-10-01 08:35
@Thomas101  It happened this morning so I took a screen shot. I clicked on a linux notification tab that said I had an email come in and as it flipped over to wavebox, it came up with this. I will keep a mental note whenever it happens to see what im doing.

![wavebox-crash](https://user-images.githubusercontent.com/9347905/46278159-4381a380-c55d-11e8-85dd-ea7e19d4448d.jpg)

**Comment by Thomas101** [comment] 2018-10-01 13:08
Thanks @tonybyng the screenshot is super helpful. I thought it was the yellow Gmail warning that sometimes comes up when the connection is flakey, but obviously not, that's the tab crashing. Electron is really poor at outputting the underlying problem of the tab crash at the moment so there's not a lot of additional info in terms of logging right now.

Try going to settings > advanced and enabling "Isolate Account Processes" to see if that helps. As for the root cause, I wonder if it's the audio stack in Google Music. I've seen some issues reported on this version of Chromium as regards AV & Linux. If changing that setting helps, we can isolate the account individually to try and narrow it down.

Aside from that, I can see you've got LastPass & Markdown Here enabled, have you got any other extensions?

**Comment by tonybyng** [comment] 2018-10-02 07:01
Thanks @Thomas101 I got in this morning to the same crashed page (it died sometime overnight). Ive now activated the Isolate Account Processes option to see if that helps and will revert back accordingly. Ive also just put Google Music to sleep.  I have todoist as well as LastPass and Markdown but ive just removed that as well so ive just introduced 3 variables into the mix ;-) If it fixes the problem over the next 3 days or so, i'd prefer to reactivate things slowly and be narrowing it down to 1 of 3 than it being an unknown - much better odds!

**Comment by Thomas101** [comment] 2018-10-02 09:41
Perfect, thanks! Keep me up to date and we'll see if we can narrow it down :)

**Comment by tonybyng** [comment] 2018-10-09 09:15
@Thomas101 Making those changes has reduced the amount of bombed out tabs but I am still getting them occasionally - and its not just gmail - I just had one in outlook.com. So just to confirm, Ive got the isolation option set, i removed the todoist app and i put the google music app to sleep.  The other day when I had one, I noticed that music wasnt sleeping at the time so thought that might have been the cause but with outlook.com going just it was definitely sleeping. ;-(

**Comment by Thomas101** [comment] 2018-10-10 13:53
Thanks. Looks like it's not that then. Let me see if I can pull any more logging info out from a crash...

**Comment by Thomas101** [comment] 2018-10-12 08:49
@tonybyng I'm trying narrow this down. How much ram and swap do you have on your machine? Can you send me a screenshot of Settings > Debug > Task Monitor after you've been using it a while

**Comment by tonybyng** [comment] 2018-10-12 11:52
@Thomas101 

Hi. machine has 16 gig ram, 16 gig swap. 3 gig ram free, 16 gig swap free. wavebox has been running for a day or two. Just about to apply the next beta update so it will shut down then, so thought i'd do this now!

![image](https://user-images.githubusercontent.com/9347905/46867039-870cc500-ce1b-11e8-8127-6d71c196c537.png)

**Comment by tonybyng** [comment] 2018-10-18 06:41
@Thomas101 Im on 4.3.1beta now and apply all the betas as they come out and suddenly realised this morning that I havent had the tab crash for a few days. Will continue to monitor but have you actively changed anything in the recent releases that might affect things?

**Comment by Thomas101** [comment] 2018-11-05 12:48
The only thing that I can think of, is that we've started limiting the number of concurrent tabs that load at once. By default, there's a soft limit on the number of CPU cores on your machine. This could be a red-herring though

**Comment by mobunti** [comment] 2018-11-05 12:52
@Thomas101 I am still getting the issue although less now than I was, so either I'm working differently or each release gets closer to resolving the problem ;-) If there is anything you think I can do to help, let me know, otherwise I will just put up with it for a bit. I just renewed my licence so I cant be that annoyed with it ;-)

**Comment by mobunti** [comment] 2018-11-05 12:52
Sorry I just realised Im logged in on the wrong account - that was @tonybyng responding... oops

**Comment by Thomas101** [comment] 2018-11-05 13:30
Thanks, there's a big chromium update getting ready to ship, so I'm hoping that will have some positive outcomes on this too :)

**Comment by tonybyng** [comment] 2018-12-05 09:53
Ive not had the problem for a few weeks I think. I got so used to reloading it i then didnt think about it, but thinking back now Ive not had the issue recently so if you are thinking the 4.5 release may have resolved it and I dont recall having any issues then I think we may have got the problem sorted. Top man. Will let you know if it happens again but Im happy at the moment the problem is fixed so if you want to close it then i'm happy

**Comment by Thomas101** [comment] 2018-12-05 09:56
Awesome. Let me know if does come back up. We've added some more logging our end so we should get a better idea of what could be causing it if it does reappear.

**Closed by Thomas101** 2018-12-05 09:56 UTC
Labels: bug, electron-3-0-fix, follow-up, os:linux
