### ISSUE TITLE
Window opener cuts off titlebar on Mac

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#607] opened 2018-03-12 12:49 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.10.4beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Mac OS 10.13.3

3.10.4beta has been cutting off the titlebar for me on newly-opened Wavebox browser windows. The issue appears to be the same as #388.

**Comment by Thomas101** [comment] 2018-03-12 13:38
That's interesting. We changed it in this beta so it would bound it to the available screen space rather than leave an arbitrary gap at the top. I'll re-add the arbitrary space for macOS, hopefully, that should re-fix it.

Out of curiosity do you use more the one monitor?

**Comment by jason0x43** [comment] 2018-03-12 15:40
I do use multiple monitors, yes, and I like to run things Wavebox in full screen mode.

When you're determining the available screen space, is that for the display the app is running on or the target display? In full screen mode there's no menubar, so that might be affecting the apparent available space.

**Comment by jason0x43** [comment] 2018-03-12 15:44
So, it seems like the titlebar is only cut off when the target display has to change Spaces from a full screen app to an open desktop Space to display the new window. That seems like it might support the idea that an available screen space calculation is happening at a bad time (like, when a full screen app is visible, so there's no menubar).

**Comment by jason0x43** [comment] 2018-03-12 15:50
The titlebar isn't cutoff 100% of the time when a Space change is required, though. More 90+%. Maybe it's a race condition. Those are the worst.

**Comment by Thomas101** [comment] 2018-03-13 09:42
Hi, we’ve just released a fix for this in Wavebox 3.10.5. Thanks

**Comment by jason0x43** [comment] 2018-03-14 19:01
Unfortunately, this isn't 100% fixed. The problem _is_ much less frequent now; 90+% of the time everything is fine, but a small but noticeable fraction of the time windows still open with a hidden titlebar.

**Comment by Thomas101** [comment] 2018-03-15 08:47
There must be a case that's falling through the cracks then. Would be good to know...

Some of the popup windows have a toolbar which includes things like back, forwards, current address etc and others don't. Have you noticed if there's any correlation between the two window styles and the faulty behaviour?

When you come up against a case that fails, what happens if you click the link again? Does it fail in the same way? If it does fail in the same way again, it would be great to have some steps to follow. I might be able to reproduce it then.

I know you said you have two monitors, it would be great to know about the layout of those. Can you go to System Preferences and then Displays and then the Arrangement Tab and send me a screenshot...
![screen shot 2018-03-15 at 08 47 33](https://user-images.githubusercontent.com/103586/37452785-83c21998-282d-11e8-9cae-e307d8b1f579.png)

Thanks!

**Comment by jason0x43** [comment] 2018-03-15 13:12
Here's my display layout. I'll collect some data on your other questions and get back to you...

<img width="780" alt="screen shot 2018-03-15 at 09 11 46" src="https://user-images.githubusercontent.com/1042866/37465249-01fbf2c2-2831-11e8-8028-bf2bcbb593bb.png">

**Comment by jason0x43** [comment] 2018-03-15 13:31
I clicked a single Slack link a number of times; here's what I saw:

* Wavebox is running in full screen mode on the small display (my laptop)
* Clicking the link always opened it on the large display (this is good)
* When I clicked a link while the large display was showing a full screen app, the large display would slide over to my desktop Space and the WaveBox window would open. Almost all the time in this case, the new window would open with its titlebar cut off.
* If the large display was already on the desktop Space, the new WaveBox window would sometimes open properly, and sometimes with its titlebar cut off. When I clicked the link repeatedly, sometimes every new window would be in the same state as the first (regarding its titlebar). Sometimes a new window would open with its titlebar visible even though the previous window's titlebar was cut off. From that point on, every new window would open with its titlebar visible.
* If at any point I opened and closed Mission Control, or changed Spaces to and from the desktop Space on the large display, any windows with the titlebar cut off would snap down into the proper position, and any additional windows would always open with the titlebar visible.
* If the large display was on a full screen app, and one or more WaveBox windows were already open on the large display's desktop Space, new WaveBox windows would sometimes still open with the titlebar cut off. Basically, the presence of WaveBox windows that were displaying properly didn't seem to affect whether new ones would open properly _when_ the large display had to change Spaces.

**Comment by jason0x43** [comment] 2018-03-15 15:29
> Some of the popup windows have a toolbar which includes things like back, forwards, current address etc and others don't. Have you noticed if there's any correlation between the two window styles and the faulty behaviour?

I don't think I've seen any WaveBox windows (other than the main one) without the toolbar.

**Comment by Thomas101** [comment] 2018-03-16 09:21
Thanks, that's been immensely helpful! I'm still having a bit of trouble my end reproducing it, but I've got a pretty good idea what the issue is.

I think it's when the app is in fullscreen mode it gets a zero height for the title bar. This in turns means when it's being bound to the usable workspace area it considers the top 20 pixels usable. Then when the title bar re-appears it allows the window to sit under it.

I've put in an arbitrary padding at the top to compensate for this, which I think should fix it.

**Comment by jason0x43** [comment] 2018-03-16 18:58
It would also be nice to have an option that would cause new windows to open in or around the center of the display.

**Comment by Thomas101** [comment] 2018-03-20 09:26
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:26 UTC
Labels: bug, os:macOS, waiting-release
