### ISSUE TITLE
Drive alternative editors

### ISSUE THREAD

**Issue by binduwavell** [wavebox/waveboxapp#297] opened 2017-07-04 03:20 UTC
* Which version of Wavebox are you using? 3.1.12
* Which Operating System are you using? Mac OSX 10.12.4

----

I configured WaveBox to show Google Drive along with my Google Inbox mail. I have some files that use 3rd party editors such as "Javascript Editey". While a Google Doc/Sheet etc will open in a new window (yuck BTW, but saw there was another issue for that.) The 3rd party apps launched from Drive do not open.

I have a pro account...

**Comment by Thomas101** [comment] 2017-07-06 09:01
Hi, thanks for reporting. This sounds like it's because the Google drive apps rely on chrome extensions/chrome apps for this to work. We are looking at adding some support for extensions into Wavebox. I'll double check this though.

Out of curiosity where were the doc & sheet links that failed to open correctly? Within an email or in drive?

**Comment by binduwavell** [comment] 2017-07-06 19:50
@Thomas101, I have not seen native google apps failing. However, I'm also relatively certain that the editors I'm using are using the open-with drive capability which I don't think uses browser extensions/chrome apps...

As I understand it the 3rd party requests a scope from the drive API on your behalf, this then associates certain mime/types with a callback URL for that application. When you attempt to open a 3rd party file format, a new window is opened with the callback URL with the driveId for the file(s) appended.

**Comment by Thomas101** [comment] 2017-07-10 10:50
Ah okay I see. This is probably related to the root cause of https://github.com/wavebox/waveboxapp/issues/187 then. You could try the new experimental window opener. It might work for this, although you might end up in the same scenario. If you want to give it a try...

1. Open Settings
2. Go to the Advanced tab
3. Toggle "Use Experimental Window Opener" so it's enabled and restart Wavebox

**Comment by binduwavell** [comment] 2017-07-14 03:21
The experimental window opener did not help with this situation.

**Comment by Thomas101** [comment] 2018-03-09 15:23
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2018-03-20 09:24
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:24 UTC
Labels: account:google, in-beta, investigate
