### ISSUE TITLE
Missing important function: close button --> hide to tray

### ISSUE THREAD

**Issue by GrigorijST** [wavebox/waveboxapp#1191] opened 2020-01-17 09:10 UTC
* Wavebox Version: 10.0.52-2 stable (Wavebox Pro)
* Operating System & Version: Linux Mint 19.3
* (Linux only) Install method: Debian installer

Upgraded to 10.x version from 4.x and was very disappointed that:
Missing important function: close button --> hide to tray

Now Wavebox all time hangs in minimized state and Plank panel.
It is very uncomfortable! Can you add this function (as it was on the previous version of Wavebox) as soon as possible.

Thanks.

**Comment by Thomas101** [comment] 2020-01-18 08:46
We're working on improving the current behaviour and hoping to push this out shortly.

There's also an option under Settings > UI to completely quit the app when closing the main window. This might be a better behaviour for you in the short term

**Comment by GrigorijST** [comment] 2020-01-18 09:17
> There's also an option under Settings > UI to completely quit the app when closing the main window. This might be a better behaviour for you in the short term

Unfortunately It's not the same. 

We need working app with notifications exactly in tray.
So we would like to get exactly as it was in 4.x version:
* pressing a close button --> hide to tray
* pressing a tray icon --> show app / hide back to tray

Hoping you will improve the current behaviour the shorlest.

Thanks.

**Comment by nicolafarina** [comment] 2020-02-02 13:11
Can't be more agree. Hide to try is an absolutely needed feature.

**Comment by GrigorijST** [comment] 2020-02-02 13:17
No patience to wait (: To use Wavebox now is so inconvenient! 
Can't understand why we haven't got this necessary function yet...

**Comment by nicolafarina** [comment] 2020-02-02 13:21
Well, internal changes seem to be huge so probably some time is needed to have a full functional release. Hope that this guys improve it rapidly. My first try is not enthusiastic too, my window starts always not at full screen, for example.

**Comment by Thomas101** [comment] 2020-02-05 14:40
Hi, we've just added this to the beta version (10.0.64). If you want to give it a try there's some info on how to switch to the beta channel here https://kb.wavebox.io/beta-channel/

All being well, it should be shipping to stable shortly

**Comment by nicolafarina** [comment] 2020-04-02 11:30
I noticed that using "X" window button application is closed to tray, but with right click and "Close window" on Windows taskbar button will exit Wavebox!

**Comment by marcusorjames** [comment] 2022-07-06 10:08
I have had continuous problems with this for a while now. On both ubuntu and pop os, with "hide to tray" set, it will intermittently quit out of wavebox completely instead of minimising, it is very frustrating. I can confirm that this does this on a fresh install of pop os.

**Comment by Thomas101** [comment] 2022-07-07 07:42
@marcusorjames when it does this, is it the first time you've pressed close since launching Wavebox, or have you pressed the close button 1-or-more times since launch (which worked correctly), then at some point you do it and it quits?

When it does quit like this, it would be good to know if you had any other Wavebox windows open (i.e. just another browsing window, Wavebox mini etc...) or if you just had the main Wavebox window open

**Comment by marcusorjames** [comment] 2022-07-07 08:14
It never does it the first time, not that I have noticed anyway. I'm using super-q to quit out, which I imagine is just sending a sigkill. It can survive multiple quits going to tray but then out of the blue it will quit completely. I would say in an hour of usage, it may do this 2 or 3 times. (I have another shortcut to bring wavebox to the forefront, so I am opening and closing quite a lot). 

I never have more than one window open at a time, so I will only be triggering this on the main window.

If there is some logging or anything I can do I would be happy to help to get this fixed :)

Another note is that it never used to do this. I'm not sure when it stopped working (it may be inline with this issue), it was probably around a year ago.

**Comment by marcusorjames** [comment] 2022-07-08 10:13
Ok I think I can reproduce this consistently now. Basically I have to click or interact with wavebox to ensure it quits to tray. If I open it without clicking on it and then press super-q then it quits completely.

Worth noting that clicking the x works fine as you then have focus on the window.

So to reproduce in pop os:
1. Open wavebox using the "super" key launcher
2. press "super-q" to quit -- it will quit to tray
3. Open wavebox again using the "super" key launcher
4. press "super-q to quit -- it will quit out completely!

Interesting to note that pop os's focus border is square before you click on it, afterwards when you click on it the border hugs the window properly with the border radius.

This exact same behaviour can be reproduced in  happens on ubuntu 18.04

I tried doing a screen recording but when I open wavebox up the second time (when it doesn't have focus) the screen recorder doesn't pick up the window until you click on it, which is probably related.

**Comment by Thomas101** [comment] 2022-07-08 11:21
I'm just trying here on Ubuntu 20.04 and super-q doesn't do anything. Have you set this somehow? It could be my local configuration has it unset :-/.

I'll try with a fresh install of 18.04, virtualization normally does funky stuff with modifier keys, so I'll need to grab a spare machine and do it on that 👍

**Comment by marcusorjames** [comment] 2022-07-08 11:29
Ok so I think ubuntu's quit shortcut might be Ctrl+q, Pop's is Super+q. I
may have remapped my ubuntu installation because the inconsistency annoyed
me...in any case it is whatever triggers a kill command.

**Comment by marcusorjames** [comment] 2022-07-08 12:39
Amazing, thank you for the excellent response to this, been driving me nuts!

**Comment by Thomas101** [comment] 2022-07-12 08:16
👍 This is now live on our beta channel (https://wavebox.io/beta). It should be heading out to stable next week :). Thanks again!

**Closed by Thomas101** 2022-07-12 08:16 UTC
