### ISSUE TITLE
Change tray minimize behaviour on Windows

### ISSUE THREAD

**Issue by orestis1234** [wavebox/waveboxapp#524] opened 2017-12-21 23:15 UTC
Wavebox 3.7.0

Windows 10

Just set up my accounts with wavebox(messenger and whatsapp). If the application is minimized I get a red dot in the icon of the application in the taskbar but the icon tray does not change. The same happens when the application is closed(well... running in the background but without an open window). Any ideas how to fix it?

**Comment by nmat** [comment] 2017-12-22 07:43
Hello @orestis1234, some various accounts does not as of yet support unread count handling in wavebox from what I understand. Instead the red dot will appear if the service has a unread message to indicate there is something unread.

For example you can look at the account setting and see that it mentions unread as a red dot but not that the unread count will happen for that specific service.

**Comment by Thomas101** [comment] 2017-12-22 09:02
@nmat is right, they only show an unread dot indicator when a notification is presented at the moment. Additionally, if these accounts are set to sleep, then you won't receive notifications, but you can turn this feature off for each account. [More info](https://wavebox.io/kb/sleep-accounts).

Also the tray icon will always show an unread count before unread activity. So, if for example you have 6 unread gmail messages the count will be 6. If you receive a WhatsApp message with this 6 you wont see any status change in the icon as it will still be showing the 6 count

**Comment by orestis1234** [comment] 2017-12-22 14:50
So I e-mailed the wavebox team. They said the unread counter does not work for messenger and whatsapp. I guess the best option is to have the application minimized since even though I get a pop-up notification about my new messages even though I dont click on it it disappears and it is not shown in the action center. 

I guess an easy and good solution, except including these apps in the unread counter of course, would be to add an option that closing the window will actually minimize it.

**Comment by nmat** [comment] 2017-12-23 09:33
@orestis1234 You can set the minimize option in wavebox in the settings.

**Comment by orestis1234** [comment] 2017-12-23 10:29
Only option I could find was "hide the main window to tray when minimize" what I meant it: when I click X instead of the window going to tray to be minized. I know I should just minimize it using the usual way, it's just that I am used to Alt + F4 for my messaging apps.

**Comment by nmat** [comment] 2017-12-30 16:05
Hello again,

Yes you are right here. Close or X is considered as a close window function in general instead of minimize to tray/taskbar. Guess I always use the minimize or click the icon in taskbar to lower the application so it does not close all the time.

@Thomas101 should there be a "On close minimize to taskbar" instead of it closing the app or minimize to tray?

**Comment by Thomas101** [comment] 2018-01-02 11:25
I'm not 100% sure I follow what's being asked for here. When you try to quit the app via the X button, Wavebox will try to hide the window first. It will keep running in the tray. To fully quit you can then right click on the tray icon and hit Quit.

Is the behaviour that you're looking for, when pressing X, minimize the app to the taskbar?

**Comment by nmat** [comment] 2018-01-26 08:50
@Thomas101 that is right. An option on that on X it would be treated as "Minimize to tray" and not close the application or minimize it to the taskbar but minimize it to tray icon.

**Comment by nmat** [comment] 2018-01-26 09:00
For example. If you test using slack on windows 10.

And you hit the X. The application still stays in tray instead of closing completely.

![image](https://user-images.githubusercontent.com/383031/35432035-15de87fa-027f-11e8-84bc-01af9f8e57a4.png)

Suggestion would be to have:
Tray Icon (on/off) - Else greyed out - On by default
Show unread count - On by default
Hide main window to tray on close - (this is for above mentioned problem) - Off by default
Hide main window to taskbar on close - (sends the application to taskbar) - On by default
Hide main window to tray on minimize - (same since its 2 different functions) - On by default
Quit application on close - (closes the window/exits the application) - Off by default

Something like that? Does it make sense?

**Comment by Thomas101** [comment] 2018-03-20 09:22
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:22 UTC
Labels: investigate, os:windows, waiting-release

**Comment by sevenmay** [comment] 2018-03-22 09:34
Why did you remove the option to minimize on close?
It's normal for apps that minimize to tray (ex: Spotify, 1Password, ...).
Now I mistakenly close it all the time.

**Comment by Thomas101** [comment] 2018-03-22 10:19
@sevenmay which os are you using? I'm guessing windows/macOS as you mentioned 1Password

#### Windows
The behaviour shouldn't result in the app quitting completely unless the tray icon is disabled. When you press close it should disappear from the taskbar, but remain running in the tray in the bottom right.
* **Spotify (fresh install)** Press close, the app quits completely
* **Spotify**:
  * Settings > Advanced Settings > Enable `Close button should minimize the Spotify window to the tray`
  * Press close, the main window disappears from the taskbar, but the tray icon remains running
* **Wavebox**
  * Press close, the main window disappears from the taskbar, but the tray icon remains running
* **Wavebox (pinned to tray)**
  * Press close, the main window disappears minimizes to the taskbar

#### macOS
The app shouldn't quit completely unless <kbd>Cmd</kbd>+<kbd>Q</kbd> or Menu > Quit is used. When you press close it should remain running in the tray and dock.
* **Spotify** Press close, the app remains running in the dock
* **Wavebox** Press close, the app remains running in the dock

**Comment by sevenmay** [comment] 2018-03-22 10:48
Version 3.12.0 on Windows 10.

![wb1](https://user-images.githubusercontent.com/1004551/37765124-b81efe04-2dc3-11e8-9c3e-0e434c3babac.jpg)

With this configuration the app minimize on close but remains highlighted in the taskbar, I don't want this if there is the tray icon.

![wb2](https://user-images.githubusercontent.com/1004551/37765364-43975170-2dc4-11e8-8748-29a5da711680.jpg)

With this configuration if you minimize the taskbar is correctly not highlighted.
But if you use the window close button the app shut down and the tray icon disappear.

The behaviour of the older version was perfect.

I get that this is a matter of preference so no big deal, I only want to know if this is the intended behaviour.

Thanks.
