### ISSUE TITLE
3.14.2 segfault Linux

### ISSUE THREAD

**Issue by roccolord** [wavebox/waveboxapp#651] opened 2018-04-18 08:38 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.14.2
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04.

Open wavebox, open a new waveboxwindow or if menu present, press file in menu, move cursor over first entry, segfault.

**Comment by Thomas101** [comment] 2018-04-18 09:10
Hi, thanks for reporting. So we can reproduce here it would be good to have some more info...
* How did you install Wavebox (Ubuntu store, deb, tar, apt-repo)
* Are you using 32-bit or 64-bit Ubuntu?
* Does it happen everytime or intermittently?
* If you right click in any page and pick "Open page with Wavebox" does that cause the crash?
* Which accounts do you have added (e.g. 2 Gmail, 1 Slack, etc...)
* Do you have any extensions installed and if so which ones?

**Comment by roccolord** [comment] 2018-04-18 10:14
Hmm did install a screen recorder to capture the problem and now I can't reproduce any longer. So sorry for the confusion. It did really crash before though :)

[ 1608.253310] Wavebox[15911]: segfault at c0 ip 00000000027c2ba4 sp 00007ffdf2944e68 error 4 in Wavebox[400000+466f000]
[ 1638.773238] Wavebox[18713]: segfault at c0 ip 00000000027c2ba4 sp 00007ffec91d2908 error 4 in Wavebox[400000+466f000]
[ 1791.261740] Wavebox[19698]: segfault at 18 ip 00000000026b45e9 sp 00007ffd6548d9d0 error 4 in Wavebox[400000+466f000]
[ 2065.025252] Wavebox[20231]: segfault at fffffcefc7dbac11 ip 00000000026b45e9 sp 00007ffe7d5a0510 error 5 in Wavebox[400000+466f000]

**Comment by Thomas101** [comment] 2018-04-18 10:18
Okay, lets hope it was just a glitch!

Would be handy to know the install method and arch of the install in case any more of these come up. The snap installs from the Ubuntu store can sometimes have separate issues from other ones because of the environment they run in

Are you happy for me to close this off?

**Comment by roccolord** [comment] 2018-04-19 15:32
I'm on Ubuntu 16.04, installed via apt-repo.

Yes close please!

**Closed** 2018-04-23 10:55 UTC

**Comment by srix55** [comment] 2018-08-22 01:07
Same problem. I'm on Ubuntu 18.04. It worked fine.. but since half an hour it consistently crashes with a segmentation fault (core dump) whenever I go to File -> move cursor down the file menu. I installed via apt get. 64 bit ubuntu. I am using gitter, trello, gmail, youtube, evernote, reddit & pinterest. Plz reopen the issue... it's making wavebox unusable. And I tried with gpu, isolate & all the other advanced toggles... same issue.

**Comment by Thomas101** [comment] 2018-08-22 07:43
@srix55 which version of Wavebox are you using and which install method did you use? This is probably a separate issue so might be best to open a new issue with additional information to cut down on noise

**Comment by srix55** [comment] 2018-08-22 07:46
@Thomas101 I am using wavebox 3.14.6 that comes with ubuntu 18.04. I installed from the official ubuntu package repository.

**Comment by Thomas101** [comment] 2018-08-22 08:01
I've given this a try here and not seeing the same. From the terminal can you run `snap --version` and see what it outputs?

**Comment by srix55** [comment] 2018-08-22 08:03
snap --version
snap    2.34.3
snapd   2.34.3
series  16
ubuntu  18.04
kernel  4.15.0-32-generic

**Comment by Thomas101** [comment] 2018-08-22 08:37
@srix55 I've re-opened this at #765

**Comment by srix55** [comment] 2018-08-22 08:38
@Thomas101 I found out what's causing the crash. I use the website - http://e.ggtimer.com/27minutes for a countdown timer (from within wavebox). Whenever the timer is running, I access the file -> cursor over menu, wavebox crashes.
