### ISSUE TITLE
Badges for Google inbox not working

### ISSUE THREAD

**Issue by roccolord** [wavebox/waveboxapp#576] opened 2018-02-13 14:55 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.10

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.13.3, Ubuntu 16.04

No badges are show in Inbox. Default settings in Unread & Sync.
Show unread count in sidebar or toobar,active
Show unread count in Menu Bar & App Badege, active.

**Comment by Thomas101** [comment] 2018-02-13 15:03
Hi, which unread mode do you have selected under your account settings? Have you tried the steps in this [kb article](https://wavebox.io/kb/google-unread-counts)?

**Comment by roccolord** [comment] 2018-02-15 07:45
I have Unread Unbundled Messages, in 3 different Inbox accounts.

**Comment by Thomas101** [comment] 2018-02-15 09:12
Okay thanks. There's a few things worth trying...

1. If you try pasting the following into the Google Inbox search bar do you get any messages? `label:inbox label:unread -has:userlabels -category:promotions -category:forums -category:social`
2. Does re-adding/adding one of the accounts a second time bring up any unread counts for that account
3. If you restart Wavebox, then go to `View > Developer > Wavebox Developer Tools` you should get a debug window appear. Click on the console tab. Have any errors or warnings appeared there?

**Comment by roccolord** [comment] 2018-02-15 14:44
1. Yes for 2 of 3 accounts.
2. Yes the number of messages found in search 1, is displayed as a badge when added a second time.
3. one 404 on a drive api https://clients6.google.com/discovery/v1/apis/drive/v2internal/rest
401 on https://clients6.google.com/voice/v1/users/@me/account?checkHangoutsCallingPermission

**Comment by Thomas101** [comment] 2018-02-19 14:53
After re-adding the accounts does the count now work correctly across all 3?

**Comment by roccolord** [comment] 2018-02-20 09:14
no.

**Comment by Thomas101** [comment] 2018-02-20 14:03
Above you said that after adding a second time, the number of messages is displayed in the badge. How many of the accounts are now not working? Is it all three or just one etc?

For the ones that aren't working, is it happening on both your Ubuntu install and macOS install or just one? Are the Google Accounts @gmail.com or @mycompany.com addresses?

**Comment by roccolord** [comment] 2018-02-20 15:01
Sorry for being unclear. Adding an account a second time gives badges correctly, on that newly added account, only. Not the old that was added way back, they are still borked. I have since deleted the newly added account. 

Of the 3 accounts I have 2 are @mybothcomanies.com and 1 @gmail.com. It's happening both on OSX and Ubuntu on all of the accounts. All using Inbox.

**Comment by Thomas101** [comment] 2018-02-20 16:15
Thanks for the extra info, are you on the beta channel by any chance? You can find this out by clicking on the settings cog (bottom left) and there's a version in the bottom right of that screen. Is it 3.10.3beta?

**Comment by roccolord** [comment] 2018-02-20 17:05
No I'm on stable.

**Comment by roccolord** [comment] 2018-02-20 17:06
I can change to other branches if needed for testing purposes.

**Comment by Thomas101** [comment] 2018-02-21 12:58
No it's okay, I was wondering if this was related to another issue that's currently on the beta channel. 

I think I might know what the root cause of this is. It would be good to confirm though. Could you try the following...

* Press <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>J</kbd> on your macOS install
* Click the network tab
* Right click on your Google Account and pick "Resync"

You should see a bunch of new logs come out and I'm guessing one of them in your case has a 404 status?

![screen shot 2018-02-21 at 12 57 31](https://user-images.githubusercontent.com/103586/36481162-e46e1996-1706-11e8-9de2-07e674f6a7c2.png)

**Comment by roccolord** [comment] 2018-02-21 14:38
I'm on Ubuntu at the moment but doing the same thing, the strange thing is that nothing is added when doing a "Resync".

**Comment by Thomas101** [comment] 2018-02-21 14:42
In the console tab do you see the `Started in n | n` and `[SYNCS][WebSocket] Socket opened` logs?

**Comment by roccolord** [comment] 2018-02-21 15:00
Ohh sorry missed that there is a "Wavebox developer tools".  In that one I get the started and Websockets and also in network a 404 to:
https://www.googleapis.com/gmail/v1/users/me/history?startHistoryId=3094460

**Comment by roccolord** [comment] 2018-02-22 09:12
![screenshot_20180222_101119](https://user-images.githubusercontent.com/164939/36529484-badd531e-17b8-11e8-9c4b-41f4f3419629.png)
![screenshot_20180222_101143](https://user-images.githubusercontent.com/164939/36529500-c8f7c056-17b8-11e8-91e3-a6dd17be6b56.png)
![screenshot_20180222_101206](https://user-images.githubusercontent.com/164939/36529518-d6967824-17b8-11e8-873e-d79c01d5eb5c.png)

Whoho! Did option 2.

**Comment by Thomas101** [comment] 2018-02-22 09:31
Probably the best one if you're comfortable editing those :). I'll keep you up to date as and when the fix goes out into beta & stable

**Comment by roccolord** [comment] 2018-02-22 09:44
OK, cheers! Thanks for you help on this issue, very good!

Vim is my friend:
:%s/historyId/xhistoryId/gc
So option 2 was a nobrainer for me :+1:

**Comment by Thomas101** [comment] 2018-02-22 09:53
+1 vim :)

**Comment by Thomas101** [comment] 2018-03-09 15:21
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2018-03-20 09:25
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:25 UTC
Labels: account:google, bug, in-beta
