### ISSUE TITLE
Play Music service plays a notification sound whenever a new track starts playing

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#487] opened 2017-11-27 10:11 UTC
* Which version of Wavebox are you using? [e.g. 3.6.1-beta]

* Which Operating System are you using? [Mac OSX 10.12.6]

I noticed that Play Music is supported. Great! However Wavebox sends notifications with each track change. I like the bubble notification but the bell sound that comes with it is a serious joykiller, it totally ruins the mood of the music. 

Please add an option to silent it.

**Comment by Tahini-123** [comment] 2017-11-27 10:14
To be clearer, I need to preserve the notification sounds on everything else (mail, etc).  I just need them to be disabled on Play Music.

**Comment by Thomas101** [comment] 2017-11-27 11:49
I can imagine this would get old quick. I'll put a fix in for it!

**Comment by Thomas101** [comment] 2017-11-30 10:53
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment] 2017-12-09 09:02
Hello,

I have done some testing for this on windows 10 and macOS today. See result below:

---

**windows 10: 1709 (OS Build 16299.98)**

wavebox: 3.6.3beta

_Google Play:_
Desktop notification - turned off by default - Result: No desktop notification on first run

Turning off the notification does work also without having to quit wavebox and start it again (however see below for more information on what needs to be done)

Issue (when prompted it will be enabled on next launch [relaunch]):
Right click reload/refresh does not refresh google play

Had to quit wavebox and then start it again for the change to kick in.

---

**macOS 10.13.2 High Sierra:**

wavebox: 3.6.3beta

Default: no notification

Turning on notification and using relaunch from the settings window - did nothing

Had to quit wavebox and then start it again for the change to kick in

---
**Summary:**
Same effect as on windows 10 when right clicking the index service it just loads while playing in background but never finishes the reload. 

The main effect of not having the notifications on by default is working as intended. Not had time to test on linux yet though but I can imagine the same effect of reloading the indexed service does the same there.

**Comment by Thomas101** [comment] 2017-12-11 12:14
Thanks for the feedback on that one. Looks like it was only when audio was playing

**Comment by nmat** [comment] 2017-12-11 18:05
On windows 10 I can see that there is a window showing to reload the site. (I can't however establish if notifications get turned off or on, since the build now does not load a notification at all from the test button)

This is the window I see:

![image](https://user-images.githubusercontent.com/383031/33846207-30ad41c2-dea6-11e7-9459-e5be1afe77bb.png)

not yet tested on macOS but will do soon enough.

**Comment by nmat** [comment] 2017-12-11 18:21
macOS test

Does work with and without notification.

Telling client to not show notification will give the electron window of reloading the site and after the reload the setting is applied correctly. No need to restart the app with quit.

Windows 10 on the other hand just does not give me options to do any notifications in GIT version now. Think there might be something else broken there.

**Comment by Thomas101** [comment] 2017-12-12 10:29
Thanks. Where are you trying to enable/disable the notifications? I was looking in Google Music then under the settings there.

**Comment by nmat** [comment] 2017-12-14 21:47
I think this is something wrong when I install the GIT repo version. I try to see if I can send notification using the button in the application:

![image](https://user-images.githubusercontent.com/383031/34015914-4b4b269e-e120-11e7-8699-cdfe136c8517.png)

However I also get a electron build error:

PS C:\git\waveboxapp> npm run rebuild:electron

> wavebox@3.6.5 rebuild:electron C:\git\waveboxapp
> node scripts/rebuildElectron.js

rebuild: C:\git\waveboxapp\src\app
Error: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
..\NodeRtUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\git\waveboxapp\src\app\node_modules\@nodert-win10\windows.applicationmodel\build\binding.vcxproj]
..\_nodert_generated.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\git\waveboxapp\src\app\node_modules\@nodert-win10\windows.applicationmodel\build\binding.vcxproj]
..\CollectionsConverterUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\git\waveboxapp\src\app\node_modules\@nodert-win10\windows.applicationmodel\build\binding.vcxproj]
..\OpaqueWrapper.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\git\waveboxapp\src\app\node_modules\@nodert-win10\windows.applicationmodel\build\binding.vcxproj]
  win_delay_load_hook.cc
C:\git\waveboxapp\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\git\waveboxapp\src\app\node_modules\@nodert-win10\windows.applicationmodel\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\git\waveboxapp\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\git\\waveboxapp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\git\waveboxapp\src\app\node_modules\@nodert-win10\windows.applicationmodel
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\git\waveboxapp\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\git\waveboxapp\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (C:\git\waveboxapp\node_modules\rxjs\Subscriber.js:185:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! wavebox@3.6.5 rebuild:electron: `node scripts/rebuildElectron.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the wavebox@3.6.5 rebuild:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

So do not think its related to this specific issue. IMO you can most likely close the issue. :)

**Comment by Thomas101** [comment] 2017-12-18 11:23
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-12-18 11:23 UTC
Labels: account:google, bug, in-beta, waiting-release
