### ISSUE TITLE
Feature request: Stylish (https://userstyles.org/) support

### ISSUE THREAD

**Issue by pioneer** [wavebox/waveboxapp#378] opened 2017-09-05 08:16 UTC
I'm constantly updating custom JS and CSS for my GMail theme taken from Userstyles when the theme is updated there. It'd be great to have those updates done automatically, just by specifying an URL to a theme or so.

**Comment by pioneer** [comment] 2017-11-17 19:47
Also, by some reason, that CSS taken from Userstyles, sometimes doesn't work properly.

**Comment by nmat** [comment] 2018-01-14 08:20
If possible can you test this with using the latest beta from 3.7.3beta where there are quite some changes on how the CSS is handled in wavebox?

If it does not work as intended then can you give example of a style that can be tested?

**Comment by pioneer** [comment] 2018-01-15 14:24
Works perfectly with my current style copied and pasted from Stylish, thanks a lot!

**Comment by nmat** [comment] 2018-01-15 19:27
If you feel that the issue can be closed or that it is fixed now you can always close it then reopen if there would be any issue.

Thank you for testing :)

**Comment by gordallott** [comment] 2018-01-31 16:16
using 3.10.0 basically no slack userstyle theme i load in works correctly, i have to remove the userstyle @mozilla shim to get them to do anything and then they don't work correctly after that https://userstyles.org/styles/117475/slack-night-mode-black as an example 

i'd still heavily prefer being able to load in a userstyles extension that just manages this stuff for me, or just integrate with userstyles in wavebox

**Comment by Thomas101** [comment] 2019-01-23 14:49
I'm going to close this as the original issue was solved using the Custom CSS setting. In addition to this extension support is ongoing and be tracked in #138.

Thanks!

**Closed by Thomas101** 2019-01-23 14:49 UTC
