### ISSUE TITLE
Microsoft Teams - no Ubuntu notifications

### ISSUE THREAD

**Issue by rajalokan** [wavebox/waveboxapp#529] opened 2018-01-05 01:25 UTC
* Which version of Wavebox are you using?  **3.7.2beta**

* Which Operating System are you using? **Ubuntu 16.04**

Hi All,

In Microsoft teams, I can't see notifications within ubuntu notifications. I can hear notification sound but no notification flashing in top right corner. How to enable desktop notification?

**Comment by nmat** [comment] 2018-01-05 08:23
@rajalokan the teams notifications does not show yet since the notifications are not fully implemented for those specific services.

I believe that the wavebox team is working on notifications for example for teams etc to be easier handled. There are some issues regarding notifications for the new services in issues listing here on github where you can find more information about it.

In short, wavebox needs to be able to be allowed to send notifications to the desktop and also there needs to be a CSS/Javascript to handle the notifcations to desktop. You can add your own javascript/CSS to send notifications to desktop until more work has been done on notifications in the service settings.

What the plan for notifications is, I will have to let the wavebox team inform you about. :)

**Comment by Thomas101** [comment] 2018-01-08 12:28
We're going to be adding teams as an integrated account in the future which will include notification and badge support. There's more info on the difference between the two account types [here](https://wavebox.io/kb/account-types).

Closing this off as it's a duplicate of #528

**Closed by Thomas101** 2018-01-08 12:28 UTC
