### ISSUE TITLE
Not possible to zoom in/out in connected Gapps

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#87] opened 2017-04-18 07:18 UTC
* Which version of Wavebox are you using? 3.1.5

* Which Operating System are you using? Ubuntu 17.04

Unless I am mistaken, the zoom +/- function is available only for the mailbox but not for the connected Google Apps (e.g Drive, etc). 
So for example if I open a Google Spreadsheet in Wavebox I cannot zoom out (very useful if you have big spreadsheets and need to check values quickly), because the only zooming function available affects the main window (mailbox) and not the pop-up window containing the spreadsheet. This is also a bit counter-intuitive, since a user would expect that the menu of a window affects that window and not another one :)

**Comment by Thomas101** [comment] 2017-04-25 08:10
Hi, thanks for reporting! I'm seeing this too, we'll get it added in!

**Comment by Thomas101** [comment] 2017-05-04 12:14
Hi, I've just pushed 3.1.6 out which fixes this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by Tahini-123** [comment] 2017-05-05 21:48
Thanks! My trial period is over but I'll buy a license for Pro version on Monday, I will check it then!

**Comment by Tahini-123** [comment] 2017-05-19 08:26
It seems like it's working! Thx for fixing

**Comment by aurimus** [comment] 2017-06-16 12:17
@Thomas101 what do you have to press to zoom in? On my Ubuntu laptop the conventional Ctrl + / - doesn't work (like it used to in Wmail)

**Comment by Thomas101** [comment] 2017-06-19 10:05
@aurimus those should work. If you try going to the view menu does zoom in & zoom out work? Which version of Wavebox are you using and which version of Ubuntu?

**Comment by aurimus** [comment] 2017-06-19 18:38
17.04, 3.18. Doesn't work, Ctrl+Shift + works increasing text size (Gmail shortcut) the decrease doesn't work though..

**Comment by Thomas101** [comment] 2017-06-21 11:28
@aurimus does just <kbd>Ctrl</kbd>+<kbd>-</kbd> work in decreasing it? I think this maybe an issue with picking up the keyboard shortcut correctly.

**Comment by aurimus** [comment] 2017-06-22 08:33
@Thomas101 Your guess is exact. Ctrl + - works correctly! .. Downside is I AM STUCK with everything small now that I tested it.. duh! hope you find the cure pretty soon.. good luck

**Comment by jmboy369** [comment] 2017-07-09 03:16
I'm having the same problem- the keyboard commands work, except for zoom in and out- it there a fix?

**Comment by Thomas101** [comment] 2017-07-10 11:01
@jmboy369 which operating system are you using? Is this with the main mailboxes window or with a content window (e.g. a google drive document)

**Comment by jmboy369** [comment] 2017-07-10 13:53
Windows 10- problem with the main mailboxes window

**Comment by Thomas101** [comment] 2017-07-11 08:07
@jmboy369 which keyboard shortcut are  you using? Have you tried <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>+</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>-</kbd>? 

Alternatively if you go to settings and enable `Show titlebar` and use the `View` > `Zoom in` menu does that work?

**Comment by jmboy369** [comment] 2017-07-11 15:50
it works with the titlebar, view, zoom in.  Thanks!!

**Comment by Thomas101** [comment] 2017-07-17 12:02
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2017-08-02 11:42
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-08-02 11:42 UTC
Labels: bug, in-beta, os:linux, os:windows

**Comment by BOBJohnson** [comment] 2019-02-12 17:43
I know this is an old issue, but I ran across trying to figure out how to zoom in. I'm on a 4K monitor, and I like to increase the zoom on text heavy content (IE, e-mails, and many webpages) - without having to set my Windows DPI > 100% (there's a reason unrelated to all this as to why I need to keep DPI at 100%).

Anyway, most browsers support Ctrl + Mouse Wheel to zoom in and out as well. Any chance you can bring that functionality in? I've already corrected my zoom via the keyboard shortcut mentioned here, but I thought there was no zoom capability because the Ctrl + Mouse Wheel didn't work as expected. Just a minor usability suggestion.

**Comment by Thomas101** [comment] 2019-02-13 11:14
@BOBJohnson which operating system are you using? You're right, we don't support Ctrl+Mouse zoom at the moment. Would you be able to open up a new issue, with some info about which OS you're using and version and we can go from there

**Comment by Beltrando** [comment] 2019-10-15 16:08
Well, same problem today for me with 4.11.4 on a windows server 2012.
I can zoom in with Ctrl - shift - +, but I can't zoom out. Never.
I use a french keyboard.

**Comment by Thomas101** [comment] 2019-10-16 07:44
@Beltrando does <kbd>Ctrl</kbd>+<kbd>0</kbd> reset the zoom level correctly?

You might also be able to access the controls through the window menus if you're happy to enable them. To do this, go to `Settings` > `User Interface` > `Toolbar` and enable `Show titlebar Menu`. From here you should be able to use `View` > `Zoom Out`.

**Comment by Beltrando** [comment] 2019-10-16 11:05
Thank you! enable Show titlebar Menu solve the problem.

But I can confirm that Ctrl + - is not working for zoom out. 

But Ctrl + 0 is working

strange, but it's not a problem anymore
