### ISSUE TITLE
Wavebox will not launch on macOS High Sierra

### ISSUE THREAD

**Issue by signe** [wavebox/waveboxapp#295] opened 2017-06-30 16:54 UTC
* Which version of Wavebox are you using? 3.1.12

* Which Operating System are you using? macOS 10.13 Beta (17A291m)

App simply doesn't launch.  It appears in the dock, but immediately hangs and has to be force quit.  Attaching the Wavebox callstack.

[wavebox_callstack.txt](https://github.com/wavebox/waveboxapp/files/1115951/wavebox_callstack.txt)

**Comment by Thomas101** [comment] 2017-07-03 10:30
Hi,

Thanks for the report & call stack. We've just setup a fresh install with 17A291m and it seems to launch okay. Could you try moving your data out from Application Support (more info on [data location](https://wavebox.io/kb/data-locations)) re-downloading Wavebox and re-launching to see if it launched correctly on your install?

**Comment by hlidotbe** [comment] 2017-07-03 10:43
Hi,

I have the same issue and removed everything in ~/Library related to wavebox. No dice.

**Comment by Thomas101** [comment] 2017-07-03 11:07
Which version did you update from? Was it from beta 1 or from Sierra?

**Comment by hlidotbe** [comment] 2017-07-03 11:29
sierra, I waited for the first public beta to be semi-safe. Not enough it seems 😄

**Comment by Thomas101** [comment] 2017-07-03 11:46
Really odd that it would work for us and not for you all though.

When you launch Wavebox, is the Window entirely white, or does it have the black bar with the loading spinner down the side? Are you able to go to `View` > `Developer Tools` from the top menubar or is it completely dead? (If you can, click on the console tab, see if there's any runtime errors in there!)

**Comment by hlidotbe** [comment] 2017-07-03 13:41
No window whatsoever. The icon appear in the dock, it beachball a few seconds then nothing. I can't cmd-tab to it and have to force quit it.

**Comment by hlidotbe** [comment] 2017-07-03 13:45
I tried again with the system console open. This message might be relevant:

```
!!! BUG: The current event queue and the main event queue are not the same. Events will not be handled correctly. This is probably because _TSGetMainThread was called for the first time off the main thread.
```

**Comment by Thomas101** [comment] 2017-07-03 14:51
I think we have the wrong version our end. Just trying to switch across now!

**Comment by signe** [comment] 2017-07-05 17:54
I was initially seeing the same message as @hlidotbe if I launched Wavebox from a terminal.

I did an over-the-top reinstall of High Sierra and I've been able to launch successfully since then.  It feels like they did a silent re-deploy of an updated build, but my build number hasn't changed.

**Comment by Thomas101** [comment] 2017-07-06 09:03
I wonder if this is why we're not able to reproduce it here. I've had another dig around but that seems to be the only build identifier I can find.

@hlidotbe out of curiosity are there any updates in the app store for macOS?

**Comment by hlidotbe** [comment] 2017-07-06 10:49
Nope, and I'm pretty sure Apple didn't do a silent update of the same build unless there was a massive security/integrity bug. There may be difference between a clean install and an upgrade (I did an upgrade and unfortunately won't be able to do a clean install for some times).

**Comment by milagrofrost** [comment] 2017-07-06 14:11
I was having this same issue.  Upgraded from 10.12.6 public beta 4 to 10.13 public beta 1.  Wavebox would not launch and would freeze, resulting in having to force quit.  

When I opened wavebox at first, I used the "Show all windows" feature that you can select by right clicking on the Dock icon. I have three monitors and if the app is not on a particular screen you get a text in the middle of your screen that says "No Available Windows".  2 out of 3 monitors said this.  the 3rd monitor where I usually kept wavebox didn;t show this text and usually this feature will pull your app window to the center of the screen.  Not the case.  I did see however that there was a 1 pixel wide line about 20 pixels high.  That was the app, but there was no way to interface with it, especially since it was frozen up.  Once I force quit and reopened the app and tried "Show all windows" I then got the "No Available Windows" on all 3 monitors.  

Deleted the wavebox folder in ~/Library/Application Support/ and reluanched wavebox and it came right up, fixed my issue.  Running wavebox 3.1.12.

**Comment by hlidotbe** [comment] 2017-07-06 15:19
I just did a sample of the process on launch. For me it hangs before getting a change to display the full menu so I can't "show all windows"

[Sample of Wavebox.txt](https://github.com/wavebox/waveboxapp/files/1128316/Sample.of.Wavebox.txt)

**Comment by Thomas101** [comment] 2017-07-07 07:42
Would anyone be able to give this early build of Wavebox a try? You can [download it from here](https://wavebox.io/dl/builds/Wavebox_3_1_12_0277a45_osx.dmg). This has an updated version of electron with some High Sierra fixes and I'm hoping it will work for everyone!

**Comment by hlidotbe** [comment] 2017-07-07 10:09
Same issue 😞

**Comment by Thomas101** [comment] 2017-07-10 10:53
I wonder if this is some kind of underlying issue with Chromium. Would you be able to give [version 3.1.8](https://github.com/wavebox/waveboxapp/releases/tag/v3.1.8) a try?

**Comment by timhanley** [comment] 2017-07-10 11:49
Tried 3.1.8 just now and it still exhibits the same issue @Thomas101

**Comment by hlidotbe** [comment] 2017-07-10 11:50
I confirm. Same problem

**Comment by Thomas101** [comment] 2017-07-10 11:59
Thanks for trying that @timhanley @hlidotbe. Would you be able to quit Wavebox, open the terminal and run the following...

`/Applications/Wavebox.app/Contents/MacOS/Wavebox --enable-logging --v=1`

This should give any runtime errors that popup

**Comment by timhanley** [comment] 2017-07-10 12:32
Here's the terminal output for that command running against Wavebox 3.1.8 @Thomas101 

2017-07-10 13:31:12.295 Wavebox[36847:2833704] !!! BUG: The current event queue and the main event queue are not the same. Events will not be handled correctly. This is probably because _TSGetMainThread was called for the first time off the main thread.
GVA info: Successfully connected to the Intel plugin, offline Gen9

**Comment by timhanley** [comment] 2017-07-10 12:37
Output after issuing a Force Quit.

[36847:0710/133316.478354:VERBOSE1:atom_browser_main_parts_posix.cc(139)] Handling shutdown for signal 15.
[36847:0710/133316.488680:VERBOSE1:statistics_recorder.cc(541)] Collections of all histograms
Histogram: AsyncDNS.ConfigChange recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.ConfigParseDuration recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: AsyncDNS.ConfigParsePosix recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: AsyncDNS.ConfigParseResult recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.HostParseResult recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.HostsChange recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.HostsParseDuration recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: AsyncDNS.HostsSize recorded 1 samples, mean = 213.0 (flags = 0x1)
0    ... 
196  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
258  ... 

Histogram: AsyncDNS.WatchStatus recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.AtExitSurfaceCount recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.GPUProcessInitialized recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.GPUProcessLaunchTime recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: GPU.GPUProcessLifetimeEvents recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.GPUProcessSoftwareRendering recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.GPUProcessTerminationStatus recorded 1 samples, mean = 4.0 (flags = 0x1)
0  ... 
4  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
5  ... 

Histogram: MPArch.ChildProcessLaunchFirst recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: Media.Midi.ResultOnShutdown recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: Media.Midi.Usage recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: Mojo.System.Node.ConnectedPeers recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: Mojo.System.Node.PendingChildren recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: OSX.SystemHotkeyMap.LoadSuccess recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: Plugin.FlashUsage recorded 1 samples, mean = 2.0 (flags = 0x1)
0  ... 
2  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
3  O                                                                         (0 = 0.0%) {100.0%}

Histogram: Startup.BrowserMainRunnerImplInitializeLongTime recorded 1 samples, mean = 419.0 (flags = 0x1)
0    ... 
372  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
429  ... 

Histogram: Startup.BrowserMainRunnerImplInitializeStep1Time recorded 1 samples, mean = 416.0 (flags = 0x1)
0    ... 
378  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
449  ... 

Histogram: Startup.BrowserMainRunnerImplInitializeStep2Time recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ... 
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ... 

Histogram: UMA.Histograms.Activity recorded 76 samples, mean = 4.2 (flags = 0x1)
0  ---O                                                                      (1 = 1.3%)
1  ------------------------------------------------------------------------O (25 = 32.9%) {1.3%}
2  O                                                                         (0 = 0.0%) {34.2%}
3  --------------------------------O                                         (11 = 14.5%) {34.2%}
4  --------------------O                                                     (7 = 9.2%) {48.7%}
5  --------------------O                                                     (7 = 9.2%) {57.9%}
6  ... 
8  ------------------------------------------------------------------------O (25 = 32.9%) {67.1%}
9  ... 

Histogram: V8.Initializer.LoadV8Snapshot.Result recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: V8.Initializer.OpenV8File.Result recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ...

**Comment by Thomas101** [comment] 2017-07-10 14:20
Thanks! The long stacktrace on force quit is expected. Do either of you use brew or macports? Have you updated those libraries since updating to High Sierra?

**Comment by timhanley** [comment] 2017-07-10 15:26
I use neither brew nor macports on the machine I have High Sierra on.

**Comment by hlidotbe** [comment] 2017-07-10 15:37
I have brew installed indeed. Not sure I did an update recently, I'll give it a shot. That being I haven't installed wavebox through it if that's even an option.

**Comment by Thomas101** [comment] 2017-07-12 14:26
We've (finally) managed to reproduce the issue our end and hopefully got a fix. It's been released to the beta channel as version 3.1.14 and can be [download from here](https://github.com/wavebox/waveboxapp/releases/tag/v3.1.14). Would be great to know if it fixes for everyone else too

**Comment by timhanley** [comment] 2017-07-12 15:35
It's working like a charm @Thomas101, many thanks!

**Comment by hlidotbe** [comment] 2017-07-13 10:16
Fixed for me too! Thanks a lot (and thank you for the slack notifications bug :) )

**Comment by Thomas101** [comment] 2017-08-02 11:45
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-08-02 11:45 UTC
Labels: in-beta, os:macOS

**Comment by sryanb** [comment] 2017-12-17 03:03
Might need to re-open this. I'm unable to launch Wavebox 3.6.0 on OSX High Seirra 10.13.2. App hangs on startup screen with the wavebox logo spinning saying "starting wavebox" but never starts.
