### ISSUE TITLE
feature request: import/export of wavebox settings

### ISSUE THREAD

**Issue by 33b5e5** [wavebox/waveboxapp#231] opened 2017-06-11 03:47 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS Sierra (10.12.5)

I'd love an option to export the Wavebox settings (including all the account setup stuff), to make it easier to setup Wavebox on a second machine. I.e., setup everything on the Desktop, export that, import it to a laptop, re-authenticate and off you go...

**Comment by caykmar** [comment] 2017-06-11 16:31
I came here to see if this was an option too. This would be particularly useful for setting up an enterprise standard desktop environment. For example, if we could pre-configure the accounts that should be in wavebox and then simply replicate the setup on each employee's desktop  -- would be a phenomenal feature.

**Comment by Thomas101** [comment] 2017-06-12 14:37
It's on our next-up list :). Duplicate of https://github.com/wavebox/waveboxapp/issues/207

**Closed by Thomas101** 2017-06-12 14:37 UTC
Labels: duplicate
