### ISSUE TITLE
Office365 Outlook PDF viewer not working

### ISSUE THREAD

**Issue by LesterU** [wavebox/waveboxapp#51] opened 2017-04-11 06:52 UTC
* Which version of Wavebox are you using? [3.1.2]

* Which Operating System are you using? [Windows 10]

The PDF viewer in Office365 Outlook doesn't work. It just says 'couldn't load plugin'
Is it possible to get this working? Otherwise I have to download and this is a pain.

![screenshot 2017-04-11 16 48 52](https://cloud.githubusercontent.com/assets/27270261/24896133/e2a7ee80-1ed6-11e7-8afa-53a77bdc43f2.png)

**Comment by Thomas101** [comment] 2017-04-11 08:41
Thanks, we'll take a look into what's happening here

**Comment by jacksarick** [comment] 2017-04-12 04:07
Same problem on OS X. The problem is that chromium, and therefore electron, has no built-in support for displaying PDFs. Gmail bypasses this issue by providing its own PDF viewer, but O365 relies on whatever plugin the app provides. 

Mozilla provides a [free all javascript library](https://github.com/mozilla/pdf.js) to view PDFs, as an alternative to the plugin that Chrome uses. One solution would be to some way add it as a plugin for electron, though I'm not quite sure how to do that.

**Comment by Thomas101** [comment] 2017-04-14 07:32
Hi, I've been looking into this. Electron has started to add support for rendering PDFs in the beta channel, but it looks like there's still a few issues around it.

I can get a pdf to render by just pointing Wavebox at it, but it looks like Microsoft are doing something else with it, either embedding it with some extra arguments or serving it up with some some missing headers etc. I've raised an upstream issue with electron https://github.com/electron/electron/issues/9192 to see if they can shed any light on this

**Comment by Thomas101** [comment] 2017-12-21 09:01
There's been some improvements to the PDF engine in the very latest beta of electron, we've given these a try, but unfortunately they don't fix the issue.

On the flip side to that though, if you have access to the [Outlook beta](https://www.google.co.uk/search?q=outlook+beta&oq=outlook+beta&aqs=chrome..69i57j0l5.6806j0j4&sourceid=chrome&ie=UTF-8) we have managed to add support in this and PDFs render as you'd expect. We also shipped PDF printing support in 3.5.0 which uses a different engine to render PDFs, we think we may be able to repurpose this in outlook for rendering too

**Comment by Thomas101** [comment] 2018-07-20 12:55
This should be fixed in the current version of Wavebox, but if you're still seeing the issue let me know and I'll take another look. Thanks!

**Closed by Thomas101** 2018-07-20 12:55 UTC
Labels: account:microsoft, bug, upstream: electron
