### ISSUE TITLE
Possible rendering problems with High Sierra

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#395] opened 2017-09-26 15:20 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.3.3beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Mac OSX High Sierra

Since updating to High Sierra yesterday I've been seeing some weird rendering issues with Wavebox. Sometimes icons for account services (like Drive and Calendar for a Google Inbox account) won't render in the left bar, although the main account icons do. Also, content in the main content area isn't rendered. Like, for an Inbox account only the "+" button and a few headings will be rendered initially, and the rest of the content area will be empty space. Moving the mouse over the content area will cause the content under the mouse to redraw (so moving the mouse around in the content area will eventually cause everything to be drawn properly).

This could be unrelated to my High Sierra upgrade (and I'm not sure what in HS would cause Electron rendering issue), but it seems pretty coincidental.

**Comment by Thomas101** [comment] 2017-09-27 08:01
Hi, thanks for reporting. It would be great to have some more info so we can try to reproduce it...

1. Does this happen everytime or is it sporadic?
2. Would you be able to send a screenshot our way
3. Do you know the year and model of your mac

There are a couple of settings that might also help. If you open Settings and then the Advanced tab, try enabling `Ignore GPU Blacklist`, restarting and seeing if that makes a difference. If it doesn't, feel free to turn this off again and try enabling `Disable hardware acceleration`.

**Comment by jason0x43** [comment] 2017-09-27 12:25
At the time I was reporting, it was happing very frequently. Like, I'd start Wavebox, everything would look normal, then at some point I'd look back and UI elements would have disappeared. However, the issue seems to have calmed down for the moment. Possibly it was just some transient GPU-related issue from to the upgrade. I'll add more details if it comes up again.

**Comment by Thomas101** [comment] 2017-10-02 09:08
Thanks for the update. I'll close this off for now, but if you start seeing it again let us know and we'll look into again

**Comment by jason0x43** [comment] 2017-10-03 00:55
I've continued to see this behavior occasionally. I attached a few screenshots showing the issue (the pixelated content is not part of the issue). In the first, Wavebox has suddenly become mostly empty. I haven't been able to determine any particular trigger for this. Sometimes it happens when Wavebox first opens, sometimes just randomly (presumably after something prompted a redraw). In any case, in the first screenshot the service icons are missing on the left (Calendar and Hangouts under the top account, and Calendar and Drive under the second account), and most of the Inbox content is empty. The remaining shots were taken after moving the mouse around, which causes page elements to render. Moving the mouse over the service icons will cause their tooltips to show, but won't cause the icons to render. However, clicking the service icons will cause them to render.

Refreshing the account (with cmd-r) will cause Inbox to fully render, and refreshing the entire UI (with cmd-shift-r) will cause the service icons to render.

![screen shot 2017-10-02 at 20 02 50](https://user-images.githubusercontent.com/1042866/31105623-a20b834e-a7b3-11e7-9791-d2da35121df1.png)
![screen shot 2017-10-02 at 20 02 55](https://user-images.githubusercontent.com/1042866/31105626-a217d22a-a7b3-11e7-9119-b30aac257f18.png)
![screen shot 2017-10-02 at 20 03 12](https://user-images.githubusercontent.com/1042866/31105624-a215390c-a7b3-11e7-9abe-6fd3abddb34b.png)
![screen shot 2017-10-02 at 20 03 22](https://user-images.githubusercontent.com/1042866/31105625-a21550ae-a7b3-11e7-8861-cc631edb9f23.png)

**Comment by Thomas101** [comment] 2017-10-03 07:27
Drats, was hoping it was just something sporadic! I haven't seen anything reported on electron issues as of yet, so I'm wondering if this is something that Wavebox is doing that a lot of other apps are not.

If you click the Apple icon in the top-right of your screen and go to `About this mac`, would you be able to send a screenshot of the Overview tab? Maybe we can try to get a machine to reproduce the issue here.

**Comment by jason0x43** [comment] 2017-10-03 12:14
Yeah, so was I. :(

I don't run any other Electron apps on a regular basis, so I can't say much there. I've only seen the issue with Wavebox, both in the main window and in external windows opened by Wavebox.

![screen shot 2017-10-03 at 08 10 04](https://user-images.githubusercontent.com/1042866/31124503-b9dad16e-a812-11e7-8fea-71ac9ec2b9c2.png)

**Comment by plan8studios** [comment] 2017-10-03 20:08
I'm experiencing the same issue with similar hardware.
![screen shot 2017-10-03 at 2 07 26 pm](https://user-images.githubusercontent.com/680706/31146525-4cc0507c-a844-11e7-850c-6a61c7eb177f.png)

**Comment by Thomas101** [comment] 2017-10-04 10:47
It looks could be related to discrete graphics rendering then. Just at a guess.

We've got a macbook pro that I think has a card in here, so I'll try to update that one and see if I can reproduce.

There's also a new version of electron available which uses a newer version of chromium. We've yet to update to this as it's still hot off the press, but I'll be looking to do that in the next week or so, I'll pass a build your way once we've done that to see if resolves the issue.

@plan8studios have you tried enabling `Disable hardware acceleration` under advanced settings?

Another thing to try might be to show the titlebar. A few people upstream have reported some graphical problems with the frameless window. If you open settings in Wavebox in the `User Interface` section there's a `Show titlebar` option, try enabling this

**Comment by jason0x43** [comment] 2017-10-04 12:48
Ah, I forgot about disabling hardware acceleration. I'll give that a shot.

Also, regarding the title bar, I've also seen the issue in secondary Wavebox browser windows that _do_ have title bars, if that's relevant.

**Comment by plan8studios** [comment] 2017-10-04 14:39
I've disabled hardware acceleration. Fingers crossed! :-)

**Comment by Kachilero** [comment] 2017-10-04 16:13
I've also been experiencing some rendering issues after updating to High Sierra, chief among them is that the app would go blank from time to time, but that seems to have stopped.
I'm also experiencing a probably unrelated issue where when the app is in full screen mode, the icons for minimizing disappear.

**Comment by jason0x43** [comment] 2017-10-05 14:54
Disabling hardware acceleration _seems_ to have done the trick. I haven't noticed any flashing, missing UI elements, or other redrawing issues.

Also, ironically, Inbox seems to work more smoothly. When hardware acceleration was enabled, it seemed like Inbox was sometimes slow to respond, or took multiple clicks, or was in some difficult-to-define way unresponsive. Possibly this is related to whatever redrawing issue caused elements to no appear, or sometimes caused flashing in the window. It seems to behave better now. That could just be me, though.

**Comment by plan8studios** [comment] 2017-10-05 16:10
So far, so good! One day in with hardware acceleration disabled and no weird UI glitches 👍

**Comment by Thomas101** [comment] 2017-10-06 08:40
Good to hear that's working for now! I'll be getting a new beta out early next week which has a newer version of Chromium, I'm hoping this will fix the compatibility issues without needing to disable hw acceleration

**Comment by nlenkowski** [comment] 2017-10-10 11:10
I've been seeing a similar issue after upgrading to High Sierra, but not just with Wavebox. Both Chrome itself and a few other Electron based apps I use are having occasional rendering glitches. I'm on an older Macbook Pro mid-2012 w/ a discrete graphics card (Nvidia 650M). Perhaps there is an upstream issue with Chromium or Electron?

I've tried resetting the PRAM and SMC and clearing all MacOS caches, to no effect. I'll try turning off hardware acceleration, but that's a temporary fix.

**Comment by raptor235** [comment] 2017-10-11 23:52
Seeing same issues, Atom & Chrome have had artifacts all week long...

  Chipset Model:	NVIDIA GeForce GT 750M

**Comment by jason0x43** [comment] 2017-10-17 15:09
Hardware acceleration definitely seems to be the issue. I haven't seen this problem come up at all since disabling hardware acceleration a couple of weeks ago.

**Comment by chris-X73** [comment] 2017-10-26 12:07
I'm experiencing the same problem with other apps like Trello and Google GSuite as well. Parts of browser window are not rendered correctly or totally missing, browser content is flickering etc. - so I don't think the problem is related to Wavebox but more to High Sierra in combination with Chrome.

**Comment by chris-X73** [comment] 2017-10-26 12:11
Disabling hardware acceleration in Chrome worked for me as well to quickfix the problem. 👍

**Comment by nlenkowski** [comment] 2017-10-26 12:25
For those not aware, this looks to be an upstream issue with Chromium that affects both Chrome and Electron apps for macOS High Sierra users with certain discrete graphics cards. A Chromium bug report has been filed here, https://bugs.chromium.org/p/chromium/issues/detail?id=773705

**Comment by raptor235** [comment] 2017-11-01 00:29
I've submitted a bug report to apple.. problem id 35284875 not sure if they'll ever get to it... if they don't I guess a downgrade back to sierra will be required... I can't put up with this much longer.

**Comment by Thomas101** [comment] 2017-11-01 11:52
@raptor235 there's some chatter on the Chromium issue tracker about this being a problem with the GPU driver. I think the Chromium team are looking to disable certain gpu features on certain machines until Apple patch the driver. Once a fix makes it out into a Chromium release, we'll be updating Wavebox too

**Comment by raptor235** [comment] 2017-11-01 11:59
Yeah I've tried disabling some of those features in chrome flags which kills the performance... so not sure how much of a fix that's going to be... we really need to make a stink of this to apple because it seems they're going to be the only ones to be able to fix this. Since it's older hardware I don't know if it's going to be at any high priority... you know they're working on implementing the next set of emoji into osx... sigh.. 

Latest release doesn't mention any issues about this.... I don't know how this stuff gets past as they spend a ton of money on tech.

**Comment by felipedrumond** [comment] 2017-11-06 18:24
I'm having exactly the same issues mentioned in this thread, but only in Chrome based apps, such as Chrome and Postman.

**Comment by Thomas101** [comment] 2017-11-14 09:45
Some users on https://github.com/electron/electron/issues/10736#issuecomment-343746578 have reported that downloading the beta drivers from nvidia has helped them with graphics issue. We haven't been able to confirm yet, but if anyone's looking at updating anyway it would be great to know how it works for them.

The drivers can be downloaded from http://www.nvidia.com/download/driverResults.aspx/126538/en-us

**Comment by felipedrumond** [comment] 2017-11-14 13:22
@Thomas101 I'm giving it a chance. Let's see what happens.

**Comment by felipedrumond** [comment] 2017-11-17 12:32
@Thomas101 After installing those drivers, I haven't seen any renderisation issues.

**Comment by Thomas101** [comment] 2017-11-20 09:10
@felipedrumond That's great news! There's some patches gone into electron which are supposed to help with this too - these will be shipping in the 3.5.2 beta shortly

**Comment by felipedrumond** [comment] 2017-11-20 12:05
@Thomas101 Confirming... I had no renderisation issues after updating the drivers! Thank you!

**Comment by Thomas101** [comment] 2017-11-21 09:30
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2017-11-23 09:25
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-11-23 09:25 UTC
Labels: bug, in-beta, os:macOS
