### ISSUE TITLE
Bug: Microsoft teams - copy on right click does not send to clipboard Ctrl+c does though (needs verification)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#863] opened 2018-11-28 13:42 UTC
* Wavebox Version: 4.4.2beta
* Operating System & Version: windows 10
* Account type (if applicable): Microsoft teams

**Expected & actual behavior**
Context menu copy and ctrl+c should send copied item to clipboard. Only ctrl+c does however.

**Steps to reproduce**
Open microsoft teams.
Select message or text
Right click and press Copy
Paste into a text document

The text is not copied.

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
Tested it in chrome browser also and there the right click copy and ctrl+c does copy the text as intended. Just that wavebox does not. My best guess is that its because I am using the built in wavebox browser instead of chrome browser.

**Comment by nmat** [comment] 2018-11-28 14:15
Just noticed the same effect on zendesk

**Comment by nmat** [comment] 2018-11-30 07:57
Been testing this out a little more on beta release. It seems that it might be something with the right click -> clipboard menu because I am seeing this quite a lot on different types of services. Its not specifically for teams and zendesk but general. Gmail "seems" to work but I can't guarantee it.

**Comment by Thomas101** [comment] 2018-11-30 09:18
I've been struggling to reproduce this. Have you tried restarting the machine - just as a might fix it.

That aside, we found that `Paste and match style` is broken on macOS. There's some kind of upstream bug (https://github.com/electron/electron/issues/15219).

I've put a workaround in commit 5b4921c would be good if that fixes it for you

**Comment by Thomas101** [comment] 2018-11-30 09:30
That's okay. The other thing I mean to ask - what were you trying to copy in Teams? E.g. text you'd typed or a message you'd received

**Comment by nmat** [comment] 2018-11-30 09:32
In this case I am only trying to copy standard text from a message.

And I use copyQ as a clipboard manager. What happened then was that I saw the old text was still being used after right click > copy. So when I pasted in powershell I got 1000 rows instead of that small text I was hoping that would have been copied. :/

my powershell was not happy with me.

**Comment by Thomas101** [comment] 2018-11-30 09:35
> my powershell was not happy with me.

Probably not. It's hard because I can't reproduce, but it sounds consistent with what other have reported with electron. I suspect that commit will fix it :)

**Comment by nmat** [comment] 2018-12-01 14:10
Tests done:

**Windows 10:** _Version 1809 (OS Build 17763.134)_

* Right click - copy and then paste to atom editor

Feedly, Microsoft Teams, Facebook Messenger, Whatsapp

Works perfectly. This fixes the issue on windows 10 just fine! Thank you! seems you are right here.

Same goes for Ctrl+C and Ctrl+V

One thing I have noticed on copy of text in teams is that it also brings a complete link for the message. Which is a bit strange. This only seems to be part of microsoft teams though. 

**macOS:** _10.14.1_

* Right click > copy

Feedly

Works perfect

**Comment by Thomas101** [comment] 2018-12-03 08:59
> One thing I have noticed on copy of text in teams is that it also brings a complete link for the message. Which is a bit strange. This only seems to be part of microsoft teams though.

Can you give an example? Sounds like it could be something that teams is doing to present the text differently.

**Comment by nmat** [comment] 2018-12-04 11:17
I have managed to figure out why this occurs.

In Teams you have the time which is marked as a link. 

This link is the link of which the paste presents. So its not really a issue if you see it in a whole.

Tested this using chrome also. And I really do think this can be closed off since it behaves the exact same way in both browser and wavebox. The function is intentional based on how teams handle sending information to the clipboard. You can mark this as fixed in-beta.

**Comment by nmat** [comment] 2018-12-04 11:33
it works perfectly in beta thank you!

**Comment by Thomas101** [comment] 2018-12-04 14:45
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-12-04 14:45 UTC
Labels: bug, in-beta
