### ISSUE TITLE
Feature request: ability to move sidebar to top/bottom/right edge

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#485] opened 2017-11-27 09:05 UTC
* Which version of Wavebox are you using? [3.6.1-beta]

* Which Operating System are you using? [Mac OSX 10.12.6, Ubuntu 17.10]

I would like the possibility to move the sidebar to another location, e.g. top or bottom of the window. 
Where it is now it collides with my desktop docks in both my Mac and my Linux PC, as they rest on the left edge of the screen. 

If this is already possible, apologies, I wasnt able to find the settings.

**Comment by Thomas101** [comment] 2017-11-27 11:44
There is some talk about adding move left/right, but haven't added anything in as yet.

**Comment by Tahini-123** [comment] 2018-03-31 06:15
Any news on this?

**Comment by Thomas101** [comment] 2018-04-04 09:29
There's a bunch of things we're planning on working on in a UI refresh soon. This will be one of those (https://github.com/wavebox/waveboxapp/projects/6#card-8332108)

**Comment by lens0021** [comment] 2023-02-17 02:04
Duplicate of #243?

**Comment by Thomas101** [comment] 2023-02-17 12:28
Merging with #243

**Closed by Thomas101** 2023-02-17 12:28 UTC
Labels: enhancement
