### ISSUE TITLE
Backspace can not erase the last one character during Japanese IME conversion (macOS)

### ISSUE THREAD

**Issue by shuntaroy** [wavebox/waveboxapp#44] opened 2017-04-10 09:27 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.2

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS 10.12.4

But the issue continues from older versions (WMail) under the older Mac OS X 10.11.x.

In inputting Japanese sentences, we Japanese use Japanese IME (Input Method Editor) to convert alphabets to Japanese (CJK) characters.
The main process is converting Hiragana (ひらがな; Phonogram) to Kanji (漢字; Chinese characters; ideogram), and we have the state of selecting Kanji candidates because many Kanji have same sounds.
We enter the state almost every time when we want to input a word.
The issue I reporting occurs during the state of selecting Kanji candidates.
After entering the conversion state provided by Japanese IME, we sometimes delete characters in order, for example, to fix typo.
Wavebox app prevent us to delete a last character which is inside the range of the conversion state in one stroke of backspace (delete) key, while the other situation we can do that in just one push of backspace.
We have to input two delete keys to delete the last character, which annoys us.

**Comment by jacksarick** [comment] 2017-04-10 18:22
Are you sure this is a problem with Wavebox? Wavebox is displaying the Gmail page without changing inputs, so if you're having problems in Gmail, it could be a problem with Google, not Wavebox. Do you have the same problem when using Gmail in a Chrome?

**Comment by shuntaroy** [comment] 2017-04-10 23:24
Yes, unfortunately, I am sure.

Only Wavebox cause the problem, while Inbox of Chrome or other browsers and other Inbox wrapper apps do not. 

I remember the issue begins from v3.0 or latter part of v2.x of WMail. 
Before those versions, WMail does not have the issue.

**Comment by Thomas101** [comment] 2017-04-11 08:33
If it's only from the later version of WMail etc it sounds like it could be the newer version of chromium. It would be great to know...

* Are you able to give me a line of text I can copy-paste into Wavebox to see the issue myself?
* Does it fail on all input fields?
* If you go to add an account and choose "Add Any Website" and paste the line of text into the website name field does this exhibit the same behaviour?

Thanks

**Comment by shuntaroy** [comment] 2017-04-11 12:23
- Are you able to give me a line of text I can copy-paste into Wavebox to see the issue myself?
  - The issue does not occur on deleting "converted" texts, but reproduces in "converting" texts. So any copy-pasted texts can be deleted normally.
- Does it fail on all input fields?
  - Yes, it fails on any search fields, Drive Document, and so on.
- If you go to add an account and choose "Add Any Website" and paste the line of text into the website name field does this exhibit the same behaviour?
  - Yes, it does. Even it can be seen in input fields of the "Add Any Website dialogue"

I prepared GIFs of this problem.

Here is a normal behaviour of inputting a Japanese word.
"日本語" means "Japanese language", which consists of 4 characters of Hiragana ("にほんご", sounds like nee-hon-go).

![wavebox_not_bug](https://cloud.githubusercontent.com/assets/6918169/24908464/164f2c20-1efb-11e7-8d88-79c4ae961e2c.gif)

Space keys are used for entering the "converting" state and selecting Kanji or other candidates.
If I pressed "enter" key, I can decide one of the candidates.
The first delete (backspace) key cancels the "converting" state to exit the mode.
This procedure is usual among any type of Japanese IMEs (I use the Google-provided Japanese IME instead of macOS default one but the difference does not matter in this issue).

And the following GIF is a behaviour of Wavebox (in the search box of google.co.jp, added by "Add Any Website").

![wavebox_bug](https://cloud.githubusercontent.com/assets/6918169/24908546/5e42ab6a-1efb-11e7-885d-cf9ef0e11ecf.gif)

You could see that Wavebox needs extra one backspace key to delete 4 characters.

I hope the above examples could explain the issue.
Thanks.

**Comment by Thomas101** [comment] 2017-04-12 13:26
Thanks those gifs are super helpful! I've done some digging around into this and can reproduce it in the most basic electron project. It looks like an issue with the run of electron versions using chromium 56. (One based on chrome 53 didn't exhibit this behaviour).

I've raised an issue upstream with electron https://github.com/electron/electron/issues/9173 hopefully they can throw some more light onto this!

**Comment by shuntaroy** [comment] 2017-04-12 14:43
Thank you so much for dealing with this issue. 
And I apologise for bothering you with the problem which is not directly related to your software but to electron...I could not notice that.
I hope the chromium project will fix this issue.
Thank you again for your sparing time for clarifying this issue.

**Comment by Thomas101** [comment] 2017-04-12 16:55
No worries! Lets hope we can get the whole thing fixed :)

**Comment by Thomas101** [comment] 2017-05-31 10:24
This has been fixed upstream and will be released in the next version of Wavebox. Thanks!

**Comment by Thomas101** [comment] 2017-06-22 08:08
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-06-22 08:08 UTC
Labels: bug, upstream: electron, waiting-release
