### ISSUE TITLE
Can't preview or download attachments in office 365/outlook

### ISSUE THREAD

**Issue by wahinevu04** [wavebox/waveboxapp#241] opened 2017-06-12 19:40 UTC
When I try to preview attachments to emails in office 365/outlook, says plugin not loaded. When I try to download the attachment, it opens a new browser window, but nothing happens after that. Any insight is appreciated. Thanks.

* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Mac OS X 10.10.5

**Comment by Thomas101** [comment] 2017-06-13 07:40
Duplicate of #51 #182 #219 fix due to land in next relase

**Closed by Thomas101** 2017-06-13 07:40 UTC
