### ISSUE TITLE
Gmelius scheduling issues

### ISSUE THREAD

**Issue by thanosgatos** [wavebox/waveboxapp#483] opened 2017-11-26 09:26 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.6.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04 LTS

I have noticed the following two issues when using Gmelius in Inbox by Gmail inside Wavebox:

1. When replying to an email and you schedule your answer to be sent later, your answer goes to Drafts, but it is NOT scheduled.
2. Once you manage to schedule an email, it does not get the "Scheduled" tag. Instead of looking like this
![image](https://user-images.githubusercontent.com/8896776/33238757-59753da0-d29c-11e7-8187-cbafdcf38969.png)
it looks like this
![image](https://user-images.githubusercontent.com/8896776/33238764-7a529338-d29c-11e7-8ad5-0ee6f61dbd36.png)

**Comment by thanosgatos** [comment] 2017-11-27 05:42
I have just realized that: 

1. New emails sent from Inbox are not tracked
2. Not all messages that are tracked in Inbox, outside of Wavebox, are tracked either

**Comment by Thomas101** [comment] 2017-11-27 12:02
Thanks for reporting. I gave the scheduled a try, but that came up right away for me. As for the tracking ticks these didn't come up right away for me in Wavebox, but did after a little while. I wonder if Gmelius have been having issues their end.

If you try testing these again do you still see the same behaviour or something different?

**Comment by thanosgatos** [comment] 2017-11-27 17:51
I am trying things again, in Wavebox:

1. Composing a new email, scheduling it to go in 1 h.
![image](https://user-images.githubusercontent.com/8896776/33280224-0aeb9ac6-d3aa-11e7-9f35-3bc88529c3aa.png)

2. After NOT getting the notification about the email being scheduled, checking my drafts:
![image](https://user-images.githubusercontent.com/8896776/33280273-2f6988ae-d3aa-11e7-8a14-00d2053fe90f.png)
And it's not even scheduled, apart from not having the label.
![image](https://user-images.githubusercontent.com/8896776/33280304-49a9aaa0-d3aa-11e7-9507-ec9232c31b5f.png)
Editing here, in the Drafts, it does get scheduled, but not label.

3. Sending an email and checking the Sent folder, I do NOT see the tracking ticks
![image](https://user-images.githubusercontent.com/8896776/33280425-b0bc61d8-d3aa-11e7-9df4-a7705400abea.png)
In the Sent folder:
![image](https://user-images.githubusercontent.com/8896776/33280453-c5eba690-d3aa-11e7-8854-f40eccacf701.png)

I have already contacted Gmelius too, and they're also looking into the issue. Are you in any way working with them maybe? I have no idea what is wrong or how to fix this. Any suggestions are welcome.

**Comment by thanosgatos** [comment] 2017-11-28 22:34
During my correspondence with the Gmelius team, I have sent tracked emails, as well as scheduled emails from both Inbox and Gmail from both Wavebox and Chrome. Hereafter, I am pasting my comments, as well as screenshots of my findings:

The weird thing is that Inbox in Wavebox, where the issue is, when you go to the sent folder, whatever is sent from Inbox does not seem to be tracked (inbox_wavebox_fresh). After a while (around 1 min, after going from the inbox folder to the sent folder) the ticks appear. Just weird!

- Gmail in Chrome
![gmail_chrome](https://user-images.githubusercontent.com/8896776/33347382-5da407fc-d49b-11e7-906f-d72b43eab47e.png)

- Gmail in Wavebox
![gmail_wavebox](https://user-images.githubusercontent.com/8896776/33347383-5dc05948-d49b-11e7-9bc5-0ee8108183a7.png)

- Inbox in Chrome
![inbox_chrome](https://user-images.githubusercontent.com/8896776/33347384-5ddb18fa-d49b-11e7-9449-57a82c47ff61.png)

- Inbox in Wavebox (fresh)
![inbox_wavebox_fresh](https://user-images.githubusercontent.com/8896776/33347387-5e143716-d49b-11e7-8d3b-43ab21cb306e.png)

- Inbox in Wavebox
![inbox_wavebox](https://user-images.githubusercontent.com/8896776/33347386-5df541d0-d49b-11e7-9308-510016c4769d.png)


When it came to the scheduled ones, things got even weirder.
- Gmail in Chrome
![sched_gmail_chrome](https://user-images.githubusercontent.com/8896776/33347429-7fdc117a-d49b-11e7-910c-e5738ae5ac2b.png)

- Gmail in Wavebox
![sched_gmail_wavebox](https://user-images.githubusercontent.com/8896776/33347431-7ff91572-d49b-11e7-9076-f975a4d64ace.png)

- Inbox in Chrome
![sched_inbox_chrome](https://user-images.githubusercontent.com/8896776/33347433-801648a4-d49b-11e7-8bcf-5f45f89b6a28.png)

- Inbox in Wavebox
![sched_inbox_wavebox](https://user-images.githubusercontent.com/8896776/33347434-8033d20c-d49b-11e7-829b-16aca12564d0.png)


All emails were sent, delivered and read.

In the very end, the support team from Gmelius concluded that it must be an issue on your (Wavebox) side. They said, and I'm quoting, 

"_The problem seems to be caused by Wavebox. Sadly, we don't have any direct control over their integration of our own solution. They actually integrated our software without any permission from our side.

We're going to reach them to clarify those points and see how we could fix the situation for current Gmelius users._"

I hope all this somehow leads to the two teams working together, because it seems like there's great potential and a great match between the two tools. Looking forward to seeing this actually sorted out.

**Comment by Thomas101** [comment] 2017-11-30 15:30
Awesome, thanks for the in-depth info. We think we may have found the root cause, we we'll be putting a fix together for the next beta due early next week!

**Comment by Thomas101** [comment] 2017-12-05 14:47
Hi, the latest beta adds some improvements for Gmelius, so hopefully, this should work a little better, for example, unread indicators should show up much more reliably.

We did notice one thing in testing that isn’t quite fixed as regards the scheduled tag. When we added Gmelius to Inbox in Wavebox, scheduled an email to be sent from Gmail in Chrome and then checked for the tag in drafts in Inbox it didn’t appear unless we reloaded Inbox.

That said, when we tested the same with two separate Chrome profiles we saw the same behaviour. In the same way we had to reload Inbox in Wavebox, we had to reload Inbox in chrome too.

It would be great to get your feedback on how it works! There's some instructions on how to try the beta [here](https://wavebox.io/kb/beta-channel)

**Comment by thanosgatos** [comment] 2017-12-09 11:48
Hi, I have been trying the beta out, but my trial has expired, so I cannot do it right now. I will not be able to buy the subscription for a while, but I will get back to this after I do so.

**Comment by Thomas101** [comment] 2017-12-11 09:08
@thanosgatos get in touch via our [support page](https://wavebox.io/support) with the email that you're logged in to wavebox with (Go to Settings, Wavebox Tab and it will be in the top right), I'll add some extra time to your trial :)

**Comment by thanosgatos** [comment] 2017-12-12 08:55
Thanks for the offer--highly appreciated! I submitted a request, but later I went ahead and bought the actual subscription. It's an awesome product. I will keep my eyes on this issue.

**Comment by Thomas101** [comment] 2017-12-18 11:23
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-12-18 11:23 UTC
Labels: bug, extensions, in-beta
