### ISSUE TITLE
Wavebox on Ubuntu keeps crashing since two releases back

### ISSUE THREAD

**Issue by rajalokan** [wavebox/waveboxapp#750] opened 2018-08-06 04:18 UTC
* Wavebox Version:  3.14.10
* Operating System & Version: Ubuntu 16.04
* (Linux only) Install method: Debian Installer
* Account type (if applicable): all

**Wavebox should continue to run and not crash**

**Steps to reproduce**

**Is the bug persistent or intermittent?**
It is persistent except sometime it works for 1-2 hours and then crash and at times keeps crashing the moment you open it.

**Screenshots**

**Additional information**

I feel info above is sufficient. Please let me know if any other details you guys need.

**Comment by nmat** [comment] 2018-08-06 14:34
This only happens in latest beta releases?

If you change back to stable it works?

Can you also check the options for:

![image](https://user-images.githubusercontent.com/383031/43722890-a31c312c-9996-11e8-9dd0-1848425ccae0.png)

**Comment by Thomas101** [comment] 2018-08-08 09:42
Does the whole app come down or is it just a single tab/window? These have been pretty stable for a while but might be worth trying the following in settings...
1. Disable Sandboxing
2. Enable Isolate Account Processes

**Comment by rajalokan** [comment] 2018-08-17 04:00
Hi Guys, apologies for delayed response. Wasn't using this as I've turned to dedicated client. But I see issue is still there. 

@Thomas101 I tried both your suggestions. Checked `Enable Isolate Account Processes` and unchecked `Sandboxing` but now it crashes within 5 secs. Earlier it would stay for few minutes and hours before crashing. 

@nmat  I tried going back to earlier version ( 3.14.7) but it fails as below
```
$ sudo gdebi Wavebox_3_14_7_linux_x86_64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Wavebox
 wavebox: Wavebox
Do you want to install the software package? [y/N]:y
Selecting previously unselected package wavebox.
(Reading database ... 322884 files and directories currently installed.)
Preparing to unpack Wavebox_3_14_7_linux_x86_64.deb ...
Unpacking wavebox (3.14.7-1) ...
Setting up wavebox (3.14.7-1) ...
/usr/share/applications/wavebox.desktop: error: value "/opt/wavebox/Wavebox --mailto=%u > /dev/null" for key "Exec" in group "Desktop Entry" contains a reserved character '>' outside of a quote
Error on file "/usr/share/applications/wavebox.desktop": Failed to validate the created desktop file
/usr/bin/gtk-update-icon-cache
gtk-update-icon-cache: Cache file created successfully.
```

Looking at other issue #754 , you think it could be the same. Anyway I will give a try to downgrade to 3.14.6 and let you guys know. But yeah it is a pain to work without wavebox. Hope this resolves soon guys.

**Comment by rajalokan** [comment] 2018-08-17 04:16
Alright, so for above downgrade it seems it has downgraded ( the error was something else). I am using 3.14.7 and it seems to be working right now. I will update more on this but yeah the latest build still keeps crashing. Cheers.

**Comment by nmat** [comment] 2018-08-17 07:04
The above error seems to be regarding something about the .desktop and fails validation. I wonder if this is due to gnome3 vs unity that ubuntu uses.

**Comment by Thomas101** [comment] 2018-08-21 13:53
Thanks for the update! #754 should see it fail to launch completely so I don't think it's down to that.

When it crashes does the app completely quit, or does it lock up, or something else? If you're still up to trying the beta, it might be worth disabling GPU acceleration to see if that makes any difference

**Comment by Thomas101** [comment] 2018-09-10 10:34
@rajalokan would you be able to try this with the latest version (4.0.0) to see if you're still seeing the crash? Thanks

**Comment by tonybyng** [comment] 2018-09-10 15:05
Hi. Ive also been getting crashes a lot more recently - on Linux Mint 18.3 which is based on ubuntu - its been in the gmail account primarily but thats where i tend to be a lot and simply requires me to press the reload button and it comes back up. Its probably been about once or twice a day. Ive just updated to the 4.0.0 version so i will also see how it goes over the next week. I thought it might be to do with me activating the "multiple inbox" feature of gmail as I did that a few weeks ago as well but will see how it goes now on v4 (im on beta channel)

**Comment by Thomas101** [comment] 2018-09-25 09:19
Hi, we think we might have found the root cause of this and have put a patch out in version 4.2.0. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Would be great to know if this has worked for you too.

Also related #790

**Comment by mj0vel** [comment] 2018-09-28 19:13
HI there, I got the latest version, 4.2.0 and I am still experiencing this issue. Not sure if this matter but I actually have the pay version because I need access to Office365. Cheers and Thank you for the help.

**Comment by Thomas101** [comment] 2018-09-29 10:09
@tonybyng that's weird. There's very little change between. 4.2.0 and 4.2.1 it's just that when we update the menu we keep the old one in memory a little while before releasing it.

I'm still struggling to get a reprodable case that everyone's seeing, but whilst playing about I found that updating the menu 10x a second would bring a crash pretty quickly, but only about 50% of the time.  If it didn't crash soon after launch it would run fine. 

The fix that's gone into 4.2.1 seemed to stop this behaviour completely which is why I thought I'd nailed it. Just as a random test, does a restart help in anyway?. Did you try the build of 4.2.0 with the menus disabled completely?

**Comment by tonybyng** [comment] 2018-09-29 10:15
@Thomas101 Im fairly sure over the last 3 days since having 4.2 it hasnt happened. tbh Im getting so used to it happening that I may well not have realised but I dont think it happened. Are there any logs I can activate so that if it does happen again, you might be able to see some trace somewhere?   I closed Wavebox down and reloaded it  to see if it reproduced again afterwards but it didnt

**Comment by tonybyng** [comment] 2018-09-29 10:31
Just to confirm, mine doesn't stop wavebox from working - its not a crash in as much as the entire application fails. Its the window Im in that says something like "something has gone wrong, please reload" or similar and it presents a reload button, and i press the button and it fires back up again. Just to confirm my current settings are Isolate Account is off and enable Sandboxing is on (all options are on in Advanced, except Isolate) Is it worth me changing those now as mentioned by you  last month, or is it better i keep as they have been and see if it re-occurs?

**Comment by Thomas101** [comment] 2018-09-29 10:50
@tonybyng sounds like a separate issue! I'm guessing with Gmail? Possibly network related.

Do you want to open a separate issue I can try to get to the bottom if it. Drop some info in it about your connection setup (proxy VPN etc), if it occurs on every load or when you change network etc :-)

**Comment by mj0vel** [comment] 2018-10-01 07:19
This is the message I got when it randomly crashed: 

cornelius@neptune:~$ wavebox 
ln: failed to create symbolic link '/home/cornelius/snap/wavebox/127/.config/gtk-2.0/gtkfilechooser.ini': File exists
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Failed to generate minidump.Segmentation fault (core dumped)

**My System:**
cornelius@neptune:~$ uname -a
Linux neptune 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Any way to enable more logging?

Regards,
Murqui

**Comment by mj0vel** [comment] 2018-10-01 08:35
@Thomas101 

cornelius@neptune:~$ wavebox --version
4.2.0

**Comment by Thomas101** [comment] 2018-10-01 13:10
Hi all, it looks like this could be related to #790. We pushed an update out in 4.3.0 this morning which should fix this. Going to close this off, but if you're still seeing crashes let me know we'll look into what else can be causing it

**Closed by Thomas101** 2018-10-01 13:10 UTC
Labels: more-info

**Comment by rajalokan** [comment] 2018-10-01 18:48
Thanks @Thomas101  and all for resolving it. I have been using the beta release of 4.3.0 as in #790 and could confirm there were no crashes. Hopefully it is sorted. Thanks and :+1: .

**Comment by mj0vel** [comment] 2018-10-03 05:43
Thank you guys, application have been stable the whole day today. Thank you for getting this fixed.
