### ISSUE TITLE
AppImage for new versions?

### ISSUE THREAD

**Issue by simoniz0r** [wavebox/waveboxapp#353] opened 2017-08-13 11:43 UTC
Hello, I just recently found Wavebox, and I was wondering if you are going to continue making AppImages for the new versions.  It seems that 3.1.12 is the latest version that has an AppImage release.

Thanks in advance!

* Which version of Wavebox are you using? [3.1.12]

* Which Operating System are you using? [Ubuntu 16.04]

**Comment by Thomas101** [comment] 2017-08-14 11:00
Hi, the AppImages that are available at the moment have been contributed by community. Do you remember where you downloaded it from originally? I'll see if I can reach out to them

**Comment by simoniz0r** [comment] 2017-08-14 12:26
https://bintray.com/probono/AppImages/Wavebox

Thanks.

**Comment by probonopd** [comment] 2017-08-14 22:00
This was just an example made by me. This project might consider to provide official AppImages.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by Thomas101** [comment] 2017-08-18 14:33
Great, I'll try and add this into an upcoming release

**Comment by probonopd** [comment] 2017-08-18 14:57
electron-builder has native AppImage generation, and there is a electron-builder appimage target for electron-forge.  For  Electron Packager and please see https://github.com/electron-userland/electron-builder#pack-only-in-a-distributable-format.

**Comment by magicalbanana** [comment] 2018-06-27 22:23
Any updates on this? When running the app on Linux it's ridiculous when it comes to memory usage.

**Comment by Thomas101** [comment] 2019-01-23 14:42
I'm going to close this off as it's a duplicate of #34. AppImage is still something we're looking at adding support for, but it's easier if we have one place to track it. Thanks!

**Closed by Thomas101** 2019-01-23 14:42 UTC
Labels: packager
