### ISSUE TITLE
Downloaded File Rename

### ISSUE THREAD

**Issue by Thomasmavilo** [wavebox/waveboxapp#420] opened 2017-10-16 15:52 UTC
* Which version of Wavebox are you using?  3.4.0
* Which Operating System are you using?  Ubuntu 16.04
When a file is downloaded, wavebox appends to the file name. 
101517.zip becomes 101517.zip.waveboxdownload

Is there a way to disable this?

**Comment by Thomas101** [comment] 2017-10-17 08:22
Wavebox appends `.waveboxdownload` whilst the file is still downloading. Once it's complete, it should remove the extension and leave it as `.zip`. Is this happening, or does it always stay with `.waveboxdownload`?

**Comment by Thomasmavilo** [comment] 2017-10-17 11:17
The suffix stays after download.  This happens with all file types, not
just .zip files

Wavebox appends .waveboxdownload whilst the file is still downloading.
Once it's complete, it should remove the extension and leave it as
.zip. Is this happening, or does it always stay with .waveboxdownload?

**Comment by Thomas101** [comment] 2017-10-18 08:18
Hmmmm, that's interesting. Do you know which install format you're using? (e.g. snap, deb, tar etc...)

**Comment by Thomasmavilo** [comment] 2017-10-18 11:26
It was installed via snap.

**Comment by Thomas101** [comment] 2017-10-20 07:41
I think the root cause is down to snap permissions. I'll have a look if we can get around this, or if not drop the extension on snap installs

**Comment by Thomas101** [comment] 2017-10-26 14:59
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2017-11-01 08:42
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-11-01 08:42 UTC
Labels: bug, in-beta
