### ISSUE TITLE
Paste does not work in onenote service that is part of the office 365 integration

### ISSUE THREAD

**Issue by blakejwc** [wavebox/waveboxapp#544] opened 2018-01-23 18:08 UTC
* Which version of Wavebox are you using? [3.9.0]

* Which Operating System are you using? [Ubuntu 14.04]

I can't paste into my onenote page outside content (e.g. from the browser, or from a 365 outlook email)

**Comment by nmat** [comment] 2018-01-24 08:24
@blakejwc does the same happen when using right click copy/paste or just with shortcut keys?

**Comment by blakejwc** [comment] 2018-01-24 15:05
@nmat Yes, right click opens onenote's menu which has a paste option; however, clicking the paste option doesn't paste the outside content.  I just tried copying content from inside using the right click menu and onenote's copy option followed by the paste option.  That also didn't work.

**Comment by Thomas101** [comment] 2018-01-25 09:20
I'm seeing the same from the right-click menu. I'll look into what's not happening there.

I found it does work when using the os-level paste using <kbd>Ctrl</kbd>+<kbd>V</kbd> though. Do you see that too?

**Comment by Thomas101** [comment] 2018-01-29 11:42
This looks somewhat down to the way Microsoft have implemented Copy & Paste. If you try in the browser you end up with the following...

![screen shot 2018-01-29 at 11 38 29](https://user-images.githubusercontent.com/103586/35508641-07077f7c-04e9-11e8-8887-8505456c1097.png)

...as to why the message doesn't appear in Wavebox is a mystery. My suspicion is their doing UserAgent detection, but I could be wrong.

In Chrome if you install their browser extension, this enables copy paste through that. I'll look to see what the compatability graph of their extension looks like in Wavebox and see if that's a viable option

**Comment by blakejwc** [comment] 2018-02-07 16:36
I was frustratingly trying all key combinations today and got copy and paste to work in OneNote with the following:
paste = Ctrl + Super + v
copy = Ctrl + Super + c

Oddly, Ctrl + x works for "cut"...

**Comment by Thomas101** [comment] 2018-02-08 11:26
I think the cause of this might be the same as #546. The latest beta should fix this (3.10.1). If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel)

**Comment by Thomas101** [comment] 2018-03-20 09:21
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:21 UTC
Labels: account:microsoft, bug, extensions, in-beta
