### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by petertudorwc** [wavebox/waveboxapp#790] opened 2018-09-14 09:03 UTC
* Wavebox Version: 4.0.0
* Operating System & Version:  Ubuntu 18.04 LTS
* (Linux only) Install method: apt-get
* Account type: All open accounts suffer from this problem (Dropbox, Trello, Email)

**Expected & actual behavior**
Normal operation is expected. Random crashing is experienced whilst writing in Dropbox paper, or simply looking at the dashboard in Trello.

**Steps to reproduce**
I don't know, it appears to be random. Sometimes Wavebox crashes 10 seconds after startup and other times it seems fine. 

**Is the bug persistent or intermittent?**
It happens persistently throughout a day. I might see it crash several times in an hour, sometimes nothing for a few hours.

**Additional information**
As I'm not sure if there is a log file I can send you, I have recorded a few *.json profiles using the developer tools to try to provide more information. 

[Wavebox_profiles.zip](https://github.com/wavebox/waveboxapp/files/2382653/Wavebox_profiles.zip)

**Comment by Thomas101** [comment] 2018-09-14 10:32
Hi thanks for reporting & for the detailed info. It would be good to know a little bit more about your setup, hopefully I can reproduce the behaviour here...

* Is version 4 the first version you've started experiencing this with or did it happen before?
* How many accounts & services do you have added to Wavebox?
* Is it a 32-bit or 64-bit install of Ubuntu?
* How much ram and swap do you have on your machine?
* Can you try changing the following settings under the advanced section, each in-turn to see if one stops the behaviour?
    * Harwardware acceleration - Disable
    * Enable Sandboxing - Disable
    * Isolate Account Processes - Enable

Thanks

**Comment by petertudorwc** [comment] 2018-09-14 10:58
Hey Thomas,


So more information about my machine. I am using an Alienware R17 with an intel® Core™ i7-7820HK. It is a 64-bit machine with 32 GB of RAM and a GeForce GTX 1080, running with the driver -> nvidia-driver-396. I am running Wavebox version 4.0.0 on Ubuntu 18.04 LTS (64-bit). I was previously running Wavebox 3.x.x (most recent version) on Ubuntu 17, but I started getting some of the crash issues when I upgraded my version of Wavebox to 4.0.0. I subsequently upgraded my distribution of Ubuntu to 18.04 LTS to see if the updated software would resolve the problem. Unfortunately, the problem persisted.


The apps that I have connected to the interface are:


  1.  Hotmail email (Outlook)
  2.  Exchange email (office 365)
  3.  Outlook email (office 365)
  4.  Dropbox paper
  5.  Bitbucket
  6.  Trello
  7.  Grammarly
  8.  Evernote
  9.  Website link (PeopleHR)
  10. Expensify
  11. Website link (ePaySlips)
  12. Whatsapp


I have Grammarly linked to Dropbox paper and my email so I can get spell checking as I go. The top six from the list are the ones I use frequently. The bottom six are used less so (weekly perhaps).

I have been looking through the forums on GitHub to see if there were any solutions and have already actioned the following:
Enable Sandboxing -> Disable
Isolate Account Processes -> Enable

Hardware acceleration is currently set to Enable, but I seem to recall that I changed it from disabled because I wanted to see if that fixed the crashing problem. I will set it disabled and see if any more problems occur.

Best regards,

Peter

________________________________

**Comment by petertudorwc** [comment] 2018-09-14 11:03
Since sending my reply with all of the settings set as you have requested, it has crashed twice! Once just sitting looking at an email (I was using another program and not interacting with Wavebox) and again, 1 second after restarting Wavebox. On the third time, Wavebox is now running. 

Best regards,

Peter

**Comment by Bula** [comment] 2018-09-17 14:30
Hi - latest wavebox causes mac to freeze...    does not freeze if i dont use it... only when i use wavebox, whole macbook air freezes after a bit of time using.

need to reboot macbook air often to fix - ...  may have to stop using wavebox.

you guys seeing this?

**Comment by Thomas101** [comment] 2018-09-17 15:10
@Bula which version of Wavebox? Which version of macOS? Have you tried disabling hardware acceleration?

**Comment by Bula** [comment] 2018-09-17 15:28
@Thomas101 
v4.0

i just begin download an update...

**Comment by caschbre** [comment] 2018-09-20 18:11
I too am experiencing the random crashing after the recent upgrade. 

* Wavebox Version: 4.1.1
* Operating System & Version: Ubuntu 16.04.5 LTS x86_64
* (Linux only) Install method: sudo apt install wavebox
* Account type (if applicable): Gmail (multiple accounts w/ calendar, contacts, drive, keep), whatsapp, slack, trello

**Comment by petertudorwc** [comment] 2018-09-20 19:45
Hey Thomas,

Yes, I tried with hardware acceleration disabled and it made no noticeable difference. It has crashed many times since then, also to the point where Dropbox paper would repeatedly crash whilst I was working on a document, making it unusable. I have also noticed that Dropbox paper seems sluggish when using it through wavebox but it appears to be fine whilst using it through google chrome. I’m not sure though if this is related to the crashes.

Cheers,

Peter

Sent from my iPhone

On 17 Sep 2018, at 16:27, Thomas Beverley <notifications@github.com<mailto:notifications@github.com>> wrote:


@petertudorwc<https://github.com/petertudorwc> did you try with hardware acceleration disabled?

**Comment by Thomas101** [comment] 2018-09-21 08:08
@caschbre did you try disabling hardware acceleration? Which GPU do you have in your machine?

@petertudorwc thanks for the update - there's a couple of stability fixes coming in the next beta as well as some better crash reporting so hopefully we can get to the bottom of this

**Comment by caschbre** [comment] 2018-09-21 17:20
@Thomas101 I'm on a Dell Precision 5520. The GPU(s) for this machine are:
NVIDIA Quadro M1200 with 4GB GDDR5 dedicated memory
Intel® Pro Graphics 630

I have disabled hardware acceleration but still have random crashing. 

Are there any logs produced by wavebox that I can attach?

**Comment by sco-tt** [comment] 2018-09-24 14:37
Same here. Ubuntu 16.04 LTS 64 bit. Snap install. 4.1.0.

Slack and google apps suite.

**Comment by Thomas101** [comment] 2018-09-25 09:18
Hi, we think we might have found the root cause of this and have put a patch out in version 4.2.0. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download)

It would be great to get some feedback as to whether it's helped everyone and also if you've tried disabling hardware acceleration. A quick show of hands would be great, for example...

---

* Ubuntu 16.04 snap install
* **4.2.0 hardware acceleration enabled**: Still crashes
* **4.2.0 hardware acceleration disabled**: Fixed

---

Thanks

**Comment by petertudorwc** [comment] 2018-09-25 10:52
Hey Thomas,

So I have upgraded to wavebox 4.2.0 and I can report the following:

    Ubuntu 18.04 apt-get install
    4.2.0 hardware acceleration enabled: Still crashes
    4.2.0 hardware acceleration disabled: Still crashes

At one point it could crash when booting up, with the window being visible for only a few seconds. Other times I'll get a few minutes of use before it crashes. 

Cheers,

Peter

**Comment by caschbre** [comment] 2018-09-26 02:55
Ubuntu 16.04 apt install
4.2.0 hardware acceleration disabled: still crashes
4.2.0 hardware acceleration enabled: still crashes

**Comment by Thomas101** [comment] 2018-09-26 05:11
@petertudorwc @caschbre thanks for trying and reporting. Looks like we didn't get to the bottom of it then 😔. We are seeing the crash reports come in though so hopefully we can get to the bottom of it. At the moment it looks like the error focuses around `glibc`.

* Can you both check which version of glibc you've got installed on your machines? (`ldd --version` should bring this up).
* Do either of you have any extensions installed in Wavebox? If so, which ones?

@petertudorwc you mentioned that it quite often crashes on launch or really shortly after launch. I wonder if a clean install still produces the crash - if it does, this would narrow down the possible paths hugely. Could you give the following a go?
1. Make sure you quit the app completely
2. Move your data folder located at `~/.local/share/wavebox/` somewhere safe
3. Start the app up a few times and see if it crashes. If it doesn't crash add an account and try starting it a few times again.
4. Quit the app
5. Move your data folder back to `~/.local/share/wavebox/`

@petertudorwc @caschbre Another thing that could be worth trying - all be it as a workaround just to get you up and running again would be the snap install. This bundles a bunch of dependencies within the app itself which, if it's a dependency issue, it might alleviate the issue. The snap install will live on your system as a completely seperate install with it's own install & data - so should be safe to just take for a test drive without upsetting your apt install. You can get the latest version with `sudo snap install wavebox`.

Thanks again

**Comment by sebgar** [comment] 2018-09-26 09:38
Hi

I have the same issue on ubuntu 16.04 full patched with wavebox 4.2.0
accounts
- outlook
- team
- gmail
- facebook messenger
- 2 slack

All account are always all alive
no acceleration

**Comment by sebgar** [comment] 2018-09-26 12:12
![selection_001](https://user-images.githubusercontent.com/12963259/46079032-2ed89080-c196-11e8-8303-606a0bef4580.png)

**Comment by caschbre** [comment] 2018-09-26 14:59
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23
No extensions installed.

What I do have connected are:
* Three google (gmail, calendar, drive, etc.) accounts.
* Evernote
* Trello
* WhatsApp
* Slack

I'll take a look at the fresh install and the snap install. I was using snap at one point but it wasn't rendering custom fonts correctly at the time.

**Comment by sebgar** [comment] 2018-09-26 15:15
the random crash start about 2-3 weeks ago, before that no problem.
if it can help the investigation.
i do upgrade everytime it was notified :)

**Comment by Thomas101** [comment] 2018-09-27 14:20
Hi all and thanks again for your feedback

From the dumps it looks to be something with the dbus menu, which falls out to an error with glibc. I've put a build together which updates libcc, disabled the window toolbar menus and makes the menu from the tray icon static. It would be great if anyone could try this - if it doesn't crash we can look at re-enabling menus and see if the libcc patch itself fixes the issue.

There 64-bit build is available here [Wavebox_4_2_0_a8e8a64.tar.gz](http://wavebox.io/dl/builds/Wavebox_4_2_0_a8e8a64.tar.gz). To give it a try...
1. Quit Wavebox
2. Extract the tar
3. Run `sh wavebox.sh` from the terminal.

You should be able to use this version as usual until you find the crash or not :)

Thanks

**Comment by caschbre** [comment] 2018-09-27 16:13
> There 64-bit build is available here [Wavebox_4_2_0_a8e8a64.tar.gz](http://wavebox.io/dl/builds/Wavebox_4_2_0_a8e8a64.tar.gz). To give it a try...

Is this running separately from our original install?  If so is there an easy way to copy the configuration so all our services are already setup?

**Comment by kerneltux0** [comment] 2018-09-28 21:20
Uninstalled snap version, then installed via apt, used the tar file posted yesterday & followed Thomas101's instructions, no issues so far, all apps have been active (writing this post in Wavebox).  Will let you know if I have any issues. (crosses fingers).

**Comment by caschbre** [comment] 2018-09-29 00:03
> There 64-bit build is available here [Wavebox_4_2_0_a8e8a64.tar.gz](http://wavebox.io/dl/builds/Wavebox_4_2_0_a8e8a64.tar.gz). To give it a try...
> 
> 1. Quit Wavebox
> 2. Extract the tar
> 3. Run `sh wavebox.sh` from the terminal.

So far I've gone a full day of no crashes with this method.

**Comment by Thomas101** [comment] 2018-09-29 07:27
Hi, thanks everyone for trying those. It does look like an issue with the window menus then.

I've released v4.2.1 to the beta channel, with what I hope is a more permanent fix (not just disable the window menus). If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel).

Let me know how that goes and if you still see the crashing. Thanks again

**Comment by kerneltux0** [comment] 2018-09-29 14:13
Using the 4.2.1 beta now.  Signed-in & active on multiple apps, no crashing yet.  I'll let you know if there are any issues. :-)

**Comment by wallace11** [comment] 2018-09-30 19:41
OS: Manjaro Linux 64-bit (Kernel version 4.14)
Wavebox version: 4.2.1

Steps to reproduce a crash:
1. Add a Google account with Drive enabled.
2. Make sure that links will open in Wavebox and not in native browser.
3. Open a spreadsheet that has a couple of sheets in it (doesn't have to be HUGE).
4. Wait a few seconds.
5. Screen either turns black or the tab crashes along with the main drive window.

Happens with both acceleration on and off.

I see spikes in CPU and RAM while this happens - something in the program is probably looping until it crashes.

**Comment by sebgar** [comment] 2018-10-01 07:15
No crash with version 4.2.1-beta 

thanks :) and great job

**Comment by Thomas101** [comment] 2018-10-01 13:01
Thanks everyone, the beta fix has gone out in 4.3.0 this morning.

@wallace11 this looks a separate issue. If you enable "Isolate Account Processes" under Settings > Advanced does that help? Could you open this up in a separate issue on GitHub and I'll see if I can get to the bottom of it.

I'll close this off as hopefully it's fixed. Thanks again everyone!

**Closed by Thomas101** 2018-10-01 13:01 UTC
Labels: bug, more-info, os:linux
