### ISSUE TITLE
Flipboard Tutorial button click error

### ISSUE THREAD

**Issue by jeremiahlsmith** [wavebox/waveboxapp#594] opened 2018-02-22 19:27 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.10.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I just downloaded WaveBox yesterday and when I signed into Flip Board, I was greeted with a tutorial walk-through popup. The first one, I can continue. When I reach the second pop-up, there is an error in the console and won't disappear. 

Refused to load the script 'https://ue-test.flipboard.com/setcookie?jsonp=1&callback=jsonpcallback14' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' http://connect.facebook.net https://connect.facebook.net https://cdn.optimizely.com http://www.google-analytics.com https://jira.flipboard.com https://cdn.flipboard.com https://apis.google.com https://twitter.com https://www.google.com https://www.gstatic.com https://s.flipboard.com http://ue.flipboard.com https://ue.flipboard.com".

app-12e68457.js:80 Uncaught TypeError: Cannot read property 'promise' of undefined
    at Object.t.request (app-12e68457.js:80)
    at e.sessionInit (app-12e68457.js:13)
    at e.sessionInit (app-12e68457.js:13)
    at e.processQueue (app-12e68457.js:13)
    at e.processQueue (app-12e68457.js:13)
    at e.emit (app-12e68457.js:13)
    at e.emit (app-12e68457.js:13)
    at t.value (app-12e68457.js:54)
    at t.handleClick (app-12e68457.js:8)
    at Object.s [as executeDispatch] (app-12e68457.js:58)

I'm not sure if this is a FlipBoard issue but when attempting the same in Google Chrome, I did not get this issue (only WaveBox as far as I can tell). 

I've attached an image! 
![capture](https://user-images.githubusercontent.com/8225720/36559579-696ba84a-17dc-11e8-87c6-785c479f88b3.PNG)

**Comment by Thomas101** [comment] 2018-02-23 08:55
Thanks for reporting and for the logs. I'm seeing the same behaviour here.

It looks like if you try to dismiss the popover, then reload the page Flipboard works as expected thereafter.

After a quick glance, it looks like it's down to the way they're trying to load a script from a subdomain, yet also disallowing this with their security policy. Chrome seems to handle this failure in an okay-type way, however, Wavebox does something differently.

I'll take a deeper look and see if I can get to the bottom of it.

**Comment by Thomas101** [comment] 2018-06-08 15:01
I can't seem to reproduce this in the latest beta, so I think it may be fixed. If you're still seeing the problem though, just re-comment and I'll take another look. Thanks!

**Comment by Thomas101** [comment] 2018-09-10 10:09
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-09-10 10:09 UTC
Labels: account:container, bug, in-beta, investigate
