### ISSUE TITLE
After the latest update, sleeping services are invisible

### ISSUE THREAD

**Issue by yochaigal** [wavebox/waveboxapp#619] opened 2018-03-20 23:03 UTC
* Which version of Wavebox are you using? 
3.11.0  (Pro account)

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Arch Linux 64bit

After the latest update, sleeping services vanish when they are set to go grey on sleep:

![image](https://user-images.githubusercontent.com/817479/37687267-4009f264-2c71-11e8-9476-e34d1f1ad02c.png)

There should be Keep, Calendar & Contacts there.

**Comment by nmat** [comment] 2018-03-21 06:44
Are these the main or indexed services?

Does the same effect happens if you are not using them on the left sidebar but on the topbar?

**Comment by Thomas101** [comment] 2018-03-21 10:02
It looks like it could be a GPU glitch. Could you give the following a try to see if they come up afterwards, it might give a hint to the root of the issue...
* Restart the machine
* Under Settings > Advanced disable `Ignore GPU Blacklist` and restart
* Under Settings > Advanced disable `Hardware acceleration` and restart

**Comment by yochaigal** [comment] 2018-03-21 11:20
I don't know what you mean by main or indexed. I also don't know what you
mean by topbar!

Thomas Beverley:
I tried each setting individually; they both seem to resolve the issue.

**Comment by Thomas101** [comment] 2018-03-21 11:22
Okay, it's probably down to a driver issue then. I would set up as below...

* `Ignore GPU Blackist` (disable)
* `Hardware acceleration` (enable)

**Comment by yochaigal** [comment] 2018-03-21 12:02
That's how I have it set.
FWIW, I did not have this issue before the most recent update.
I have an Intel GPU (X1 Carbon 4th Gen).

**Comment by Thomas101** [comment] 2018-03-21 14:24
This version of Wavebox is running a newer version of Chromium. Google maintains a [list](https://chromium.googlesource.com/chromium/src/gpu/+/master/config/software_rendering_list.json) of GPU's & drivers that they disable certain features for which has probably been updated in this version.

For the most part, this works, but sometimes it results in rendering glitches like the one you've seen. Manually overwriting the list normally fixes the problem though!

**Comment by yochaigal** [comment] 2018-03-21 18:32
Actually, this issue seems to have come back. I've seen it in these
scenarios:

   - Ignore GPU Blackist (disable)
   - Hardware acceleration (enable)

Or:

   - Ignore GPU Blackist (enable)
   - Hardware acceleration (enable)

**Comment by Thomas101** [comment] 2018-03-22 09:12
What happens if you disable hardware acceleration completely? Does it still show up?

**Comment by yochaigal** [comment] 2018-03-22 12:28
The problem disappears.

**Comment by yochaigal** [comment] 2018-03-22 12:43
Actually no it happens again with hardware acceleration turned off as well.

**Comment by Thomas101** [comment] 2018-03-26 15:25
It's definitely some kind of GPU related issue. There's quite a bit of discussion on this thread for atom https://github.com/atom/atom/issues/10714 (which uses the same underlying stack).

There seems to be some kind of consensus there that it's an issue with Intel graphics drivers. Their suggestion is to change GPU acceleration method from SNA to UXA. There's some info [here](https://wiki.archlinux.org/index.php/Intel_graphics#SNA_issues) on doing that. Might be worth giving that a try...

**Comment by bbluemel** [comment] 2018-03-27 12:33
@Thomas101 I've been getting this too (randomly) recently, in Windows.

Toggling the "Collapse sidebar services when account is inactive." off and on again seems to restore their visibility.

I haven't noticed them disappearing if the option is turned off, but without being able to completely reproduce the issue effectively it hard to say what causes them to disappear.

Given that it's happening for me on Windows and @yochaigal in Linux it seems rather unlikely to be GPU driver related.

**Comment by Thomas101** [comment] 2018-03-28 08:36
@bbluemel I'm starting to agree with you. We've had a report in for macOS too. Our suspicion was a driver issue as we'd seen something similar around 12 months ago with an older version of Chromium. 

We're still struggling to get a reproducible case which shows it a the moment so we can debug. Has anyone noticed any steps that cause this to happen? For example, switching accounts quickly, or with keyboard shortcuts etc?

With driver issues looking more unlikely, I wonder if it could be a chromium rendering bug (3.13.0 ships with a newer version of chromium and the sporadicness of it suggests so). If we try pushing the component down onto the GPU it may fix this and confirm that suspicion. Would you be able to give this a try?

1. Go to Settings > Advanced
2. Click Main Window Custom CSS
3. Paste the following into the modal and press save...
```css
.WB-SidelistItemMailboxServices {
  transform: translate3d(0,0,0);
}
.WB-SidelistItemMailboxServices * {
  transform: translate3d(0,0,0);
}
```

You shouldn't see any noticeable effect from this, but hopefully might fix it

**Comment by bbluemel** [comment] 2018-03-29 11:02
@Thomas101 had that set for 24 hours now and haven't seen the icon disappear yet... though for me it was random, so not sure if it's fixed, or if it just hasn't reappeared yet.  Will post back if/when it does.

**Comment by Thomas101** [comment] 2018-03-29 11:27
@bbluemel thanks. I've put a patch in for the next release - hopefully that is enough to solve this

**Comment by Thomas101** [comment] 2018-04-09 14:25
Hi, we’ve just released this to the beta channel of Wavebox in version 3.13.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2018-04-16 10:11
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-04-16 10:11 UTC
Labels: bug, in-beta, investigate, sporadic/hard to reproduce
