### ISSUE TITLE
Allow wave to save websites username and password

### ISSUE THREAD

**Issue by karsyboy** [wavebox/waveboxapp#37] opened 2017-04-08 23:23 UTC
it would be nice if wavebox was able to save added wbestites usernames and passwords and auto login.

**Comment by jacksarick** [comment] 2017-04-10 03:21
What do you mean by this? Are you having trouble staying logged into your inbox?

**Comment by Thomas101** [comment] 2017-04-10 06:48
You will get logged out of session periodically in the same way that you do in the browser. We're looking to add keychain (osx) or similar on other platforms so you get the same experience as what you do with your web browser

**Comment by Thomas101** [comment] 2017-06-22 13:43
![](https://github.trello.services/images/mini-trello-icon.png) [Password storage](https://trello.com/c/uc5MgQ62/231-password-storage)

**Comment by nmat** [comment] 2017-11-18 01:04
I am using various methods of auth here with different services and all of them save the login and password. @karsyboy could you provide more information of what exactly you mean here and if there is a specific service that you have problems with regarding saving password and login?

At the moment I can't reproduce it.

**Comment by Thomas101** [comment] 2018-02-08 09:25
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2018-03-20 09:22
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:22 UTC
Labels: feature, in-beta
