### ISSUE TITLE
Slack Account Reports unread count, despite all read

### ISSUE THREAD

**Issue by jcarroll-mediafly** [wavebox/waveboxapp#7] opened 2017-04-05 21:35 UTC
* Which version of Wavebox are you using? 
3.1.2

* Which Operating System are you using?
macOS Sierra 10.12.4

Just simply logged into a slack account and always reporting unread count

**Comment by Thomas101** [comment] 2017-04-06 07:44
Hi, is this reporting an unread number or the unread dot?

**Comment by raguay** [comment] 2017-04-06 12:16
Me too. A slack channel has a dot with a 1 for one unread message, but I've read everything.

macOS 10.12.5 Beta (16F43c)
WaveBox Version: 3.1.2

**Comment by Dejw4g** [comment] 2017-04-06 12:41
I have the same problem, it says I have 27 unread messages, but I've read everything.

**Comment by Thomas101** [comment] 2017-04-06 12:42
Thanks, we'll dig a bit deeper to see what's happening here

**Comment by Kachilero** [comment] 2017-04-06 18:36
Happening for me as well - Version 3.1.2 on Mac 10.12.4

**Comment by asunifran** [comment] 2017-04-07 07:44
Same here, just on slack accounts. - Wavebox 3.1.2 on Windows 10

**Comment by cympfh** [comment] 2017-04-07 08:57
Some slack accounts (not all) have this problem.

OS X El Captaion 10.11.6
Wavebox 3.1.2
Electron/1.6.5 Chromium/56.0.2924.87

**Comment by benvddriessche** [comment] 2017-04-07 13:51
I had the same issue, "solved" it by using the SHIFT+ESC combo a couple of times. This forces Slack to mark all messages as read. The problem did not come back for me after that.

**Comment by Thomas101** [comment] 2017-04-07 15:10
Just about to look into this, would be good to know if the shift+esc trick works for anyone else?

**Comment by Kachilero** [comment] 2017-04-07 15:12
I worked for me, although I had to restart Wavebox and I'm still not seeing unread counts for email.

**Comment by Thomas101** [comment] 2017-04-07 15:18
@Kachilero are you using Gmail/Inbox/Outlook/Office365? If Gmail/Inbox have you tried right clicking on the account, going to settings and changing the unread mode?

**Comment by raguay** [comment] 2017-04-07 15:20
It worked for me. It hasn't messed up yet. Keeping an eye on it.

**Comment by Kachilero** [comment] 2017-04-07 16:46
@Thomas101 I am using gmail ( one account is a personal, the other a business, ) and just tried as you suggested. They were both set to 

* Show unread badge
* Add unread messages to app unread count
* Show notifications

Turning those off and then on again did not resolve the issue.

However, the slack issue does seem to be resolved.

**Comment by urfolomeus** [comment] 2017-04-07 17:16
At the risk of plus-1-ing ... I was seeing the same and SHIFT+ESC worked for me (so far at least).

```
Wavebox   3.1.2
Electron  1.6.5
Chromium  56.0.2924.87
Mac OSX   10.12.3
```

**Comment by Thomas101** [comment] 2017-04-08 09:15
@kachilero sorry i was talking about the unread mode drop down a little bit further down. I've added a [KB article here](https://github.com/wavebox/waveboxapp/wiki/KB:-Google-Unread-Counts) which gives some more in depth instructions

**Comment by Thomas101** [comment] 2017-04-10 15:20
Hi, has everyone been able to resolve this by using `shift+esc`?

If not, can you update to the newly released 3.1.3. Wavebox will autoupdate shortly or if you want to get it sooner you can either re-launch Wavebox to trigger an autoupdate or redownload from https://wavebox.io/download.

Once it's updated can you go to View > Developer Tools and then click on the console tab. Then enter `window.waveboxDebug.flags.slackLogUnreadCounts = true`. Once you've done this right click on the account in the left toolbar and then click Resync. You should see some logs come out with some information about the data returned from slack. Each channel should have some info about it...

```js
{
      "name": "random",
      "mention_count": 0,
      "unread_count": 16
    }
```

The unread_count indicates new messages where you're not mentioned, where as the mention_count indicates places where you've been @thomas101 mentioned. Do you have anything with numbers here that shouldn't be

Thanks

**Comment by asunifran** [comment] 2017-04-12 15:27
shift+esc solved it for me.

**Comment by Thomas101** [comment] 2017-04-14 10:12
I've added some more fixes into version 3.1.4, so hopefully this should be looking good now. Going to close this issue off but if you do have any more problems just re-comment and I'll take another look.

Wavebox should update automatically after a while, but if you want to hurry it up, just restart the app and it will re-check

**Comment by jaredswarts55** [comment] 2017-04-27 15:37
This is now happening again for me. Shift + Esc use to work but doesn't appear to work anymore. I am on windows 10.

**Comment by Thomas101** [comment] 2017-05-02 09:54
@jaredswarts55 is it showing a count or just the unread dot indicator? I'll see if I can add some debug info into the app to see what it thinks is unread

**Comment by jaredswarts55** [comment] 2017-05-04 14:19
@Thomas101 It was just unread dot indicators. Must have had a keyboard issue at the time because on a different machine I was able to clear the indicator with shift+esc.

**Comment by adrianaoun** [comment] 2017-06-11 20:03
i can repro this - dot indicators - 3.1.8 on mac

shift-esc doesn't help.

**Comment by Thomas101** [comment] 2017-06-12 14:41
@adrianaoun what are the steps to reproduce the phantom dot?

**Comment by adrianaoun** [comment] 2017-06-12 14:42
My slack has it 100% of the time

So reproving steps are:
-login to slack
-have no unread messages

**Comment by tomsautelle** [comment] 2017-06-16 07:40
I have the same issue, Windows 10, version 3.1.8
all badge/notification settings enabled.

I have a permanent dot despite everything being read - shift-esc did nothing.

**Comment by Thomas101** [comment] 2017-06-16 08:39
We’ve got a permanent fix together for this which is due to land in the next release early next week

**Comment by MikePelton** [comment] 2017-07-26 11:15
So here we are at July 26th and I'm still seeing that bug - Windows 10. Anyone else?

**Comment by robin31** [comment] 2017-10-31 15:49
Still having this in 3.4.0

**Comment by jcarroll-mediafly** [comment] 2017-11-16 19:05
issue still present in 3.5.0

**Comment by Thomas101** [comment] 2017-11-17 11:31
@robin31 @jcarroll-mediafly it would be good to have some more info...

1. Are you seeing an unread number or just the unread activity dot?
2. If you try right clicking on the account in the left and picking `Resync` does the unread go away or stay?
3. In the slack tab if you try pressing <kbd>Shift</kbd>+<kbd>Esc</kbd> and then `Resync` does this make any difference?

**Comment by jcarroll-mediafly** [comment] 2017-11-17 14:48
1. Just the activity dot, but annoying enough that I'm constantly switch to the application to see if I actually need to read something.
2. Sometimes it goes away. Sometimes it goes away comes back in a few seconds. Sometimes no change and the dot persists.
3. I haven't had luck with Shift+Esc. Not sure if anything should be refreshing, there is no feedback when I hit that keycombo.

I'm running on Macos Sierra 10.12.6 if that helps

**Comment by Thomas101** [comment] 2017-11-21 11:38
@jcarroll-mediafly can you try the following...

Go to View > Developer > Wavebox Developer Tools. You'll get a window appear. Can you click on the console tab and then paste... `window.waveboxDebug.flags.slackLogUnreadCounts = true`. 
![screen shot 2017-11-21 at 11 34 30](https://user-images.githubusercontent.com/103586/33070465-fba61cde-ceaf-11e7-8c7d-d7815516240d.png)

Next, right click on one of the affected accounts and hit resync. You'll see a long log of all the slack channels come out. Can you take a look to see any have `has_unreads:true`

![screen shot 2017-11-21 at 11 35 27](https://user-images.githubusercontent.com/103586/33070531-3365a9dc-ceb0-11e7-8945-1a28e78d1089.png)

These are the probable cause of what's showing the unread dot. Can you send me a screenshot of any of those (obviously blocking out any sensitive info)? It might give some clues as to what's causing the unread count

**Comment by jcarroll-mediafly** [comment] 2017-11-21 14:42
Next time I see it I'll try those steps. As luck would have it, its behaving better atm

**Comment by Thomas101** [comment] 2017-11-22 09:05
Okay, well I'll close this off again then, but just recomment if it comes back up. It could be something with Slack API, they've been having a few problems lately - their system status page is full of issues from the last few weeks

**Closed by Thomas101** 2017-11-22 09:05 UTC
Labels: bug

**Comment by robin31** [comment] 2017-11-22 10:36
Hi @Thomas101 ,

I've done the steps with the `window.waveboxDebug.flags.slackLogUnreadCounts = true`

I got this in my console:
```
[SLACK:UNREAD] call 34a067bd-36bb-48d7-8680-7faf400f65d8
mailboxes.js:23 [SLACK:UNREAD] start 34a067bd-36bb-48d7-8680-7faf400f65d8
mailboxes.js:35 Object {ok: false, error: "invalid_auth"}
Promise.resolve.then.then.catch @ mailboxes.js:35
mailboxes.js:23 [SLACK:UNREAD] error: 34a067bd-36bb-48d7-8680-7faf400f65d8 Object {ok: false, error: "invalid_auth"}
```

After seeing the error I removed the slack account and added it again. Now its working like intended again.

**Comment by Thomas101** [comment] 2017-11-22 10:51
@robin31  It could be that slack rotated tokens for some reason. I'll look to see why wavebox didn't report it as an authentication issue though!

**Comment by jcarroll-mediafly** [comment] 2017-11-22 15:09
Ya, I tried your steps and each time I resync the out put of the logs says everything is read. Sometimes the dot will come back, and I can see there are no new unread channels. I have slack app and web browser up to confirm, nothing showing up there so no new messages truly. So I'll hit resync again and get same results, nothing marked as unread. Dot may or may not come back.

I dunno. I've been pretty aggressive hitting resync because I want the dot to clear, otherwise I feel I'm missing conversations...oh well...

**Comment by Thomas101** [comment] 2017-11-23 09:27
@jcarroll-mediafly we've just released a new update 3.6.0, would you be able to give it a try with this? If you don't see the dot clearing could you try re-adding your slack account to see if that makes a difference? Thanks

**Comment by jcarroll-mediafly** [comment] 2017-11-24 15:22
cool, will update!

**Comment by jcarroll-mediafly** [comment] 2018-02-12 19:40
Felt like its gotten worse. I set the flag window.waveboxDebug.flags.slackLogUnreadCounts = true and resync'd to inspect for any counts that were unread.

All the dm_count were 0, all the has_unreads were false, and all the mention_count were 0.

I resync'd 3 times and the dot came back each time. I took the output that the slackLogUnreadCounts spit out and diffed all 3 of them. Exact same output each time.

Running version 3.10.0

Not sure if any of this actually helps. Its not end of the world, simply annoying.

**Comment by MLDSBigGuy** [comment] 2018-06-03 12:35
Same problem for me too !! All read messages are still marked as unread.

**Comment by paragbaxi** [comment] 2018-07-05 05:12
have the same issue on mac slack 3.2.0

**Comment by paragbaxi** [comment] 2018-07-18 14:17
web slack doesn't show any unread messages count. mac slack shows 6. when i have 1 new legit message, mac slack shows 7.

**Comment by Czarto** [comment] 2018-09-04 15:12
Unsure if this is the same problem, but my red dot problem came down to having an old inactive workplace in my slack account, that unexpectedly had some activity. Even though I wasn't actively logged into the account, that's the account that was causing the red "unread" dot on my desktop icon...

**Comment by smshashi** [comment] 2019-03-21 11:06
I had the same problem, but even after pressing SHIFT+ ESC (to clear unread messages) the issue did not get solved. However I then realized that I had subscribed to multiple channels which I was not using actively. After removing myself from those channels, the unread icon went away!!

**Comment by localjo** [comment] 2020-05-03 11:24
Shift + esc doesn't appear to work for thread replies in workspaces that aren't on paid plains. :-/ I've got an unread thread count that I can't get rid of.

**Comment by Tomaszu97** [comment] 2020-05-18 13:00
I have the same problem and its really annoying! shift+esc does not work, you have to exit whole workspace and come back to fix it! running on windows btw

**Comment by jcalvillo** [comment] 2020-05-19 12:15
- same issue (**threads** 3 new replies) but list is empty
- `shift`+`esc` does not fix it (mark all as read)
- `shift` + `command` + `R` does not fix it (force reload)

I think this is a **free tier** workspace. Perhaps the issue is that there _are actually 3 unread replies in my threads_ but I cannot see them because they are too far back in my history (?)

**Comment by davidpesce** [comment] 2020-06-05 12:06
I have the same issue in mac desktop app. There's a thread (free tier) that I never read and is no longer accessible.

**Comment by trishchuk** [comment] 2020-07-15 13:58
Same issue.

- Threads — 1 new reply; list is empty;
- Clear/Reload does not help;
- Win10 app/Web/Android — all the same.

**Comment by quantumdotdot** [comment] 2020-09-25 04:30
I just had the same issue with a thread that was no longer accessible. Removing and re-adding didn't work, but shift+esc did.

**Comment by Thomas101** [comment] 2020-09-25 07:48
@quantumdotdot which version of Wavebox are you using?

**Comment by rajdesai-icix** [comment] 2021-07-08 12:53
> At the risk of plus-1-ing ... I was seeing the same and SHIFT+ESC worked for me (so far at least).
> 
> ```
> Wavebox   3.1.2
> Electron  1.6.5
> Chromium  56.0.2924.87
> Mac OSX   10.12.3
> ```

That worked for me. Thanks

**Comment by sam1am** [comment] 2022-03-28 20:50
Having this issue on 10.99.46.2 

M1 Mac 

Shift+Esc does not work 

The console command returns an error: 
<img width="538" alt="Screen Shot 2022-03-28 at 2 50 20 PM" src="https://user-images.githubusercontent.com/127555/160484813-03888023-5976-4228-b83d-cfc2eb9e473f.png">
