### ISSUE TITLE
Crash when installing Markdown Here extension 

### ISSUE THREAD

**Issue by pedrov** [wavebox/waveboxapp#641] opened 2018-04-05 09:16 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.13.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.12.6

[CrashReport](https://github.com/wavebox/waveboxapp/files/1879326/CrashReport.txt)

**Comment by nmat** [comment] 2018-04-05 13:11
@pedrov is this a new install of wavebox or is it from a upgrade from any version?

**Comment by pedrov** [comment] 2018-04-05 13:30
Hi @nmat. It is a upgrade.

**Comment by nmat** [comment] 2018-04-06 07:09
I will test this at home later on. However I do not have a mac located anywhere near where I am now so going to check to see if its possible to reproduce. Have you managed to get other extensions installed?

**Comment by Thomas101** [comment] 2018-04-06 07:55
Hi @pedrov,

From the crash report it looks like something's been freed before it should have been. Would be good to try a few other things so we can try to isolate it.

1. If you try to install any of the other extensions (e.g. Trelabels) do you have a crash with this too?
2. Does trying to install MarkdownHere a second time produce a crash
3. Where have you installed Wavebox? Is it under the main applications folder (e.g. `/Applications`) or your user applications (e.g. `/Users/pedrov/Applications`) or somewhere else?

As a side node from that, we've changed the way extensions are downloaded in the next release (https://github.com/wavebox/waveboxapp/commit/d3bc55505f3c27148ef4caad340337cf24078463). The current method is a bit messy and it's been on our list to tidy that up. Looking at the crash report I suspect this change may fix the problem

**Comment by Thomas101** [comment] 2018-04-16 10:10
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-04-16 10:10 UTC
Labels: in-beta
