### ISSUE TITLE
Gmail: Unable to download attachments

### ISSUE THREAD

**Issue by tnaseem** [wavebox/waveboxapp#803] opened 2018-09-25 11:52 UTC
* Wavebox Version: 4.1.0
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail

**Expected & actual behavior**
When hitting the download link of a file attachment, the file should download to the machine. In the previous version, I also received a notification that the attachment was successfully downloaded.

In this latest version, although it appears that it's doing something (I can see the progress bar moving across the top), no download occurs.

Selecting the attachment will display it inline (a PDF for instance), but hitting the download link in the top right also doesn't work.

I have to resort to opening Gmail in Chrome to download the attachment.

**Steps to reproduce**
Hit the download link on the attachment in the email.

**Is the bug persistent or intermittent?**
Always occurs.

**Screenshots**

![snag_2b5d3ef](https://user-images.githubusercontent.com/1317345/46012645-fd23e300-c11d-11e8-978b-9909c71b6fbc.png)

**Additional information**

**Comment by tnaseem** [comment] 2018-09-25 11:59
Just noticed there's a version 4.2.0. However, this problem still occurs in this latest version.

**Comment by Thomas101** [comment] 2018-09-26 04:15
Hi, thanks for reporting and trying with the update! I'm having a little bit of trouble reproducing the same here. It would be great to have some extra info...

* Have you got more than one Gmail account, do all of them exhibit this behaviour or just one?
* Do you have extensions installed, if so which ones?
* Is this with a personal gmail (e.g. @gmail.com) or a corporate one (e.g. @mycompany.com)
* If you go to `Settings` > `Download` can you send a screenshot of the Download section in case it's a setting combination we're not testing.
* Have you tried downloading anything from something apart from Gmail? Does this download or fail silently too?

It might be worth trying re-adding the Gmail account and having a go with that one to see if there's any difference - although this is just a shot in the dark

**Comment by tnaseem** [comment] 2018-09-26 05:17
Many thanks for getting back to me. It is a strange one, indeed.

I've just tried it on my other accounts (Google Drive, Harvest) and the downloads don't work there either, so it's not just Gmail.

So, in answer to your questions:

> * Have you got more than one Gmail account, do all of them exhibit this behaviour or just one?
Just the one Gmail account.

> * Do you have extensions installed, if so which ones?
Grammarly for Chrome (14.865.1815-1.1.0)
Play Midnight for Google Play Music (3.2.1-1.0.0)

Uninstalled and restarted but the problem persists.

> * Is this with a personal gmail (e.g. @gmail.com) or a corporate one (e.g. @mycompany.com)
Personal Gmail

> * If you go to `Settings` > `Download` can you send a screenshot of the Download section in case it's a setting combination we're not testing.

![snag_667edf5](https://user-images.githubusercontent.com/1317345/46058264-4f144980-c1ae-11e8-9096-2e53920a0e38.png)

> * Have you tried downloading anything from something apart from Gmail? Does this download or fail silently too?
As above: Google Drive, Harvest. Fails silently, as before.

> 
> It might be worth trying re-adding the Gmail account and having a go with that one to see if there's any difference - although this is just a shot in the dark
Removing and re-adding didn't work, unfortunately.

**Comment by Thomas101** [comment] 2018-09-26 05:53
Okay, looks like the download handler. Can you try these two...

1. Under settings > Downloads, re-click the "Select Location" button and re-pick where you want downloads to go. Do they work now?
2. Same place, change the toggle next to "Always ask download location" so it's on, does that work?

Thanks

**Comment by tnaseem** [comment] 2018-09-26 06:07
Findings below... but these only worked the first time I tried it in each case:
 
> 1. Under settings > Downloads, re-click the "Select Location" button and re-pick where you want downloads to go. Do they work now?

If I selected the same location, it didn't work. But when I tried a different one (Desktop), it downloaded the file with a notification.

> 2. Same place, change the toggle next to "Always ask download location" so it's on, does that work?

This opened up the file save location dialogue and allowed me to save the file.

Now, when I set it back to the Downloads folder, it stopped working again. So, I thought it was something to do with that location. So, repeated the above steps. This time they didn't work (ie. failed silently).

I then swapped to a totally new folder (Documents), and it downloaded fine. Hit the download button again to see if it would prompt me to overwrite the file (or save a duplicate). Again, it failed silently (as before).

**Comment by Thomas101** [comment] 2018-09-26 06:40
That's weird. I've just had a try on macOS and it looks like it works fine. I'll check on windows shortly to see if it's the same.

Can you check which version of Windows 10 you have installed? Some info on [how to do that here]( http://techspeeder.com/2015/11/24/find-which-build-version-of-windows-10-your-computer-has-installed/).

Also, in the case where it fails (e.g. download and then try again after 30 secs) can you check the Downloads directory to see if the download is there shortly after clicking download - just in case it's the notification that's failing to come up.

**Comment by tnaseem** [comment] 2018-09-26 06:54
> That's weird. I've just had a try on macOS and it looks like it works fine. I'll check on windows shortly to see if it's the same.

On MacOS it appears to work fine here too.

> 
> Can you check which version of Windows 10 you have installed?

Windows 10 Version 1803 (OS Build 17134.285)
 
> Also, in the case where it fails (e.g. download and then try again after 30 secs) can you check the Downloads directory to see if the download is there shortly after clicking download - just in case it's the notification that's failing to come up.

Nothing in the downloads folder when it failed. In each case it fails, the progress bar, that runs across the top, gets to near the end of the window, but nothing happens after that.

Having said all that, I can't make it fail again (even after that delay). Pretty sure it won't last :(

**Comment by Thomas101** [comment] 2018-09-27 11:11
Still having trouble trying to reproduce it here, macOS and Windows. Downloads seem to work pretty reliably. I wonder if it's something to do with the download itself...

* What kind of size is the pdf?
* Does it fail with any file or is it just one in particular?
* Can you reproduce the problem with any other file type (e.g. image)?
* Are you using gsuite (e.g. a @mycompany.com email) or personal (e.g. @gmail.com) account?
* When you try it in harvest are you ever able to reproduce the behaviour there?
* Which antivirus are you using?

**Comment by tnaseem** [comment] 2018-09-27 12:50
> Still having trouble trying to reproduce it here, macOS and Windows. Downloads seem to work pretty reliably. I wonder if it's something to do with the download itself...

Stupid thing now is that I can't reproduce the issue any more either! Will keep trying...

> 
> * What kind of size is the pdf?

Various sizes. The 'test' one I was trying was 5.2MB. Others were a few hundred k.

> * Does it fail with any file or is it just one in particular?

It happened with any file attachment I tried and files from other services (Harvest, for instance).

> * Can you reproduce the problem with any other file type (e.g. image)?

If I can make it happen again, I'll try this. Can't remember what file types I tried other than the PDF's.

> * Are you using gsuite (e.g. a @mycompany.com email) or personal (e.g. @gmail.com) account?

Personal Gmail account.

> * When you try it in harvest are you ever able to reproduce the behaviour there?

Yes. Tried to download invoices (PDF) from there and it also failed.

> * Which antivirus are you using?

Malewarebytes Premium (v3.5.1), but it didn't flag anything. Next time it occurs, I'll turn it off and try again.

**Comment by Thomas101** [comment] 2018-10-01 11:50
Thanks, as regards the antivirus I was wondering if it scanning the download was somehow interfering with it. Just as an avenue of investigation.

As we can't seem to reproduce it and it's fixed itself your end, I'll close this off for now, but if you start seeing it again just re-open and we'll see if we can get to the bottom of it

Thanks

**Closed by Thomas101** 2018-10-01 11:50 UTC
Labels: account:google, bug, more-info
