### ISSUE TITLE
[Feature Request] Wavebox Launcher

### ISSUE THREAD

**Issue by ferenczy** [wavebox/waveboxapp#1005] opened 2019-04-04 13:43 UTC
Every version of Wavebox installed has a different executable, because every version is installed into a separate directory whose name contains a version number, for example `"C:\Users\<username>\AppData\Local\wavebox\app-4.9.3\Wavebox.exe"`.

Many things in Windows are tied to an application's executable, for example firewall rules, systray icon configuration (show or hide) and also some 3rd party applications, for example DisplayFusion which modifies behavior of windows of other applications (additional window buttons, etc.).

With every new version of Wavebox, which are released several times a week (which is great!), I have to reconfigure everything. It would be great if Wavebox has some shim or launcher which would be on a stable location, e.g. `"C:\Users\<username>\AppData\Local\wavebox\Wavebox.exe"` and the only thing it does is to launch the newest currently installed version of Wavebox. It wouldn't execute it as a separate process but instead "inside" itself, so in _Task manager_, it should appear like the launcher is running and all applications and configurations tied to a particular executable path would still work even if a new version is installed.

I hope it's understandable :)

**Comment by nmat** [comment] 2019-04-04 16:41
Duplicate of: https://github.com/wavebox/waveboxapp/issues/997

**Comment by ferenczy** [comment] 2019-04-04 23:19
You're right, I didn't notice it, sorry. I think we can close this one.

**Closed** 2019-04-05 08:55 UTC
