### ISSUE TITLE
Mailto links don't open with sleeping accounts

### ISSUE THREAD

**Issue by phahulin** [wavebox/waveboxapp#570] opened 2018-02-07 14:34 UTC
* Which version of Wavebox are you using?
3.10.0

* Which Operating System are you using?
Xubuntu 16.04

Hi,firstly thank you for a great app!
Now the question: is it possible to register wavebox as default mail client to open mailto links? I tried to setup `/opt/Wavebox/wavebox --mailto=%s` in preferred applications but clicking on a mailto link just opens the last used profile in wavebox, no "from" address selection, no message with pre-filled "to", "subject"... I have 3 gmail accounts and 1 slack.

**Comment by Thomas101** [comment] 2018-02-08 10:17
Hi, if you drop the `--mailto=` prefix and just run `/opt/Wavebox/wavebox %s` that should work

**Comment by phahulin** [comment] 2018-02-08 20:16
Nope, I get the same result - last used profile opens (can even be slack)

**Comment by Thomas101** [comment] 2018-02-09 08:40
It's probably worth checking that the link handler is working first then. If you just run `/opt/Wavebox/wavebox mailto:user@email.com` does that bring up the email picker?

If that's working how are you configuring the preferred application? Is it through a config file or using an app?

**Comment by phahulin** [comment] 2018-02-09 08:51
Ok, I should have used it in the following way: `/opt/Wavebox/wavebox mailto:%s` (keep `mailto:`). Now it works if I select an account that wasn't sleeping. If it was sleeping, account page opens, refreshes but "compose new message" window doesn't appear.

**Comment by Thomas101** [comment] 2018-02-13 10:13
That looks like a bug. I'll see if we can get a fix in!

**Comment by Thomas101** [comment] 2018-03-09 15:23
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by phahulin** [comment] 2018-03-10 11:03
I tried beta and it seems to be working working, great!

**Comment by phahulin** [comment] 2018-03-12 09:35
Though now it looks like sometimes wavebox just quits. I don't see any errors in syslog, are there any other wavebox logs or debug mode? It's probably unrelated to this issue, but I could open a new one.

**Comment by Thomas101** [comment] 2018-03-12 12:23
We can stick to it here if you like. Would be good to know a little bit more so I can try and reproduce my end...
1. How many google accounts do you have added?
2. When you open the `mailto:` link do you see the account picker or does it just go straight into the account?
3. Is the account sleeping or awake when it crashes? (Or doesn't matter)
4. Is there any difference between opening a link with Google Inbox/Gmail
5. Do you have any extensions installed?
6. Does it happen every time you try to open?

**Comment by phahulin** [comment] 2018-03-12 14:18
Sorry, I was not too clear - this happens in background, when I'm not doing anything with wavebox. I just look at status bar and wavebox is not there anymore, check with `ps aux` or `htop` and see that wavebox is not running. I restart it, it runs for a while, I receive notification, can open the app, everything looks ok, but then it stops again. Not sure what might be causing it to quit.

I'm running xubuntu 16.04, have 3 gmail accounts and 1 slack.

**Comment by Thomas101** [comment] 2018-03-13 09:47
Ah, I think this was related to #606 and #608. If you update to 3.10.5 this should be fixed now :)

**Comment by Thomas101** [comment] 2018-03-20 09:23
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:23 UTC
Labels: bug, in-beta
