### ISSUE TITLE
Wavebox does not auto restart after extension is uninstalled

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#759] opened 2018-08-14 16:20 UTC
* Wavebox Version: [e.g. 3.0.0]
3.14.10beta

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows10 
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
Gmail Extension

**Expected & actual behavior**
Some information about what you expect to happen and what actually happens.

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?
try uninstalling the extension listed below.

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?
This is the first time I have uninstalled an extension, don't know

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**
After selecting to uninstall the Gmelius extension a message appeared that the extention would be uninstalled after a Wavebox restart.  There is a restart option in the screen and it was selected, however, a Wavebox restart did not occur.  It was restarted manually and the extension was no longer installed.

**Comment by Thomas101** [comment] 2018-08-15 07:54
This is by design. When closing the settings screen you either have to click close (to just close the settings) or click the restart button that's highlighted in blue to restart the app. We don't want to unexpectedly restart the app without explicit consent as it looks buggy.

**Closed by Thomas101** 2018-08-15 07:54 UTC
