### ISSUE TITLE
Crash when loading heavy web apps

### ISSUE THREAD

**Issue by wallace11** [wavebox/waveboxapp#826] opened 2018-10-11 07:37 UTC
* Wavebox Version: 4.2.1 beta
* Operating System & Version: Manjaro Linux 64-bit (Kernel version 4.14)
* (Linux only) Install method: AUR

**Steps to reproduce**
1. Add a Google account with Drive enabled.
2. Make sure that links will open in Wavebox and not in native browser.
3. Open a spreadsheet that has a couple of sheets in it (doesn't have to be HUGE).
4. Wait a few seconds.
5. Screen Tab either turns black or the tab crashes along with the main drive window.

**Is the bug persistent or intermittent?**
The bug appears 90% of the times when interacting with resource-demanding web apps. It isn't limited to only Google Spreadsheets, but it's the easiest and simplest way to reproduce it.

**Additional information**
Settings turned on/off, yet problem persists:
- Advanced > Ignore GPU Blacklist
- Advanced > Hardware acceleration
- Advanced > Isolate account processes
- Advanced > Enable Sandboxing

**Comment by Thomas101** [comment] 2018-10-12 08:27
Thanks for reporting. I wonder if this is somehow related to #816.

If you head into Settings > Debug and click the task monitor button can you send a screenshot of the window that appears? Can you also send how much ram and swap you've got configured, I'll see if we can try to narrow this down

**Comment by wallace11** [comment] 2018-10-16 02:33
That is just so weird.
The bug used to appear almost all the time and I could reproduce it quite reliably with the procedure mentioned above. However, since you asked me to check the task monitor it'd ALWAYS happen off-camera. I've been trying to catch that happening more than a couple of times but the bug just won't appear while the task manager is open.
I guess I'll just have to keep trying...

**Comment by Thomas101** [comment] 2018-10-16 09:48
If you close the task manager I'm guessing it happens in a reproducible way? If that is the case maybe get it to state that would normally allow you to reproduce it and send a screenshot of the task manager before reproducing. Then reproduce the issue, re-open the task manager and send a screenshot of that?

My hunch is that the process sharing has perhaps ballooned in some way that it shouldn't have.

**Comment by wallace11** [comment] 2018-10-20 20:11
Just reporting that it happens a lot less often in v4.3.1.
Actually, it hardly became reproducible (but will happen eventually).

**Comment by Thomas101** [comment] 2018-11-10 08:03
Thanks for the update! The only thing that I can think of that was changed in 4.4.0, is that we've started limiting the number of concurrent tabs that load at once. By default, there's a soft limit on the number of CPU cores on your machine.

Just before I close it off, it would be great to confirm that - just so we can get a feel of the root cause of the issue. Would you be able to give the following a try?

* Go to Settings > Advanced
* Change the `Concurrent service load limit` from `auto` to `unlimited`
* Restart Wavebox and see if the crashes start to re-appear

Unlimited will make it behave in the same was as it did in 4.3.0 and lower.

**Comment by wallace11** [comment] 2018-11-15 12:18
I reverted all my changes, including `Concurrent service load limit`, `Isolate account processes` and `Enable Sandboxing`, but I just cannot recreate this bug anymore. 
Nothing changed on my system except for a couple of system updates and point-kernel upgrades, so this is weird.
Maybe other changes actually improved memory handling?

**Comment by Thomas101** [comment] 2018-11-19 11:01
Thanks for trying those out. The only thing I can think of is that one of the libraries we use has been updated whilst doing system updates. Perhaps this has had the knock-on effect of resolving the problem.

I'll close this off for now then, but if it starts to come up again just recomment or reopen and we'll look a bit deeper. Thanks

**Closed by Thomas101** 2018-11-19 11:01 UTC
Labels: bug, electron-3-0-fix, follow-up, os:linux
