### ISSUE TITLE
New version very slow on MacOS

### ISSUE THREAD

**Issue by jaygorrell** [wavebox/waveboxapp#1158] opened 2019-12-11 14:19 UTC
* Wavebox Version: 4.11.6
* Operating System & Version: MacOS Mojave 10.14.6

After installing the new version, my laptop is at a crawl to the point that I lost 35% battery in an hour. Closing Wavebox immediately resolves the issue. Everything was perfect before installing 4.11.6 this morning.

**Comment by Thomas101** [comment] 2019-12-11 14:32
Thanks for reporting. How many and which accounts do you have added to Wavebox? Would you be able to send a screenshot of the task manager by going to Settings > Debug > Task monitor

**Comment by jaygorrell** [comment] 2019-12-11 14:40
I have 2 Gmail, Trello, Notion, Feedly, 8 Slack, 2 AWS, SMS, and What's App.

Task manager is being painful to use with the slow speed, but there's nothing abnormal there that I see. 200MB per slack, no CPU over 3%, etc. But regularly getting the spinning ball. Sync channels at the bottom does show Setup/Connected for only 2 of the Slacks, while all the others are red X. All of them have checkmarks for Maintenance though.

**Comment by jaygorrell** [comment] 2019-12-11 14:45
I just rolled back to 4.11.5 and can confirm things are back to normal. Happy to upgrade again after work hours if more testing is needed.

**Comment by Thomas101** [comment] 2019-12-11 14:48
Thanks. I'll take a look and let you know when there's an update available

**Comment by EnorMOZ** [comment] 2019-12-11 14:48
Fyi, I had a very similar experience. Rolling back also confirmed to go back to normal.

**Comment by hiperlouro** [comment] 2019-12-11 16:29
This may be related with https://github.com/wavebox/waveboxapp/issues/1160 since you are also using slack.

**Comment by jaygorrell** [comment] 2019-12-11 17:45
It could be. The task manager never showed crazy numbers like that for me but system activity monitor wouldn't even populate CPU % for quite some time either so something was hammering it.

**Comment by Thomas101** [comment] 2019-12-11 20:17
Hey, thanks for reporting. I've just pushed a beta version out (4.11.8) which should be much much better. It would be great if you could give it a try! Downloads are available on the releases page https://github.com/wavebox/waveboxapp/releases/tag/v4.11.8

**Comment by Thomas101** [comment] 2019-12-12 10:06
A fix for this has just gone out in 4.11.9 :)

**Closed** 2019-12-12 10:09 UTC

**Comment by jaygorrell** [comment] 2019-12-12 13:24
Working great. Thank you!
