### ISSUE TITLE
Keyboard shortcuts not working in Trello or Office 365

### ISSUE THREAD

**Issue by lkortebe** [wavebox/waveboxapp#546] opened 2018-01-23 20:16 UTC
* Which version of Wavebox are you using? [e.g. 3.9.0]
* Which Operating System are you using? [e.g. Windows 7]

My Trello keyboard shortcuts just stopped working. They work fine in a browser. 
Also (relatedly?), a few days ago, Ctrl+C stopped copying text within all Office 365 tools. I can paste fine. All shortcuts work fine in a browser.

**Comment by nmat** [comment] 2018-01-24 08:25
@lkortebe does right click and triggering the copy/paste work as intended inside the application?

**Comment by lkortebe** [comment] 2018-01-24 20:03
@nmat 
Yes. 
Looks like Ctrl+c is defaulting to choosing "Categories" in the Mail app, and to doing nothing in other Office 365 tools. Could this be a setting I toggled?

Trello shortcuts are working again!

**Comment by nmat** [comment] 2018-01-25 07:14
Yeah office365 has some oddness going on with shortcuts. Not sure why. Until further development and understanding of what is going on when using office365 be patient since its hopefully going to be better later on.

I have noticed that most of the shortcuts that affects things are when using the Mail app inside office365 but not when using the other applications. I think its very strange behavior from office365 to overwrite or use strange keys but as mentioned before be patient. :)

**Comment by Thomas101** [comment] 2018-01-25 10:10
As for Trello, I'm guessing they had a broken release.

For Office, I might have an idea what's behind this.

**Comment by Thomas101** [comment] 2018-02-08 09:27
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by lkortebe** [comment] 2018-02-08 14:26
Thanks, Office copy/paste is back.


Mia Kortebein
Program Coordinator

Community Involved in Sustaining Agriculture (CISA)
One Sugarloaf Street
South Deerfield, MA 01373
(413) 665-7100
www.buylocalfood.org<https://mail.buylocalfood.org/owa/UrlBlockedError.aspx>
________________________________

**Comment by Thomas101** [comment] 2018-03-20 09:21
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2018-03-20 09:21 UTC
Labels: account:microsoft, bug, in-beta
