### ISSUE TITLE
Huge memory spikes if notification is not dismissed

### ISSUE THREAD

**Issue by EvHaus** [wavebox/waveboxapp#470] opened 2017-11-18 02:47 UTC
* Which version of Wavebox are you using?: 3.5.0
* Which Operating System are you using?: Windows 10

Wavebox starts using an insane amount of RAM if a notification is not dismissed. Steps to reproduce:

- Wait for a calendar notification to come up
- Leave it undismissed for a few hours
- Check the task manager to see how much RAM is being used

Here's what happens after I come home from work and my home computer has notifications that haven't been dismissed:

![capture](https://user-images.githubusercontent.com/226640/32976266-8c9653c6-cbc7-11e7-838f-b3d55dfee902.PNG)

What's extra frustrating is that I've set ALL my accounts to have Google Calendar notifications disabled -- but they still pop up. But that's a different issue.

**Comment by TheWithz** [comment] 2017-11-18 03:27
#453 @Thomas101 this could very well be the reason for my issue as well. When I'm in class, I'm not dismissing the notifications, which is why I could never reproduce it when I was working at my computer.

**Comment by nmat** [comment] 2017-11-18 09:24
interesting.....I wonder if triggering the notifications will trigger a event several times for both default and enhanced?

Could there be a difference in the methods of closing the event or something?

**Comment by Thomas101** [comment] 2017-11-20 09:15
@TheWithz it looks like this could be the cause of what you're seeing too. I'll put a patch in for the next beta to use something other than alert. I think the blocking nature of it may be what's causing the issue.

**Comment by EvHaus** [comment] 2017-11-20 16:38
@Thomas101 Are you aware of any known issues with Calendar notifications? I have Wavebox set to disable Calendar notifications, but they still keep popping up for one of my accounts. I'm talking about the `alert()` style notifications, not the OS-style notifications.

**Comment by Thomas101** [comment] 2017-11-21 09:23
@EvHaus if you're using the new style calendar, you turn of notifications all-together from your Google Calendar Settings. These can be found by pressing the cog in the top right of the screen. If you're not yet using the new style calendar you can switch between alert and notifications by toggling "Use Interruptive Notifications"
![scrn](https://user-images.githubusercontent.com/103586/33064389-6720dc0a-ce9d-11e7-9ba9-625d49cf67dd.png)

**Comment by Thomas101** [comment] 2017-11-21 09:23
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2017-11-23 09:24
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-11-23 09:24 UTC
Labels: bug, in-beta
