### ISSUE TITLE
cannot click anything in google calendar

### ISSUE THREAD

**Issue by gaambo** [wavebox/waveboxapp#834] opened 2018-10-25 07:55 UTC
* Wavebox Version: [e.g. 3.0.0]
4.4.0
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
mac osx mojava
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
gmail

**Expected & actual behavior**
the google calendar view of my colleague does not work he cannot click anything in calendar - but sees all events. so he cannot change days, show/hide calendars, open events,... 
the javascript console shows the following: 
```
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
5/calendar/_/scs/calendar-static/_/js/k=calendar.mat.de.Qqoy9o-fXuI.O/am=QAwQciIE/rt=j/d=0/rs=ANwU0p42y1cjvnuyj9hmM66nxhBeE0yx7A/m=sykc,wGM7Jc,IG7qPe,vGlHXb,sy8l,syn9,synb,EcW08c,ngQCce,sy3i,sy3k,sy3j,sy3f,sykd,LykBS Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
```
i guess that's the problem. on my microsoft surface with windows 10 and the same wavebox version it works. 
we tried reloading, resyncing and removing & readding the account - still the same issue. it works in chrome browser.

**Steps to reproduce**

**Is the bug persistent or intermittent?**
happens always

**Screenshots**
see console output above

**Additional information**

**Comment by gaambo** [comment] 2018-10-25 15:03
it happens when using a logitech mouse (which otherwise works correctly), but using the touchpad brings the same problems.

**Comment by nmat** [comment] 2018-10-25 19:12
Touch pad work for me on macbook pro using macos mojave. If you disconnect the logitech mouse completely and everything else does it work then?

**Comment by gaambo** [comment] 2018-10-29 06:43
disconnecting the mouse did not resolve the problem. i actually think it is connected to the error in the console about not being able to load some javascript files - and therefore the click handler for all the elements are not registered. he of course can click - but nothing happens in the calendar.   
**but:** my colleague just rebooted his macbook (did that a couple of times last week without any effect) and now it works correctly again. 
still these javascript errors seem uncommon, or? should i close this?

**Comment by Thomas101** [comment] 2018-11-05 13:15
The error was probably generated by Calendar/Gmail. It looks like a http request failed, however it's hard to say if this is the root cause. The Calendar code could cope with this and continue without any issue.

If it's fixed after a restart, it's going to be a hard one to track down. Could be a problem anywhere from the OS up to what's hosted in Wavebox, to Wavebox itself. If you're happy for me to do so I'll close this off, but if it comes up again re-open and add any additional info. I'll see if we can get to the bottom of it!

**Closed by Thomas101** 2018-11-05 13:15 UTC
