### ISSUE TITLE
Ghost downloads

### ISSUE THREAD

**Issue by asferens** [wavebox/waveboxapp#95] opened 2017-04-19 03:04 UTC
Wavebox 3.1.5 | Mac OSX 10.11.6

Files showing up in downloads e.g. filename.pdf.waveboxdownload

Can't view them in the terminal via viewing normal or hidden files, only seen visually as the pop up module pre opening a finder window.

**Comment by Thomas101** [comment] 2017-04-25 08:29
I have seen this before. Are you seeing the ghost files just in the dock or also in a finder window?

**Comment by asferens** [comment] 2017-04-25 08:30
Only the dock

**Comment by Thomas101** [comment] 2017-04-25 09:23
Thanks. That's where I've seen it too. Restarting the dock did fix it, but obviously that's not a permanent solution. I'll take another look to see if there's anything else I can do in Wavebox to force the dock to update

**Comment by Thomas101** [comment] 2017-04-28 11:12
I can't find anything solid on what's causing this. Of what I can find on Google the only solution is restarting the dock.

I've added in a little delay between receiving the download complete call and moving the file. Hopefully this will give the dock a little bit more time to catch up.

This will be going out in version 3.1.6 soon

**Comment by Thomas101** [comment] 2017-05-04 12:16
Hi, I've just pushed 3.1.6 out which hopefully fixes this. If you see the issue again re-comment and I'll take another look. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by adrianaoun** [comment] 2017-06-11 20:01
I'm seeing this happen on v3.1.8

**Comment by asferens** [comment] 2017-06-12 06:16
Sorry to say I still am as well

**Comment by Thomas101** [comment] 2017-06-12 14:44
okay thanks. I'll see if I can take another look. Do you see it everytime or just sometimes?

@asferens did you see any improvement after 3.1.6?

@adrianaoun which version of macOS are you using?

**Comment by adrianaoun** [comment] 2017-06-12 14:45
The latest Mac OS

**Comment by asferens** [comment] 2017-06-12 16:21
Hard to say, seems to be pretty random - maybe happens 30% of the time with downloads.

**Comment by zellerjeff** [comment] 2017-10-02 03:24
Hi, I can consistently replicate this issue. Wavebox 3.3.0.
2016 MacBook Pro 15", Mac OS X High Sierra 10.13
<img width="541" alt="screen shot 2017-10-01 at 11 23 31 pm" src="https://user-images.githubusercontent.com/22085849/31063295-b6d638aa-a6ff-11e7-9b6c-b22185afb7a9.png">

**Comment by Thomas101** [comment] 2017-10-02 11:31
This does seem more pronounced with High Sierra. I'll take another look into this. If I can reproduce it, makes it much easier to diagnose :)

**Comment by brianlenz** [comment] 2017-10-22 06:07
FWIW, I am also experiencing this issue regularly after upgrading to High Sierra (10.13) on Wavebox 3.4.2.

**Comment by Thomas101** [comment] 2017-10-25 09:52
We've decided to drop the `.waveboxdownload` extension for the time-being as it seems to be causing more trouble than good. Due out in the next beta shortly and stable over the next week-or-so

**Comment by Thomas101** [comment] 2017-10-26 14:59
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment] 2017-11-01 08:43
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Closed by Thomas101** 2017-11-01 08:43 UTC
Labels: bug, in-beta, os:macOS, sporadic/hard to reproduce
