### ISSUE TITLE
Gnome-Shell interation problem on Ubuntu 18.04

### ISSUE THREAD

**Issue by efwe** [wavebox/waveboxapp#681] opened 2018-05-19 00:08 UTC
* Wavebox Version: 3.4.16
* Operating System & Version: Ubuntu 18.04 LTS
* (Linux only) Install method: Snap

I see many  entries like the following. It looks like `gnome-shell-extension-appindicator` is called every second and the 'unable to lookup icon' is from the `appIndicator.js`. Funny enough i see the 
number of unread mails in the status bar and when the app is in this endless loop i see something like
[1] -> [2] -> [1] -> [2]

> May 19 02:03:47 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Attempting to re-register :1.103/org/ayatana/NotificationItem/wavebox1; resetting instead
> May 19 02:03:47 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Item :1.103/org/ayatana/NotificationItem/wavebox1 is already registered
> May 19 02:03:49 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Attempting to re-register :1.103/org/ayatana/> May 19 02:03:47 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Attempting to re-register :1.103/org/ayatana/NotificationItem/wavebox1; resetting instead
> May 19 02:03:47 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Item :1.103/org/ayatana/NotificationItem/wavebox1 is already registered
> May 19 02:03:49 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Attempting to re-register :1.103/org/ayatana/NotificationItem/wavebox1; resetting instead
> May 19 02:03:49 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Item :1.103/org/ayatana/NotificationItem/wavebox1 is already registered
> May 19 02:03:49 osa gnome-shell[1766]: [AppIndicatorSupport-FATAL] unable to lookup icon for wavebox1_2098NotificationItem/wavebox1; resetting instead
> May 19 02:03:49 osa gnome-shell[1766]: [AppIndicatorSupport-WARN] Item :1.103/org/ayatana/NotificationItem/wavebox1 is already registered
> May 19 02:03:49 osa gnome-shell[1766]: [AppIndicatorSupport-FATAL] unable to lookup icon for wavebox1_2098

this logging can be ended by really switching to wavebox

i also had one not reproducable crash but i leave the trace here for reference

> May 19 02:03:49 osa gnome-shell[1766]: [AppIndicatorSupport-FATAL] unable to lookup icon for wavebox1_2098
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]: 3.14.6
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]: TypeError: Cannot read property 'show' of null
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at t.a.show (/snap/wavebox/109/resources/app/bin/app/index.js:1:21693)
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at Function.processWindowVisibility (/snap/wavebox/109/resources/app/bin/app/index.js:1:281919)
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at Function.processSingleInstanceArgs (/snap/wavebox/109/resources/app/bin/app/index.js:1:437466)
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at Function.<anonymous> (/snap/wavebox/109/resources/app/bin/app/index.js:1:455558)
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]: TypeError: Cannot read property 'show' of null
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at t.a.show (/snap/wavebox/109/resources/app/bin/app/index.js:1:21693)
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at Function.processWindowVisibility (/snap/wavebox/109/resources/app/bin/app/index.js:1:281919)
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at Function.processSingleInstanceArgs (/snap/wavebox/109/resources/app/bin/app/index.js:1:437466)
> May 19 02:03:49 osa wavebox_wavebox.desktop[4884]:     at Function.<anonymous> (/snap/wavebox/109/resources/app/bin/app/index.js:1:455558)
> May 19 02:03:49 osa gnome-shell[1766]: Object .Gjs_AppIndicatorIconActor__1 (0x55861368fa20), has been already finalized. Impossible to set any property to it.
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: == Stack trace for context 0x558611b12330 ==
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #0 0x7fffddf43f60 b   resource:///org/gnome/gjs/modules/_legacy.js:83 (0x7fc61f5b5de0 @ 87)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #1 0x558611ebe800 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:93 (0x7fc61c9c2098 @ 58)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #2 0x7fffddf452e0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fc61f5b5de0 @ 71)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #3 0x7fffddf45af0 b   self-hosted:915 (0x7fc61f5f12b8 @ 367)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #4 0x7fffddf45be0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fc61f5d3230 @ 386)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #5 0x558611ebe778 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:190 (0x7fc61c9a8cd0 @ 22)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #6 0x7fffddf46f60 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fc61f5b5de0 @ 71)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #7 0x558611ebe6d0 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:176 (0x7fc61c99bf78 @ 26)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #8 0x7fffddf482e0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fc61f5b5de0 @ 71)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #9 0x558611ebe630 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:170 (0x7fc61c99bef0 @ 68)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #10 0x7fffddf49660 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fc61f5b5de0 @ 71)
> May 19 02:03:49 osa org.gnome.Shell.desktop[1766]: #11 0x7fffddf49e90 b   self-hosted:917 (0x7fc61f5f12b8 @ 394)
> 
after restart of the app everything looks normal.

~fw

**Comment by Thomas101** [comment] 2018-05-21 08:05
Thanks for reporting. There's a few open issues on Ubuntu with similar log messages [[#1739468]](https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1739468) [[#1740993](https://bugs.launchpad.net/indicator-multiload/+bug/1740993)] so it looks like it may be an upstream issue with Ubuntu.

Looking through the crash log it looks like it happens when you try to launch the app when it's already running. There's a handover procedure that runs when this happens which refocuses the window and basically give the appearance that you've just switched to the app. Looking through the code, I think there could be an edge case where if you try to launch the app twice in quick succession you could end up here, but I'll have to have a try at reproducing.

**Comment by Thomas101** [comment] 2019-01-23 15:31
Thanks for taking time to report this. I'm going to close it off though, as we're already setting the environment variables as suggested and the upstream issues with Ubuntu remain open as regards this.

If you think there's something we can do to reduce the logs though, feel free to re-comment and we'll give it a try. Thanks!

**Closed by Thomas101** 2019-01-23 15:31 UTC
Labels: investigate, os:linux
