### ISSUE TITLE
attaching error: app detects zero size

### ISSUE THREAD

**Issue by regisz** [wavebox/waveboxapp#339] opened 2017-08-04 10:10 UTC
Hi,

If I try to add one or more attachments into a new email, the wavebox says the size of files are zero, but it is not true.

* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.2.0
Made with ♥ at wavebox.io

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
$ lsb_release -a
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
$ uname -a
Linux balage-noti 4.12.4-041204-generic #201707271932 SMP Thu Jul 27 23:33:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Thomas101** [comment] 2017-08-04 11:02
Hi, thanks for reporting. So I can try to reproduce the issue my end, I would be great to have a little bit more info...

* Which method did you use to install Wavebox (e.g. deb, snap, tar, repo etc...). 
* Which account type is this with (.e.g Gmail, Google Inbox, Outlook, etc...)
* Which method did you use to upload (e.g. drag & drop, pressing an attach button etc)
* If you send the emails do the attachments send correctly or does it fail?

Thanks

**Comment by regisz** [comment] 2017-08-04 11:41
- Which method did you use to install Wavebox (e.g. deb, snap, tar, repo etc...).
snap
- Which account type is this with (.e.g Gmail, Google Inbox, Outlook, etc...)
Gmail
- Which method did you use to upload (e.g. drag & drop, pressing an attach button etc)
attach button
- If you send the emails do the attachments send correctly or does it fail?
I can not attach anything, the app does not allow it. I get an error message window, where the reason is that the file size is zero.

**Comment by Thomas101** [comment] 2017-08-04 13:52
Thanks for the info. I wonder if this is down to the snap package sandbox environment. I'll take a look to see what I can do

**Comment by Thomas101** [comment] 2017-09-01 13:13
@regisz just been looking into this, if you try attaching an image from somewhere in your userspace (e.g. desktop) does it work?

**Comment by regisz** [comment] 2017-09-04 11:06
yes, I can attach a file from my Desktop.

**Comment by Thomas101** [comment] 2017-09-05 08:50
Would you be able to try with the 3.3.0 and see if that works? Also if you run `snap --version` what versions do you get out?

**Comment by regisz** [comment] 2017-09-05 08:56
my Wavebox version:

> Version 3.3.0
> Made with ♥ at wavebox.io

and 
> $ snap --version
> snap    2.27.5
> snapd   2.27.5
> series  16
> ubuntu  16.04
> kernel  4.13.0-041300-generic

I tried it again, but the issue is the same :(.

**Comment by Thomas101** [comment] 2017-09-06 08:56
Hmmm that's weird. I've just tried a fresh install of 16.04 and updated to the same versions with success. I wonder if it's a permission problem. If you `ls -al` on the file you're trying to upload and also the documents directory what's the permission signature?

**Comment by regisz** [comment] 2017-09-06 09:06
I checked it, the rights are the same: `-rw-rw-r--`.
But, I think I found the problem: the file name, the none ascii characters. I'm Hungarian, so I use sometimes some special characters in my file names :).

**Comment by Thomas101** [comment] 2017-09-06 09:10
Ah! That could be it. Can you paste the failing filename, if I can reproduce it my end it can see if it's an issue with Wavebox or upstream with snap and report it :)

**Comment by regisz** [comment] 2017-09-06 09:15
Yes, of course :)
The filename: `0_zenék.txt`

**Comment by Thomas101** [comment] 2017-09-06 09:19
I'd like to say that failed for me too, but....

![screen shot 2017-09-06 at 10 18 24](https://user-images.githubusercontent.com/103586/30104212-d204af16-92ec-11e7-8d13-dee20a623333.png)

**Comment by regisz** [comment] 2017-09-06 09:44
hm, interesting.
But, somewhy snap does not work, I get the next error message: `snap-confine has elevated permissions ...`. I tried to reinstall snap, but it did not help.
So, I downloaded the deb package of wavebox, installed it, and now the attaching works perfectly.

**Comment by Thomas101** [comment] 2017-09-12 07:33
Thanks for that info. A bit of Googling doesn't reveal any answers, but a few people have said that it behaves differently with different kernel versions. It sounds like it's probably an upstream issue with snap, so hopefully it will get patched in a future release. Going to close this off for now as it seems to be working with deb packages. Thanks for all your help :)

**Closed by Thomas101** 2017-09-12 07:33 UTC
Labels: os:linux, packager:snap

**Comment by regisz** [comment] 2017-09-12 07:41
Yes, I found the kernel and snap problem too. But I found your apt repository, so now I use it instead of snap :).
