### ISSUE TITLE
Sync WaveBox across devices

### ISSUE THREAD

**Issue by amancevice** [wavebox/waveboxapp#506] opened 2017-12-14 11:17 UTC
* `3.6.0`

* macOS `10.13.2`

I have a paid WaveBox account and have installed WaveBox on two devices (work & home, both macs, both on `10.13.2`). It would be nice if WaveBox synchronized the app configuration accross devices -- or at least gave the option to do so.

I usually add new accts to WaveBox on my work computer and it's a bit of a hassle to then go do the same thing on my home computer. It'd be cool if the acct just showed up.

The acct credentials obviously wouldn't need to sync, but if the specific WaveBox settings (type of acct, user name, colors, &c) did I think this would be a great feature.

**Comment by Thomas101** [comment] 2017-12-15 09:07
This is something we're working towards adding but just haven't gotten around to yet. It may be a bit late now, but if you need to setup another machine there's some instructions [here](https://wavebox.io/kb/copying-accounts) on how to import/export between machines

**Comment by tonybyng** [comment] 2018-04-28 12:28
+1 on this , both Linux boxes (although I guess a sync shouldnt matter what the client is)

**Comment by maxim-lian** [comment] 2018-05-15 05:04
Where are those files stored? If it's in a consistent location, we could use [mackup](https://github.com/lra/mackup) to sync across devices

**Comment by max-imlian** [comment] 2018-07-21 22:39
I didn't find anything. Would be interested to know if that works!

**Comment by Thomas101** [comment] 2018-08-15 11:51
Hi, we've added the ability to import and export accounts using cloud sync in 3.14.14 beta ([more info on beta](https://wavebox.io/kb/beta-channel)). If you head into settings and then `Data & Sync` there are some tools to restore and save your profile. It's not full on sync but gives some more tooling to restore.

I'll keep this open while we work on adding full sync

**Comment by logankoester** [comment] 2018-09-03 05:43
I have the same problem as @jessewallace. Syncing from an existing Linux host to a Windows host appears to have no effect on the target.

**Comment by Thomas101** [comment] 2018-09-03 07:45
Thanks, I'll have a look and get this patched

**Comment by logankoester** [comment] 2018-09-03 09:07
@Thomas101 Great! @me if you need any further information to reproduce.

**Comment by dwithnall** [comment] 2018-09-08 00:28
Howdy,

Can confirm that the cloud sync doesn't work in any direction (Linux -> windows, or windows -> windows) using 3.14.15 beta currently. Mildly annoying as I have 13 accounts to setup and I can't remember what they all were :)

Also, you have a typo in the Debug settings "Write app merics log"

D.

**Comment by Thomas101** [comment] 2018-09-10 09:05
Thanks everyone, this should be working now

**Comment by Thomas101** [comment] 2018-09-10 10:09
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!

**Comment by bane73** [comment] 2019-03-20 21:55
> Hi, we've added the ability to import and export accounts using cloud sync in 3.14.14 beta ([more info on beta](https://wavebox.io/kb/beta-channel)). If you head into settings and then `Data & Sync` there are some tools to restore and save your profile. It's not full on sync but gives some more tooling to restore.
> 
> I'll keep this open while we work on adding full sync

@Thomas101 : I'm curious about this issue because it was closed as delivered but the only thing I'm seeing in the latest Wavebox is that *manual* cloud-sync up/down is implemented but not actual real-time syncing, which is what "sync" means to me. Just wondering if you could clarify.

I'm just trying to decide if I'm following-along correctly or not, whether or not I should open a ticket, and whether or not there's any appetite to go after the type of "sync" I am referring to. 

My use-case is that at work I pull up Wavebox and work all day long... as I work, I will make changes to my configuration and I would expect those changes to automatically sync to the cloud (not necessarily real-time, maybe hourly or a few times over the day)... when I go home, I want my Wavebox there to automatically be made aware of the earlier changes and re-sync so that my home Wavebox configuration matches the one I left at work. 

As an aside, I did see the other issue talking about having separate "profiles" such as "work" and "home". That feature is also very exciting and works into my anticipated-workflow above in the sense that on my breaks at work I might flip over to my "home"-profile to take care of some personal work and then later at home I might monitor my "work"-profile in case we are having after-hours production/support issues.

**Comment by Thomas101** [comment] 2019-03-22 11:48
@bane73 you're right, I don't think this should have been closed - constant sync is something separate to the cloud backup/restore process that's already there.

**Comment by bane73** [comment] 2019-03-22 14:51
Thanks @Thomas101 , this is great news! I know teams can't typically make hard-promises about features/timelines but I appreciate the attention on the issue b/c I am just at the end of my trial and have been weighing whether or not to switch to a paid; seems like the project is active-enough I'll probably be making that switch.

**Comment by lens0021** [comment] 2023-02-24 13:20
I think there is a profile sync feature currently. https://wavebox.io/kb/what-is-profile-sync-faq/

**Closed** 2023-02-24 13:25 UTC
Labels: feature
