### ISSUE TITLE
MacOS dictation does not work (but does in Google Chrome)

### ISSUE THREAD

**Issue by c-lawlz** [wavebox/waveboxapp#262] opened 2017-06-18 16:39 UTC
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.12.5

(this was tested in Keep and Docs)
If I double press the fn key - I get the sound notification of a failed dictation.  This does work on Chrome though.  I hope it's an easy fix, would love to use this feature on my mac (since Keep doesn't support dictation via the web yet).

Thanks!
Corey

**Comment by nmat** [comment] 2017-11-11 23:10
@c-lawlz I have been testing it a bit here on my macOS machine. The double tap of fn key I am not following is this something you have setup yourself?

Also tested the Right click to see if there is a spellchecking in keep and it does come up for me here. So is it the double tap of fn you want to have implemented?

**Comment by Thomas101** [comment] 2017-11-13 11:15
Using double fn, this has started to work me. I'm wondering if one of the latest versions of electron that Wavebox is using has fixed this. Okay to close?

**Comment by nmat** [comment] 2017-11-13 12:03
@Thomas101 can you provide example of this so I can test it when I am home to see if I can verify also?

**Comment by Thomas101** [comment] 2017-11-13 13:32
I tried with Inbox, just click in the message compose area and then hit fn twice. You get a nice dictation box, start talking and hey presto

![scrn](https://user-images.githubusercontent.com/103586/32728108-04d783e0-c877-11e7-9c66-c052374d5904.png)

**Comment by nmat** [comment] 2017-11-13 20:48
Yes, confirmed and tested with Dictation turned on for macOS and works in both slack and gmail.

I would say that this is fixed now or invalid bug since it does seem to work.

**Closed** 2017-11-14 09:38 UTC
Labels: investigate, os:macOS
